/* Formatted on 5/14/2020 5:45:15 PM (QP5 v5.227.12220.39754) */
SELECT SMBPOGN_PIDM PIDM,                                        ------PROGRAM
       SMBPOGN_REQUEST_NO REQUEST_NO,
       SMBPOGN_PROGRAM PROGRAM_code,
       SGBSTDN_LEVL_CODE LEVL_CODE,
       SGBSTDN_CAMP_CODE CAMP_CODE,
       SGBSTDN_COLL_CODE_1 COLL_CODE,
       SGBSTDN_dept_CODE dept_CODE,
       SGBSTDN_MAJR_CODE_1 MAJR_CODE,
       SMBPOGN_MET_IND MET_IND,
       SMBPOGN_TERM_CODE_CATLG TERM_CODE_CATLG,
       SMBPOGN_TERM_CODE_EFF prog_TERM_CODE_EFF,
       SMBPOGN_TERM_CODE_EFF_AREA CODE_EFF_AREA,
       SMBPOGN_REQ_CREDITS_OVERALL prog_REQ_CREDITS_OVERALL,
       SMBPOGN_REQ_COURSES_OVERALL prog_REQ_COURSES_OVERALL,
       SMBPOGN_ACT_CREDITS_OVERALL prog_ACT_CREDITS_OVERALL,
       SMBPOGN_ACT_COURSES_OVERALL prog_ACT_COURSES_OVERALL,
       ------------------------------AREA
       SMBAOGN_AREA AREA_code,
       SMBAOGN_MET_IND area_MET_IND,
       SMBAOGN_REQ_CREDITS_OVERALL area_REQ_CREDITS_OVERALL,
       SMBAOGN_REQ_COURSES_OVERALL area_REQ_COURSES_OVERALL,
       SMBAOGN_ACT_CREDITS_OVERALL area_ACT_CREDITS_OVERALL,
       SMBAOGN_ACT_COURSES_OVERALL area_ACT_COURSES_OVERALL,
       ------------------ COURSES
       SMRDORQ_CAA_SEQNO SEQNO,
       SMRDORQ_MET_IND crse_MET_IND,
       SMRDORQ_SUBJ_CODE SUBJ_CODE,
       SMRDORQ_CRSE_NUMB_LOW CRSE_NUMB,
       P.SMRDOUS_CRN crn,
       P.SMRDOUS_TERM_CODE TERM_CODE,
       P.SMRDOUS_GRDE_CODE GRDE_CODE,
       ADJ.SMRDOUS_SUBJ_CODE || ADJ.SMRDOUS_CRSE_NUMB ADJ_SUBJ
  FROM SMBPOGN,
       sgbstdn,
       SMBAOGN,
       SMRDORQ,
       SMRDOUS P,
       SMRDOUS ADJ
 WHERE     SGBSTDN_PIDM = SMBPOGN_PIDM
       AND SMBPOGN_REQUEST_NO = (SELECT MAX (SMBPOGN_REQUEST_NO)
                                   FROM SMBPOGN
                                  WHERE SMBPOGN_PIDM = SGBSTDN_PIDM)
       AND SGBSTDN_TERM_CODE_EFF = (SELECT MAX (SGBSTDN_TERM_CODE_EFF)
                                      FROM SGBSTDN
                                     WHERE SGBSTDN_PIDM = SMBPOGN_PIDM)
       AND SMBPOGN_PROGRAM = SGBSTDN_PROGRAM_1
       AND SMBPOGN_TERM_CODE_CATLG = SGBSTDN_TERM_CODE_CTLG_1
       AND SMBAOGN_PIDM = SMBPOGN_PIDM
       AND SMBAOGN_REQUEST_NO = SMBPOGN_REQUEST_NO
       AND SMRDORQ_PIDM = SMBPOGN_PIDM
       AND SMRDORQ_REQUEST_NO = SMBPOGN_REQUEST_NO
       AND SMRDORQ_AREA = SMBAOGN_AREA
       AND SMRDORQ_SUBJ_CODE IS NOT NULL
       AND P.SMRDOUS_PIDM(+) = SMBPOGN_PIDM
       AND P.SMRDOUS_REQUEST_NO(+) = SMBPOGN_REQUEST_NO
       AND P.SMRDOUS_AREA(+) = SMBAOGN_AREA
       AND P.SMRDOUS_CAA_SEQNO(+) = SMRDORQ_CAA_SEQNO
       AND ADJ.SMRDOUS_PIDM(+) = SMBPOGN_PIDM
       AND ADJ.SMRDOUS_REQUEST_NO(+) = SMBPOGN_REQUEST_NO
       AND ADJ.SMRDOUS_AREA(+) = SMBAOGN_AREA
       AND ADJ.SMRDOUS_CAA_SEQNO(+) = SMRDORQ_CAA_SEQNO
       AND ADJ.SMRDOUS_SUBJ_CODE(+) || ADJ.SMRDOUS_CRSE_NUMB(+) <>
              SMRDORQ_SUBJ_CODE || SMRDORQ_CRSE_NUMB_LOW
       --AND SMBAOGN_AREA=:AREA
       AND SGBSTDN_PIDM = 128852
UNION
SELECT SMBPOGN_PIDM PIDM,                                        ------PROGRAM
       SMBPOGN_REQUEST_NO REQUEST_NO,
       SMBPOGN_PROGRAM PROGRAM_code,
       SGBSTDN_LEVL_CODE LEVL_CODE,
       SGBSTDN_CAMP_CODE CAMP_CODE,
       SGBSTDN_COLL_CODE_1 COLL_CODE,
       SGBSTDN_dept_CODE dept_CODE,
       SGBSTDN_MAJR_CODE_1 MAJR_CODE,
       SMBPOGN_MET_IND MET_IND,
       SMBPOGN_TERM_CODE_CATLG TERM_CODE_CATLG,
       SMBPOGN_TERM_CODE_EFF prog_TERM_CODE_EFF,
       SMBPOGN_TERM_CODE_EFF_AREA CODE_EFF_AREA,
       SMBPOGN_REQ_CREDITS_OVERALL prog_REQ_CREDITS_OVERALL,
       SMBPOGN_REQ_COURSES_OVERALL prog_REQ_COURSES_OVERALL,
       SMBPOGN_ACT_CREDITS_OVERALL prog_ACT_CREDITS_OVERALL,
       SMBPOGN_ACT_COURSES_OVERALL prog_ACT_COURSES_OVERALL,
       ------------------------------AREA
       SMBAOGN_AREA AREA_code,
       SMBAOGN_MET_IND area_MET_IND,
       SMBAOGN_REQ_CREDITS_OVERALL area_REQ_CREDITS_OVERALL,
       SMBAOGN_REQ_COURSES_OVERALL area_REQ_COURSES_OVERALL,
       SMBAOGN_ACT_CREDITS_OVERALL area_ACT_CREDITS_OVERALL,
       SMBAOGN_ACT_COURSES_OVERALL area_ACT_COURSES_OVERALL,
       ------------------ COURSES
       SMRDRRQ_CAA_SEQNO,
       NVL (P.SMRDOUS_EARNED_IND, 'N') MET_IND,
       SMRDRRQ_SUBJ_CODE,
       SMRDRRQ_CRSE_NUMB_LOW,
       P.SMRDOUS_CRN,
       P.SMRDOUS_TERM_CODE,
       P.SMRDOUS_GRDE_CODE,
       ADJ.SMRDOUS_SUBJ_CODE || ADJ.SMRDOUS_CRSE_NUMB ADJ_SUBJ
  FROM SMBPOGN PROG,
       SMBAOGN,
       sgbstdn,
       SMRDRRQ,
       SMRDOUS P,
       SMRDOUS ADJ
 where SGBSTDN_PIDM = SMBPOGN_PIDM
       AND SMBPOGN_REQUEST_NO = (SELECT MAX (SMBPOGN_REQUEST_NO)
                                   FROM SMBPOGN
                                  WHERE SMBPOGN_PIDM = SGBSTDN_PIDM)
       AND SGBSTDN_TERM_CODE_EFF = (SELECT MAX (SGBSTDN_TERM_CODE_EFF)
                                      FROM SGBSTDN
                                     WHERE SGBSTDN_PIDM = SMBPOGN_PIDM)
       AND SMBPOGN_PROGRAM = SGBSTDN_PROGRAM_1
       AND SMBPOGN_TERM_CODE_CATLG = SGBSTDN_TERM_CODE_CTLG_1
       AND SMBAOGN_PIDM = SMBPOGN_PIDM
       AND SMBAOGN_REQUEST_NO = SMBPOGN_REQUEST_NO
               AND SMRDRRQ_PIDM = SMBPOGN_PIDM
               AND SMRDRRQ_REQUEST_NO = SMBPOGN_REQUEST_NO
               AND SMRDRRQ_AREA = SMBAOGN_AREA
               AND P.SMRDOUS_PIDM(+) = SMBPOGN_PIDM
               AND P.SMRDOUS_REQUEST_NO(+) = SMBPOGN_REQUEST_NO
               AND P.SMRDOUS_AREA(+) = SMBAOGN_AREA
               AND P.SMRDOUS_CAA_SEQNO(+) = SMRDRRQ_CAA_SEQNO
               AND P.SMRDOUS_KEY_RULE(+) = SMRDRRQ_KEY_RULE
               AND P.SMRDOUS_RUL_SEQNO(+) = SMRDRRQ_RUL_SEQNO
               AND ADJ.SMRDOUS_PIDM(+) = SMBPOGN_PIDM
               AND ADJ.SMRDOUS_REQUEST_NO(+) = SMBPOGN_REQUEST_NO
               AND ADJ.SMRDOUS_AREA(+) = SMBAOGN_AREA
               AND ADJ.SMRDOUS_CAA_SEQNO(+) = SMRDRRQ_CAA_SEQNO
               AND ADJ.SMRDOUS_KEY_RULE(+) = SMRDRRQ_KEY_RULE
               AND ADJ.SMRDOUS_RUL_SEQNO(+) = SMRDRRQ_RUL_SEQNO
               AND ADJ.SMRDOUS_SUBJ_CODE(+) || ADJ.SMRDOUS_CRSE_NUMB(+) <>
                      SMRDRRQ_SUBJ_CODE || SMRDRRQ_CRSE_NUMB_LOW 
                      AND SGBSTDN_PIDM = 128852;