CREATE OR REPLACE PROCEDURE ACD_ADV_DISTRIBUTE(P_SESSION_ID VARCHAR2     )
IS 
CURSOR GET_FAC IS SELECT FAC_PIDM,QUOTA FROM ACD_ADV_FAC_PROC WHERE SESSION_ID=P_SESSION_ID;
CURSOR GET_STD IS SELECT STD_PIDM FROM ACD_ADV_STD_PROC WHERE SESSION_ID=P_SESSION_ID;

BEGIN
 
FOR STD_REC IN GET_STD LOOP
NULL; 

 

 

END LOOP; 

END;
 