Insert into GLBSLCT
   (GLBSLCT_APPLICATION, GLBSLCT_SELECTION, GLBSLCT_CREATOR_ID, GLBSLCT_DESC, GLBSLCT_LOCK_IND, 
    GLBSLCT_ACTIVITY_DATE, GLBSLCT_TYPE_IND)
 Values
   ('STUDENT', 'DPLM_STD', 'SAISUSR', 'DPLM_STD', 'N', 
    SYSDATE, NULL);
 

Insert into GLBEXTR
   SELECT 'STUDENT', 'DPLM_STD', 'SAISUSR', 'SAISUSR', PIDM, 
    SYSDATE, 'S', NULL  FROM 
    (  SELECT SG.SGBSTDN_PIDM   PIDM
FROM SGBSTDN SG
where  SG.SGBSTDN_LEVL_CODE='œ»'
AND SG.SGBSTDN_TERM_CODE_EFF=(SELECT MAX(SGBSTDN_TERM_CODE_EFF) FROM SGBSTDN
WHERE SGBSTDN_PIDM=SG.SGBSTDN_PIDM)
AND SG.SGBSTDN_STST_CODE NOT IN ('ÿÌ','ŒÃ','„”','ÿ”')
 
   );