/* Formatted on 13/09/2021 09:44:36 (QP5 v5.227.12220.39754) */
DECLARE
   V_PROG_CODE       VARCHAR2 (15) := '4M12HRMO43';
   V_NEW_EFF_TERM    VARCHAR2 (8) := '144310';
   V_OLD_EFF_TERM    VARCHAR2 (8) := '000000';
   l_SMBPGEN_count   NUMBER := 0;
   l_SMBAGEN_count   NUMBER := 0;
   l_SMRPAAP_count   NUMBER := 0;
   l_SMRACAA_count   NUMBER := 0;
   l_SMBARUL_count   NUMBER := 0;
BEGIN
   --SMBPGEN
   UPDATE SMBPGEN
      SET SMBPGEN_TERM_CODE_EFF = V_NEW_EFF_TERM
    WHERE     SMBPGEN_PROGRAM = V_PROG_CODE
          AND SMBPGEN_TERM_CODE_EFF = V_OLD_EFF_TERM;

   l_SMBPGEN_count := SQL%ROWCOUNT;
   DBMS_OUTPUT.put_line ('SMBPGEN UPDATED Rows : ' || l_SMBPGEN_count);



   --
   -- SMRPAAP

   UPDATE SMRPAAP
      SET SMRPAAP_TERM_CODE_EFF = V_NEW_EFF_TERM
    WHERE     SMRPAAP_PROGRAM = V_PROG_CODE
          AND SMRPAAP_TERM_CODE_EFF = V_OLD_EFF_TERM;

   l_SMRPAAP_count := SQL%ROWCOUNT;
   DBMS_OUTPUT.put_line ('SMRPAAP UPDATED Rows : ' || l_SMRPAAP_count);

   --
   UPDATE SMBAGEN
      SET SMBAGEN_TERM_CODE_EFF = V_NEW_EFF_TERM
    WHERE     SMBAGEN_AREA IN (SELECT SMRPAAP_AREA
                                 FROM SATURN.SMRPAAP
                                WHERE SMRPAAP_PROGRAM = V_PROG_CODE)
          AND SMBAGEN_TERM_CODE_EFF = V_OLD_EFF_TERM;

   l_SMBAGEN_count := SQL%ROWCOUNT;
   DBMS_OUTPUT.put_line ('SMBAGEN UPDATED Rows : ' || l_SMBAGEN_count);

   --
   UPDATE SMRACAA
      SET SMRACAA_TERM_CODE_EFF = V_NEW_EFF_TERM
    WHERE     SMRACAA_AREA IN (SELECT SMRPAAP_AREA
                                 FROM SATURN.SMRPAAP
                                WHERE SMRPAAP_PROGRAM = V_PROG_CODE)
          AND SMRACAA_TERM_CODE_EFF = V_OLD_EFF_TERM;

   l_SMRACAA_count := SQL%ROWCOUNT;
   DBMS_OUTPUT.put_line ('SMRACAA UPDATED Rows : ' || l_SMRACAA_count);


   UPDATE SMBARUL
      SET SMBARUL_TERM_CODE_EFF = V_NEW_EFF_TERM
    WHERE     SMBARUL_AREA IN (SELECT SMRPAAP_AREA
                                 FROM SATURN.SMRPAAP
                                WHERE SMRPAAP_PROGRAM = V_PROG_CODE)
          AND SMBARUL_TERM_CODE_EFF = V_OLD_EFF_TERM;

   l_SMBARUL_count := SQL%ROWCOUNT;
   DBMS_OUTPUT.put_line ('SMBARUL UPDATED Rows : ' || l_SMBARUL_count);
END;