UPDATE   WF_REQUEST_FLOW A  SET A.NOTES='Ì—ÃÏ „—«Ã⁄… «·Œœ„«  «·ÿ·«»Ì… »ﬂ·Ì… «·⁄·Ê„ ·«” ·«„ «·„·› Ê≈‰Â«¡ «·„⁄«„·…'
WHERE EXISTS (SELECT '1' FROM REQUEST_MASTER WHERE REQUEST_NO=A.REQUEST_NO 
AND  OBJECT_CODE in ('WF_CLEARANCE','WF_UN_WITHDRAW'))
AND A.ROLE_CODE='RO_DAR_AUDITOR'
AND A.ACTION_CODE='APPROVE'
AND A.NOTES IS NULL ;



-----
UPDATE   WF_REQUEST_FLOW A  SET A.NOTES=' ⁄ –— «·ﬂ·Ì… ⁄‰ ﬁ»Ê· «·ÿ·»'
WHERE EXISTS (SELECT '1' FROM REQUEST_MASTER WHERE REQUEST_NO=A.REQUEST_NO 
AND  OBJECT_CODE in ('WF_TRANSFER'))
AND A.ROLE_CODE='TRN_DEPT_HEAD'
AND A.ACTION_CODE='FR_REJECT_REQUEST'
AND A.NOTES IS NULL ;

UPDATE   WF_REQUEST_FLOW A  SET A.NOTES=' ⁄ –— «·ﬂ·Ì… ⁄‰ ﬁ»Ê· «·ÿ·»'
WHERE EXISTS (SELECT '1' FROM REQUEST_MASTER WHERE REQUEST_NO=A.REQUEST_NO 
AND  OBJECT_CODE in ('WF_TRANSFER'))
AND A.ROLE_CODE='RO_COLLEGE_DEAN'
AND A.ACTION_CODE='FR_REJECT_REQUEST'
AND A.NOTES IS NULL ;