 Insert into TWGRMENU
   (TWGRMENU_NAME, TWGRMENU_SEQUENCE, TWGRMENU_URL_TEXT, TWGRMENU_URL, TWGRMENU_URL_DESC, 
    TWGRMENU_IMAGE, TWGRMENU_ENABLED, TWGRMENU_DB_LINK_IND, TWGRMENU_SUBMENU_IND, TWGRMENU_TARGET_FRAME, 
    TWGRMENU_STATUS_TEXT, TWGRMENU_ACTIVITY_DATE, TWGRMENU_URL_IMAGE, TWGRMENU_SOURCE_IND)
 Values
   ('bmenu.P_StuMainMnu', 35, '„ÿ«»ﬁ… «·Œÿ… «·œ—«”Ì…', 'XWSKCMPL.P_DISPLAY_COMPLIANCE', NULL, 
    NULL, 'Y', 'Y', 'N', NULL, 
    '„ÿ«»ﬁ… «·Œÿ… «·œ—«”Ì…', TO_DATE('04/02/2019 12:19:39', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'L');
    
Insert into TWGRWMRL
   (TWGRWMRL_NAME, TWGRWMRL_ROLE, TWGRWMRL_ACTIVITY_DATE, TWGRWMRL_SOURCE_IND)
 Values
   ('XWSKCMPL.P_DISPLAY_COMPLIANCE', 'WEBUSER', TO_DATE('08/19/2019 09:22:49', 'MM/DD/YYYY HH24:MI:SS'), 'L');
 
SET DEFINE OFF;
Insert into TWGBWMNU
   (TWGBWMNU_NAME, TWGBWMNU_DESC, TWGBWMNU_PAGE_TITLE, TWGBWMNU_HEADER, TWGBWMNU_HEADER_IMAGE, 
    TWGBWMNU_SUBTITLE_IMAGE, TWGBWMNU_TOP_RIGHT_IMAGE, TWGBWMNU_TOP_LEFT_IMAGE, TWGBWMNU_BULLET_IMAGE, TWGBWMNU_SEP_IMAGE, 
    TWGBWMNU_L_MARGIN_WIDTH, TWGBWMNU_MAIN_TEXT_WIDTH, TWGBWMNU_R_MARGIN_WIDTH, TWGBWMNU_HELP_URL, TWGBWMNU_HELP_LINK, 
    TWGBWMNU_HELP_IMAGE, TWGBWMNU_BGCOLOR, TWGBWMNU_BG_IMAGE, TWGBWMNU_COMMENT, TWGBWMNU_TEXT_COLOR, 
    TWGBWMNU_LINK_COLOR, TWGBWMNU_ALINK_COLOR, TWGBWMNU_VLINK_COLOR, TWGBWMNU_BACK_URL, TWGBWMNU_BACK_LINK, 
    TWGBWMNU_BACK_IMAGE, TWGBWMNU_BACK_MENU_IND, TWGBWMNU_MODULE, TWGBWMNU_ENABLED_IND, TWGBWMNU_INSECURE_ALLOWED_IND, 
    TWGBWMNU_ACTIVITY_DATE, TWGBWMNU_CSS_URL, TWGBWMNU_MAP_TITLE, TWGBWMNU_CACHE_OVERRIDE, TWGBWMNU_EXIT_IMAGE, 
    TWGBWMNU_MENU_IMAGE, TWGBWMNU_SOURCE_IND, TWGBWMNU_HELP_CSS, TWGBWMNU_ADM_ACCESS_IND, TWGBWMNU_PRINT_CSS)
 Values
   ('XWSKCMPL.P_DISPLAY_COMPLIANCE', '„ÿ«»ﬁ… «·Œÿ… «·œ—«”Ì…', '„ÿ«»ﬁ… «·Œÿ… «·œ—«”Ì…', '„ÿ«»ﬁ… «·Œÿ… «·œ—«”Ì…', NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    '30', NULL, '40', NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, 'bmenu.P_StuMainMnu', '«·—ÃÊ⁄ ≈·Ï «·ﬁ«∆„…', 
    NULL, 'Y', 'STU', 'Y', 'Y', 
    TO_DATE('10/10/2018 11:22:08', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL, 'S', NULL, 
    NULL, 'L', NULL, 'N', NULL);
COMMIT;
GRANT EXECUTE ON XWSKCMPL TO PUBLIC;
CREATE PUBLIC SYNONYM XWSKCMPL FOR bu_apps.XWSKCMPL;

 

 
