CREATE OR REPLACE FUNCTION F_FACULTY_PWD_VALIDATE(P_USER VARCHAR2 , P_FACULTY_ID VARCHAR2)
RETURN VARCHAR2 
IS
CURSOR CHECK_EXIST IS SELECT '1' FROM GORFBPR
Where
GORFBPR_FGAC_USER_ID =  P_USER 
AND ROWNUM<2 ; 

CURSOR GET_DEPTS IS SELECT 'Y' FROM GORFBPR
Where
GORFBPR_FGAC_USER_ID =  P_USER 
AND REPLACE(GORFBPR_FBPR_CODE,'DEPT_') IN ( SELECT SIRDPCL_DEPT_CODE FROM  sirdpcl WHERE SIRDPCL_PIDM=F_GET_PIDM(P_FACULTY_ID));
L_EXIST CHAR ; 
L_VALIDATE CHAR :='N';
BEGIN
OPEN   CHECK_EXIST ;
FETCH CHECK_EXIST INTO L_EXIST ;
CLOSE CHECK_EXIST ;

IF L_EXIST IS NULL THEN 


RETURN 'Y';
ELSE
OPEN GET_DEPTS ;

FETCH GET_DEPTS INTO L_VALIDATE ;
CLOSE  GET_DEPTS ;
END IF ; 
RETURN L_VALIDATE ;


END;

CREATE OR REPLACE PUBLIC SYNONYM F_FACULTY_PWD_VALIDATE FOR BU_APPS.F_FACULTY_PWD_VALIDATE ;
GRANT EXECUTE ON F_FACULTY_PWD_VALIDATE TO PUBLIC ;



SELECT  F_FACULTY_PWD_VALIDATE('AYALQARNI', '10088')

FROM DUAL ; 