DECLARE 
CURSOR WF_CUR IS SELECT REQUEST_NUMBER ,REQUESTER_PIDM FROM REQUEST_MASTER
WHERE OBJECT_CODE IN ('WF_CLEARANCE','WF_UN_WITHDRAW')
AND REQUEST_STATUS='P';
L_SEX CHAR;
 
BEGIN
FOR REC IN WF_CUR LOOP
UPDATE WF_REQUEST_FLOW SET ACTION_CODE = 'AUTO_APPROVE',ACTIVITY_DATE=SYSDATE,USER_ID=USER
WHERE ROLE_CODE IN ( 'RO_STD_ACTIVITY' ,'RO_STD_BOX','RO_STD_FOOD','RO_STD_SERVICES')
AND ACTION_CODE IS NULL 
AND REQUEST_NUMBER=REC.REQUEST_NUMBER;
SELECT SPBPERS_SEX INTO L_SEX  FROM SPBPERS WHERE SPBPERS_PIDM=REC.REQUESTER_PIDM;
IF L_SEX='F' THEN 
SELECT COUNT(ACTION_CODE) FROM WF_REQUEST_FLOW
WHERE REQUEST_NUMBER=REC.REQUEST_NUMBER
AND ACTION_CODE ='APPROVE'
END LOOP ;

END; 

