/* Formatted on 8/28/2019 8:56:06 AM (QP5 v5.227.12220.39754) */
  SELECT F_GET_STD_NAME (A.SGBSTDN_PIDM),
         F_GET_STD_ID (A.SGBSTDN_PIDM),
         SGBSTDN_COLL_CODE_1,
         f_get_desc_fnc ('STVCOLL', a.SGBSTDN_COLL_CODE_1, 30) COLLEGE,
         SGBSTDN_DEPT_CODE,
         f_get_desc_fnc ('STVDEPT', A.SGBSTDN_DEPT_CODE, 30) DEPRTMENT,
         A.SGBSTDN_PROGRAM_1,
         SMRPRLE_PROGRAM_DESC
    FROM SGBSTDN A, SMRPRLE
   WHERE     A.SGBSTDN_TERM_CODE_EFF =
                (SELECT MAX (SGBSTDN_TERM_CODE_EFF)
                   FROM SGBSTDN
                  WHERE     SGBSTDN_PIDM = A.SGBSTDN_PIDM
                        AND SGBSTDN_TERM_CODE_EFF <= '144010')
         AND A.SGBSTDN_STST_CODE = 'AS'
         AND A.SGBSTDN_LEVL_CODE ='Ìã'
         --AND SGBSTDN_COLL_CODE_1='16'
         --AND SGBSTDN_DEPT_CODE='1601'
         AND SUBSTR (F_GET_STD_ID (A.SGBSTDN_PIDM), 1, 3) = '438'
         AND A.SGBSTDN_PROGRAM_1 NOT LIKE '%1433'
         AND SMRPRLE_PROGRAM = SGBSTDN_PROGRAM_1
ORDER BY A.SGBSTDN_PROGRAM_1

