Insert into GENERAL.GUBOBJS
   (GUBOBJS_NAME, GUBOBJS_DESC, GUBOBJS_OBJT_CODE, GUBOBJS_SYSI_CODE, GUBOBJS_USER_ID, 
    GUBOBJS_ACTIVITY_DATE, GUBOBJS_HELP_IND, GUBOBJS_EXTRACT_ENABLED_IND, GUBOBJS_UI_VERSION)
 Values
   (:OBJECT_CODE, :OBJECT_DESC, 'JOBS', 'S', 'LOCAL', 
   SYSDATE, 'N', 'N', 'B');
Insert into BANSECR.GURUOBJ
   (GURUOBJ_OBJECT, GURUOBJ_ROLE, GURUOBJ_USERID, GURUOBJ_ACTIVITY_DATE, GURUOBJ_USER_ID)
 Values
   (:OBJECT_CODE, 'BAN_DEFAULT_M', 'SAISUSR', SYSDATE, 'BANSECR');
Insert into BANSECR.GURUOBJ
   (GURUOBJ_OBJECT, GURUOBJ_ROLE, GURUOBJ_USERID, GURUOBJ_ACTIVITY_DATE, GURUOBJ_USER_ID)
 Values
   (:OBJECT_CODE, 'BAN_DEFAULT_M', 'BU_APPS', SYSDATE, 'BANSECR');
Insert into BANSECR.GURAOBJ
   (GURAOBJ_OBJECT, GURAOBJ_DEFAULT_ROLE, GURAOBJ_CURRENT_VERSION, GURAOBJ_SYSI_CODE, GURAOBJ_ACTIVITY_DATE, 
    GURAOBJ_USER_ID, GURAOBJ_OWNER, GURAOBJ_ACCESS_TRACKING_IND)
 Values
   (:OBJECT_CODE, 'BAN_DEFAULT_M', '8.6', 'S', sysdate, 
    'BU_DEV', 'PUBLIC', 'Y');   
	Insert into GJBJOBS
   (GJBJOBS_NAME, GJBJOBS_TITLE, GJBJOBS_ACTIVITY_DATE, GJBJOBS_SYSI_CODE, GJBJOBS_JOB_TYPE_IND, 
    GJBJOBS_DESC, GJBJOBS_COMMAND_NAME, GJBJOBS_PRNT_FORM, GJBJOBS_PRNT_CODE, GJBJOBS_LINE_COUNT, 
    GJBJOBS_VALIDATION)
 Values
   (:OBJECT_CODE, :OBJECT_DESC, SYSDATE, 'S', 'R', 
    :OBJECT_DESC, NULL, NULL, NULL, NULL, 
    NULL);
    COMMIT;

