SELECT 
    a.TRNS_SEQ, TRNS_DATE, TRNS_TYPE, 
   TRNS_USER, KEY_1, KEY_2, 
     COL_NAME, OLD_VALUE, 
   NEW_VALUE
FROM AUDT.SSRMEET_AUDT_MASTER a,AUDT.SSRMEET_AUDT_DETAIL b
Where
TRNS_USER = 'MSAWILEH'
and a.TRNS_SEQ=b.TRNS_SEQ
and COL_NAME not in ('SSRMEET_ROOM_CODE','SSRMEET_DATA_ORIGIN','SSRMEET_USER_ID','SSRMEET_ACTIVITY_DATE','SSRMEET_BLDG_CODE','SSRMEET_CATAGORY')
and NEW_VALUE is not null 
 order by KEY_2 ,1;