
  SELECT A.SFRSTCR_TERM_CODE,
         K.STVTERM_DESC,
         A.SFRSTCR_CRN,
         SCBCRSE_TITLE,
         D.SCBCRSE_SUBJ_CODE || D.SCBCRSE_CRSE_NUMB CourseCode,
         F_GET_STD_ID (A.SFRSTCR_PIDM) STUDENT_ID,
         F_GET_STD_NAME (A.SFRSTCR_PIDM) STUDENT_NAME,
         G.STVCOLL_DESC,
         H.STVDEPT_DESC,
         J.SMRPRLE_PROGRAM_DESC,
         REPLACE (B.STVRSTS_DESC, '*') STVRSTS_DESC,
         A.SFRSTCR_CREDIT_HR,
         DECODE (A.SFRSTCR_GRDE_CODE, 'Õ', '‰⁄„', '·«') DENY_STATUS
    FROM SFRSTCR A,
         STVRSTS B,
         SSBSECT C,
         SCBCRSE D,
         SGBSTDN E,
         STVCOLL G,
         STVDEPT H,
         SMRPRLE J,
         STVTERM K
   WHERE     A.SFRSTCR_TERM_CODE LIKE NVL (:P_TERM_CODE, '%')
         AND A.SFRSTCR_PIDM = F_GET_PIDM (:P_STD_ID)
         AND A.SFRSTCR_RSTS_CODE LIKE NVL (:P_RSTS_CODE, '%')
         AND A.SFRSTCR_RSTS_CODE = B.STVRSTS_CODE
         AND A.SFRSTCR_TERM_CODE = C.SSBSECT_TERM_CODE
         AND A.SFRSTCR_CRN = C.SSBSECT_CRN
         AND D.SCBCRSE_SUBJ_CODE = C.SSBSECT_SUBJ_CODE
         AND D.SCBCRSE_CRSE_NUMB = C.SSBSECT_CRSE_NUMB
         AND D.SCBCRSE_EFF_TERM =
                (SELECT MAX (SCBCRSE_EFF_TERM)
                   FROM SCBCRSE
                  WHERE     SCBCRSE_SUBJ_CODE = D.SCBCRSE_SUBJ_CODE
                        AND SCBCRSE_CRSE_NUMB = D.SCBCRSE_CRSE_NUMB
                        AND SCBCRSE_EFF_TERM <= A.SFRSTCR_TERM_CODE)
         AND A.SFRSTCR_PIDM = E.SGBSTDN_PIDM
         AND E.SGBSTDN_TERM_CODE_EFF =
                (SELECT MAX (SGBSTDN_TERM_CODE_EFF)
                   FROM SGBSTDN
                  WHERE     SGBSTDN_PIDM = E.SGBSTDN_PIDM
                        AND SGBSTDN_TERM_CODE_EFF <=
                               F_GET_PARAM ('WORKFLOW', 'CURRENT_TERM', 1))
         AND E.SGBSTDN_COLL_CODE_1 = G.STVCOLL_CODE
         AND E.SGBSTDN_DEPT_CODE = H.STVDEPT_CODE
         AND E.SGBSTDN_PROGRAM_1 = J.SMRPRLE_PROGRAM
         AND A.SFRSTCR_TERM_CODE = K.STVTERM_CODE
ORDER BY SFRSTCR_TERM_CODE, STVRSTS_DESC

-- we need to add from to std id and college code also 