/* Formatted on 5/13/2020 4:53:29 AM (QP5 v5.227.12220.39754) */
SELECT COMP.* ,capp.COURSE_TITLE
  FROM (SELECT SMBPOGN_PIDM PIDM,                                ------PROGRAM
               SMBPOGN_REQUEST_NO REQUEST_NO,
               SMBPOGN_PROGRAM PROGRAM_CODE,
               SMBPOGN_MET_IND PROG_MET_IND,
               SMBPOGN_TERM_CODE_CATLG TERM_CATAG,
               SMBPOGN_TERM_CODE_EFF TERM_CODE_EFF_PROG,
               SMBPOGN_TERM_CODE_EFF_AREA TERM_CODE_EFF_AREA,
               SMBPOGN_REQ_CREDITS_OVERALL PROG_REQ_CREDITS_OVERALL,
               SMBPOGN_REQ_COURSES_OVERALL PROG_REQ_COURSES_OVERALL,
               SMBPOGN_ACT_CREDITS_OVERALL PROG_ACT_CREDITS_OVERALL,
               SMBPOGN_ACT_COURSES_OVERALL PROG_ACT_COURSES_OVERALL,
               ------------------------------AREA
               SMBAOGN_AREA AREA_CODE,
               SMBAOGN_MET_IND AREA_MET_IND,
               SMBAOGN_REQ_CREDITS_OVERALL AREA_REQ_CREDITS_OVERALL,
               SMBAOGN_REQ_COURSES_OVERALL AREA_REQ_COURSES_OVERALL,
               SMBAOGN_ACT_CREDITS_OVERALL AREA_ACT_CREDITS_OVERALL,
               SMBAOGN_ACT_COURSES_OVERALL AREA_ACT_COURSES_OVERALL,
               ------------------ COURSES
               SMRDORQ_CAA_SEQNO CAA_SEQNO,
               SMRDORQ_MET_IND CRSE_MET_IND,
               SMRDORQ_SUBJ_CODE SUBJ_CODE,
               SMRDORQ_CRSE_NUMB_LOW CRSE_NUMB,
               P.SMRDOUS_CRN CRN,
               P.SMRDOUS_TERM_CODE TERM_CODE,
               P.SMRDOUS_GRDE_CODE GRDE_CODE,
               ADJ.SMRDOUS_SUBJ_CODE || ADJ.SMRDOUS_CRSE_NUMB ADJ_SUBJ ,P.SMRDOUS_CREDIT_HOURS ,P.SMRDOUS_CREDIT_HOURS_USED
          FROM SMBPOGN PROG,
               SMBAOGN,
               SMRDORQ,
               SMRDOUS P,
               SMRDOUS ADJ
         WHERE     SMBPOGN_REQUEST_NO =
                      (SELECT MAX (SMBPOGN_REQUEST_NO)
                         FROM SMBPOGN
                        WHERE SMBPOGN_PIDM = PROG.SMBPOGN_PIDM)
               AND SMBAOGN_PIDM = SMBPOGN_PIDM
               AND SMBAOGN_REQUEST_NO = SMBPOGN_REQUEST_NO
               AND SMRDORQ_PIDM = SMBPOGN_PIDM
               AND SMRDORQ_REQUEST_NO = SMBPOGN_REQUEST_NO
               AND SMRDORQ_AREA = SMBAOGN_AREA
               AND SMRDORQ_SUBJ_CODE IS NOT NULL
               AND P.SMRDOUS_PIDM(+) = SMBPOGN_PIDM
               AND P.SMRDOUS_REQUEST_NO(+) = SMBPOGN_REQUEST_NO
               AND P.SMRDOUS_AREA(+) = SMBAOGN_AREA
               AND P.SMRDOUS_CAA_SEQNO(+) = SMRDORQ_CAA_SEQNO
               AND ADJ.SMRDOUS_PIDM(+) = SMBPOGN_PIDM
               AND ADJ.SMRDOUS_REQUEST_NO(+) = SMBPOGN_REQUEST_NO
               AND ADJ.SMRDOUS_AREA(+) = SMBAOGN_AREA
               AND ADJ.SMRDOUS_CAA_SEQNO(+) = SMRDORQ_CAA_SEQNO
               AND ADJ.SMRDOUS_SUBJ_CODE(+) || ADJ.SMRDOUS_CRSE_NUMB(+) <>
                      SMRDORQ_SUBJ_CODE || SMRDORQ_CRSE_NUMB_LOW
        UNION
        SELECT SMBPOGN_PIDM,                                     ------PROGRAM
               SMBPOGN_REQUEST_NO,
               SMBPOGN_PROGRAM,
               SMBPOGN_MET_IND,
               SMBPOGN_TERM_CODE_CATLG,
               SMBPOGN_TERM_CODE_EFF,
               SMBPOGN_TERM_CODE_EFF_AREA,
               SMBPOGN_REQ_CREDITS_OVERALL,
               SMBPOGN_REQ_COURSES_OVERALL,
               SMBPOGN_ACT_CREDITS_OVERALL,
               SMBPOGN_ACT_COURSES_OVERALL,
               ------------------------------AREA
               SMBAOGN_AREA,
               SMBAOGN_MET_IND,
               SMBAOGN_REQ_CREDITS_OVERALL,
               SMBAOGN_REQ_COURSES_OVERALL,
               SMBAOGN_ACT_CREDITS_OVERALL,
               SMBAOGN_ACT_COURSES_OVERALL,
               ------------------ COURSES
               SMRDRRQ_CAA_SEQNO,
               NVL (P.SMRDOUS_EARNED_IND, 'N') MET_IND,
               SMRDRRQ_SUBJ_CODE,
               SMRDRRQ_CRSE_NUMB_LOW,
               P.SMRDOUS_CRN,
               P.SMRDOUS_TERM_CODE,
               P.SMRDOUS_GRDE_CODE,
               ADJ.SMRDOUS_SUBJ_CODE || ADJ.SMRDOUS_CRSE_NUMB ADJ_SUBJ ,P.SMRDOUS_CREDIT_HOURS ,P.SMRDOUS_CREDIT_HOURS_USED
          FROM SMBPOGN PROG,
               SMBAOGN,
               SMRDRRQ,
               SMRDOUS P,
               SMRDOUS ADJ
         WHERE     SMBPOGN_REQUEST_NO =
                      (SELECT MAX (SMBPOGN_REQUEST_NO)
                         FROM SMBPOGN
                        WHERE SMBPOGN_PIDM = PROG.SMBPOGN_PIDM)
               AND SMBAOGN_PIDM = SMBPOGN_PIDM
               AND SMBAOGN_REQUEST_NO = SMBPOGN_REQUEST_NO
               AND SMRDRRQ_PIDM = SMBPOGN_PIDM
               AND SMRDRRQ_REQUEST_NO = SMBPOGN_REQUEST_NO
               AND SMRDRRQ_AREA = SMBAOGN_AREA
               AND P.SMRDOUS_PIDM(+) = SMBPOGN_PIDM
               AND P.SMRDOUS_REQUEST_NO(+) = SMBPOGN_REQUEST_NO
               AND P.SMRDOUS_AREA(+) = SMBAOGN_AREA
               AND P.SMRDOUS_CAA_SEQNO(+) = SMRDRRQ_CAA_SEQNO
               AND P.SMRDOUS_KEY_RULE(+) = SMRDRRQ_KEY_RULE
               AND P.SMRDOUS_RUL_SEQNO(+) = SMRDRRQ_RUL_SEQNO
               AND ADJ.SMRDOUS_PIDM(+) = SMBPOGN_PIDM
               AND ADJ.SMRDOUS_REQUEST_NO(+) = SMBPOGN_REQUEST_NO
               AND ADJ.SMRDOUS_AREA(+) = SMBAOGN_AREA
               AND ADJ.SMRDOUS_CAA_SEQNO(+) = SMRDRRQ_CAA_SEQNO
               AND ADJ.SMRDOUS_KEY_RULE(+) = SMRDRRQ_KEY_RULE
               AND ADJ.SMRDOUS_RUL_SEQNO(+) = SMRDRRQ_RUL_SEQNO
               AND ADJ.SMRDOUS_SUBJ_CODE(+) || ADJ.SMRDOUS_CRSE_NUMB(+) <>
                      SMRDRRQ_SUBJ_CODE || SMRDRRQ_CRSE_NUMB_LOW) COMP ,VW_ACADEMIC_PLANS capp
 WHERE 
 COMP.PROGRAM_CODE(+)=CAPP.PROGRAM_CODE
 AND COMP.TERM_CODE_EFF_PROG(+)=CAPP.EFFECTIVE_TERM
 AND COMP.AREA_CODE(+)=CAPP.AREA_CODE
 AND COMP.SUBJ_CODE(+)||COMP.CRSE_NUMB(+)=CAPP.SUBJECT_CODE||CAPP.COURSE_NUMBER
 AND PIDM = f_get_pidm('430010860')
 And CRSE_MET_IND='Y'
 AND capp.REQUIRED_FLAG='Y'
 