select DISTINCT SFRSTCR_CRN CRN, STVCAMP_DESC ,SCBCRSE_TITLE , 
               SFRSTCR_LEVL_CODE , SPRIDEN_FIRST_NAME||' '||SPRIDEN_LAST_NAME NAM ,SSBSECT_SEQ_NUMB,SPRIDEN_ID
        from SFRSTCR, SSBSECT, STVCAMP, SCBCRSE, SIRASGN,spriden
where SSBSECT_CRN         =   SFRSTCR_CRN       AND
      SSBSECT_CAMP_CODE   like   :P_camp      AND
      SSBSECT_CAMP_CODE = stvcamp_code and
      SSBSECT_SUBJ_CODE   =   SCBCRSE_SUBJ_CODE AND
      SSBSECT_CRSE_NUMB   =   SCBCRSE_CRSE_NUMB AND
      SSBSECT_SSTS_CODE = '?' AND 
       SSBSECT_SCHD_CODE in( '?' ,'?')            and
      SFRSTCR_RSTS_CODE   in  ('RE','RW')       AND 
      SFRSTCR_TERM_CODE   =  SSBSECT_TERM_CODE AND
       SFRSTCR_TERM_CODE = :P_TERM AND
       SPRIDEN_PIDM = SIRASGN_PIDM AND    
       SPRIDEN_CHANGE_IND IS NULL AND
      SIRASGN_CRN      =     SFRSTCR_CRN     AND 
      SIRASGN_TERM_CODE = SFRSTCR_TERM_CODE AND
      SFRSTCR_grde_code       IS NULL           AND
       SPRIDEN_ID LIKE :P_ID AND 
      SSBSECT_GRADABLE_IND = 'Y'                
      ORDER BY SSBSECT_SEQ_NUMB,2,4,3
      