SELECT 
PROGRAM_CODE, EFFECTIVE_TERM, PROGRAM_DESC, 
   REQUIRED_CREDITS_HRS, REQUIRED_COURSES, AREA_PRIORITY, 
   AREA_CODE, AREA_DESC, AREA_REQUIRED_CREDITS_HRS, 
   AREA_COURSES, REQUIRED_FLAG, SUBJECT_CODE, 
   COURSE_NUMBER, COURSE_TITLE, RULE_CODE, 
   RULE_DESC, RULE_REQUIRED_CREDITS_HRS, RULE_REQUIRED_COURSES ,SMRDOUS_GRDE_CODE  ,smrdous_pidm ,SMRDOUS_REQUEST_NO
FROM VW_ACADEMIC_PLANS , smrdous S 
Where
PROGRAM_CODE = '1-3201-1433'
and PROGRAM_CODE= SMRDOUS_PROGRAM
and SMRDOUS_PIDM = f_get_pidm('435000365')
and AREA_CODE=SMRDOUS_AREA
and EFFECTIVE_TERM=SMRDOUS_TERM_CODE_EFF
and SMRDOUS_SUBJ_CODE=SUBJECT_CODE
and SMRDOUS_CRSE_NUMB=COURSE_NUMBER
AND S.SMRDOUS_REQUEST_NO=(SELECT MAX(SMRDOUS_REQUEST_NO) FROM SMRDOUS WHERE SMRDOUS_PIDM=S.SMRDOUS_PIDM)