SELECT 
  F_GET_STD_ID(SFRSTCR_PIDM)STIID, SFRSTCR_TERM_CODE, SFRSTCR_PIDM, SFRSTCR_CRN, 
   SFRSTCR_CLASS_SORT_KEY, SFRSTCR_REG_SEQ, SFRSTCR_PTRM_CODE, 
   SFRSTCR_RSTS_CODE, SFRSTCR_RSTS_DATE, SFRSTCR_ERROR_FLAG, 
   SFRSTCR_MESSAGE, SFRSTCR_BILL_HR, SFRSTCR_WAIV_HR, 
   SFRSTCR_CREDIT_HR, SFRSTCR_BILL_HR_HOLD, SFRSTCR_CREDIT_HR_HOLD, 
   SFRSTCR_GMOD_CODE, SFRSTCR_GRDE_CODE, SFRSTCR_GRDE_CODE_MID, 
   SFRSTCR_GRDE_DATE, SFRSTCR_DUPL_OVER, SFRSTCR_LINK_OVER, 
   SFRSTCR_CORQ_OVER, SFRSTCR_PREQ_OVER, SFRSTCR_TIME_OVER, 
   SFRSTCR_CAPC_OVER, SFRSTCR_LEVL_OVER, SFRSTCR_COLL_OVER, 
   SFRSTCR_MAJR_OVER, SFRSTCR_CLAS_OVER, SFRSTCR_APPR_OVER, 
   SFRSTCR_APPR_RECEIVED_IND, SFRSTCR_ADD_DATE, SFRSTCR_ACTIVITY_DATE, 
   SFRSTCR_LEVL_CODE, SFRSTCR_CAMP_CODE, SFRSTCR_RESERVED_KEY, 
   SFRSTCR_ATTEND_HR, SFRSTCR_REPT_OVER, SFRSTCR_RPTH_OVER, 
   SFRSTCR_TEST_OVER, SFRSTCR_CAMP_OVER, SFRSTCR_USER, 
   SFRSTCR_DEGC_OVER, SFRSTCR_PROG_OVER, SFRSTCR_LAST_ATTEND, 
   SFRSTCR_GCMT_CODE, SFRSTCR_DATA_ORIGIN, SFRSTCR_ASSESS_ACTIVITY_DATE, 
   SFRSTCR_DEPT_OVER, SFRSTCR_ATTS_OVER, SFRSTCR_CHRT_OVER, 
   SFRSTCR_RMSG_CDE, SFRSTCR_WL_PRIORITY, SFRSTCR_WL_PRIORITY_ORIG, 
   SFRSTCR_GRDE_CODE_INCMP_FINAL, SFRSTCR_INCOMPLETE_EXT_DATE, SFRSTCR_MEXC_OVER, 
   SFRSTCR_STSP_KEY_SEQUENCE, SFRSTCR_BRDH_SEQ_NUM, SFRSTCR_BLCK_CODE
FROM SATURN.SFRSTCR
WHERE
sfrstcr_term_code='144510'
 
   AND NVL(SFRSTCR_GRDE_CODE,'D4')='гд' 
  --AND SFRSTCR_PIDM=219807
 AND SFRSTCR_RSTS_CODE in ( 'RW','RE')
 AND NOT EXISTS (SELECT '1' FROM sybstdc WHERE SYBSTDC_TERM_CODE =SFRSTCR_TERM_CODE AND   SYBSTDC_CRN =SFRSTCR_CRN AND  SYBSTDC_PIDM=SFRSTCR_PIDM
AND SYBSTDC_DISCONNECTED='Y' 

 )
 AND SFRSTCR_CREDIT_HR>0
 ORDER BY 2