/* Formatted on 4/29/2020 11:23:17 PM (QP5 v5.227.12220.39754) */
SET DEFINE OFF;

INSERT INTO TWGRWMRL (TWGRWMRL_NAME,
                      TWGRWMRL_ROLE,
                      TWGRWMRL_ACTIVITY_DATE,
                      TWGRWMRL_SOURCE_IND)
     VALUES ('xwlkstcr.p_proc',
             'FACULTY',
             TO_DATE ('12/05/2018 15:38:19', 'MM/DD/YYYY HH24:MI:SS'),
             'L');

INSERT INTO TWGBWMNU (TWGBWMNU_NAME,
                      TWGBWMNU_DESC,
                      TWGBWMNU_PAGE_TITLE,
                      TWGBWMNU_HEADER,
                      TWGBWMNU_HEADER_IMAGE,
                      TWGBWMNU_SUBTITLE_IMAGE,
                      TWGBWMNU_TOP_RIGHT_IMAGE,
                      TWGBWMNU_TOP_LEFT_IMAGE,
                      TWGBWMNU_BULLET_IMAGE,
                      TWGBWMNU_SEP_IMAGE,
                      TWGBWMNU_L_MARGIN_WIDTH,
                      TWGBWMNU_MAIN_TEXT_WIDTH,
                      TWGBWMNU_R_MARGIN_WIDTH,
                      TWGBWMNU_HELP_URL,
                      TWGBWMNU_HELP_LINK,
                      TWGBWMNU_HELP_IMAGE,
                      TWGBWMNU_BGCOLOR,
                      TWGBWMNU_BG_IMAGE,
                      TWGBWMNU_COMMENT,
                      TWGBWMNU_TEXT_COLOR,
                      TWGBWMNU_LINK_COLOR,
                      TWGBWMNU_ALINK_COLOR,
                      TWGBWMNU_VLINK_COLOR,
                      TWGBWMNU_BACK_URL,
                      TWGBWMNU_BACK_LINK,
                      TWGBWMNU_BACK_IMAGE,
                      TWGBWMNU_BACK_MENU_IND,
                      TWGBWMNU_MODULE,
                      TWGBWMNU_ENABLED_IND,
                      TWGBWMNU_INSECURE_ALLOWED_IND,
                      TWGBWMNU_ACTIVITY_DATE,
                      TWGBWMNU_CSS_URL,
                      TWGBWMNU_MAP_TITLE,
                      TWGBWMNU_CACHE_OVERRIDE,
                      TWGBWMNU_EXIT_IMAGE,
                      TWGBWMNU_MENU_IMAGE,
                      TWGBWMNU_SOURCE_IND,
                      TWGBWMNU_HELP_CSS,
                      TWGBWMNU_ADM_ACCESS_IND,
                      TWGBWMNU_PRINT_CSS)
     VALUES ('xwlkstcr.p_proc',
             'ﬂ‘Ê› «· ÊﬁÌ⁄',
             'ﬂ‘Ê› «· ÊﬁÌ⁄',
             'ﬂ‘Ê› «· ÊﬁÌ⁄',
             NULL,
             NULL,
             'TopRightBanner2000',
             'TopLeftBanner2000',
             NULL,
             NULL,
             '30',
             NULL,
             '40',
             NULL,
             NULL,
             NULL,
             NULL,
             NULL,
             NULL,
             NULL,
             NULL,
             NULL,
             NULL,
             'bmenu.P_FacMainMnu',
             '«·—ÃÊ⁄ «·Ï «·ﬁ«∆„…',
             NULL,
             'Y',
             'STU',
             'Y',
             'N',
             TO_DATE ('12/05/2018 15:38:19', 'MM/DD/YYYY HH24:MI:SS'),
             '/css/web_defaultmenu.css',
             NULL,
             'S',
             NULL,
             NULL,
             'L',
             NULL,
             'N',
             NULL);

COMMIT;