Insert into WTAILOR.TWGRWMRL
   (TWGRWMRL_NAME, TWGRWMRL_ROLE, TWGRWMRL_ACTIVITY_DATE, TWGRWMRL_SOURCE_IND)
 Values
   ('xwlkrclc.p_dis_calc', 'WEBUSER', TO_DATE('7/14/2020 1:16:35 PM', 'MM/DD/YYYY HH:MI:SS AM'), 'L');
Insert into WTAILOR.TWGRWMRL
   (TWGRWMRL_NAME, TWGRWMRL_ROLE, TWGRWMRL_ACTIVITY_DATE, TWGRWMRL_SOURCE_IND)
 Values
   ('xwlkrclc.p_prnt_calc', 'WEBUSER', TO_DATE('12/28/2017 1:27:46 PM', 'MM/DD/YYYY HH:MI:SS AM'), 'L');
 
Insert into WTAILOR.TWGBWMNU
   (TWGBWMNU_NAME, TWGBWMNU_DESC, TWGBWMNU_PAGE_TITLE, TWGBWMNU_HEADER, TWGBWMNU_HEADER_IMAGE, 
    TWGBWMNU_SUBTITLE_IMAGE, TWGBWMNU_TOP_RIGHT_IMAGE, TWGBWMNU_TOP_LEFT_IMAGE, TWGBWMNU_BULLET_IMAGE, TWGBWMNU_SEP_IMAGE, 
    TWGBWMNU_L_MARGIN_WIDTH, TWGBWMNU_MAIN_TEXT_WIDTH, TWGBWMNU_R_MARGIN_WIDTH, TWGBWMNU_HELP_URL, TWGBWMNU_HELP_LINK, 
    TWGBWMNU_HELP_IMAGE, TWGBWMNU_BGCOLOR, TWGBWMNU_BG_IMAGE, TWGBWMNU_COMMENT, TWGBWMNU_TEXT_COLOR, 
    TWGBWMNU_LINK_COLOR, TWGBWMNU_ALINK_COLOR, TWGBWMNU_VLINK_COLOR, TWGBWMNU_BACK_URL, TWGBWMNU_BACK_LINK, 
    TWGBWMNU_BACK_IMAGE, TWGBWMNU_BACK_MENU_IND, TWGBWMNU_MODULE, TWGBWMNU_ENABLED_IND, TWGBWMNU_INSECURE_ALLOWED_IND, 
    TWGBWMNU_ACTIVITY_DATE, TWGBWMNU_CSS_URL, TWGBWMNU_MAP_TITLE, TWGBWMNU_CACHE_OVERRIDE, TWGBWMNU_EXIT_IMAGE, 
    TWGBWMNU_MENU_IMAGE, TWGBWMNU_SOURCE_IND, TWGBWMNU_HELP_CSS, TWGBWMNU_ADM_ACCESS_IND, TWGBWMNU_PRINT_CSS)
 Values
   ('xwlkrclc.p_dis_calc', 'Õ«”»… ‰”» «·ﬁ»Ê·', 'Õ«”»… ‰”» «·ﬁ»Ê·', 'Õ«”»… ‰”» «·ﬁ»Ê·', NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    '30', NULL, '40', NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, 'bmenu.P_WorkFlow', '«·—ÃÊ⁄ ≈·Ï «·ﬁ«∆„…', 
    NULL, 'Y', 'STU', 'Y', 'Y', 
    TO_DATE('7/14/2020 1:21:27 PM', 'MM/DD/YYYY HH:MI:SS AM'), NULL, NULL, 'S', NULL, 
    NULL, 'L', NULL, 'N', NULL);
Insert into WTAILOR.TWGBWMNU
   (TWGBWMNU_NAME, TWGBWMNU_DESC, TWGBWMNU_PAGE_TITLE, TWGBWMNU_HEADER, TWGBWMNU_HEADER_IMAGE, 
    TWGBWMNU_SUBTITLE_IMAGE, TWGBWMNU_TOP_RIGHT_IMAGE, TWGBWMNU_TOP_LEFT_IMAGE, TWGBWMNU_BULLET_IMAGE, TWGBWMNU_SEP_IMAGE, 
    TWGBWMNU_L_MARGIN_WIDTH, TWGBWMNU_MAIN_TEXT_WIDTH, TWGBWMNU_R_MARGIN_WIDTH, TWGBWMNU_HELP_URL, TWGBWMNU_HELP_LINK, 
    TWGBWMNU_HELP_IMAGE, TWGBWMNU_BGCOLOR, TWGBWMNU_BG_IMAGE, TWGBWMNU_COMMENT, TWGBWMNU_TEXT_COLOR, 
    TWGBWMNU_LINK_COLOR, TWGBWMNU_ALINK_COLOR, TWGBWMNU_VLINK_COLOR, TWGBWMNU_BACK_URL, TWGBWMNU_BACK_LINK, 
    TWGBWMNU_BACK_IMAGE, TWGBWMNU_BACK_MENU_IND, TWGBWMNU_MODULE, TWGBWMNU_ENABLED_IND, TWGBWMNU_INSECURE_ALLOWED_IND, 
    TWGBWMNU_ACTIVITY_DATE, TWGBWMNU_CSS_URL, TWGBWMNU_MAP_TITLE, TWGBWMNU_CACHE_OVERRIDE, TWGBWMNU_EXIT_IMAGE, 
    TWGBWMNU_MENU_IMAGE, TWGBWMNU_SOURCE_IND, TWGBWMNU_HELP_CSS, TWGBWMNU_ADM_ACCESS_IND, TWGBWMNU_PRINT_CSS)
 Values
   ('xwlkrclc.p_prnt_calc', 'Õ«”»… ‰”» «·ﬁ»Ê·', 'Õ«”»… ‰”» «·ﬁ»Ê·', 'Õ«”»… ‰”» «·ﬁ»Ê·', NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    '30', NULL, '40', NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, 'bmenu.P_WorkFlow', '«·—ÃÊ⁄ ≈·Ï «·ﬁ«∆„…', 
    NULL, 'Y', 'STU', 'Y', 'Y', 
    TO_DATE('7/14/2020 1:21:35 PM', 'MM/DD/YYYY HH:MI:SS AM'), NULL, NULL, 'S', NULL, 
    NULL, 'L', NULL, 'N', NULL);
 GRANT EXECUTE ON xwlkrclc TO PUBLIC;
CREATE PUBLIC SYNONYM xwlkrclc FOR bu_apps.xwlkrclc;

