/* Formatted on 24/03/2021 13:08:28 (QP5 v5.227.12220.39754) */
  SELECT COUNT (*),
         A.SGBSTDN_TERM_CODE_ADMIT,
         A.SGBSTDN_PROGRAM_1,
          
         F_GET_DESC_FNC ('STVCOLL', A.SGBSTDN_COLL_CODE_1, 30) COLLEGE,
         F_GET_DESC_FNC ('STVLEVL', A.SGBSTDN_LEVL_CODE, 30),F_GET_DESC_FNC ('STVDEPT', A.SGBSTDN_DEPT_CODE, 30)
    FROM SGBSTDN A 
   WHERE     A.SGBSTDN_TERM_CODE_EFF = (SELECT MAX (SGBSTDN_TERM_CODE_EFF)
                                          FROM SGBSTDN
                                         WHERE SGBSTDN_PIDM = A.SGBSTDN_PIDM)
         
         --  AND SGBSTDN_STST_CODE = 'AS'
         AND SGBSTDN_LEVL_CODE IN ('蹄', '先')
         AND A.SGBSTDN_TERM_CODE_ADMIT IN ('144210', '144220')
GROUP BY A.SGBSTDN_TERM_CODE_ADMIT,
         A.SGBSTDN_PROGRAM_1,
         A.SGBSTDN_DEPT_CODE ,
         A.SGBSTDN_COLL_CODE_1,
         A.SGBSTDN_LEVL_CODE
ORDER BY A.SGBSTDN_TERM_CODE_ADMIT, A.SGBSTDN_LEVL_CODE;


SELECT COUNT (*)
  FROM SGBSTDN A
 WHERE     A.SGBSTDN_TERM_CODE_ADMIT IN ('144210', '144220')
       AND A.SGBSTDN_TERM_CODE_EFF = (SELECT MAX (SGBSTDN_TERM_CODE_EFF)
                                        FROM SGBSTDN
                                       WHERE SGBSTDN_PIDM = A.SGBSTDN_PIDM)
       AND SGBSTDN_LEVL_CODE IN ('蹄', '先');


  SELECT COUNT (*), SPBPERS_SEX
    FROM SGBSTDN A, SPBPERS
   WHERE     A.SGBSTDN_TERM_CODE_ADMIT IN ('144210', '144220')
         AND A.SGBSTDN_TERM_CODE_EFF = (SELECT MAX (SGBSTDN_TERM_CODE_EFF)
                                          FROM SGBSTDN
                                         WHERE SGBSTDN_PIDM = A.SGBSTDN_PIDM)
         AND SGBSTDN_LEVL_CODE IN ('蹄', '先')
         AND SPBPERS_PIDM = A.SGBSTDN_PIDM
GROUP BY SPBPERS_SEX;

SELECT COUNT (DISTINCT SGBSTDN_COLL_CODE_1)
  FROM SGBSTDN A
 WHERE     A.SGBSTDN_TERM_CODE_ADMIT IN ('144210', '144220')
       AND A.SGBSTDN_TERM_CODE_EFF = (SELECT MAX (SGBSTDN_TERM_CODE_EFF)
                                        FROM SGBSTDN
                                       WHERE SGBSTDN_PIDM = A.SGBSTDN_PIDM)
       AND SGBSTDN_LEVL_CODE IN ('蹄', '先');


SELECT COUNT (DISTINCT SGBSTDN_DEPT_CODE),F_GET_DESC_FNC ('STVDEPT', A.SGBSTDN_DEPT_CODE, 30)
  FROM SGBSTDN A
 WHERE     A.SGBSTDN_TERM_CODE_ADMIT IN ('144210', '144220')
       AND A.SGBSTDN_TERM_CODE_EFF = (SELECT MAX (SGBSTDN_TERM_CODE_EFF)
                                        FROM SGBSTDN
                                       WHERE SGBSTDN_PIDM = A.SGBSTDN_PIDM)
       AND SGBSTDN_LEVL_CODE IN ('蹄', '先')
       GROUP BY F_GET_DESC_FNC ('STVDEPT', A.SGBSTDN_DEPT_CODE, 30);