SELECT 
    TERM_CODE, WAPP_CODE, PROGRAM_CODE, 
   RULE_CODE, ACTIVITY_DATE, USER_ID, 
   CHOICE_ORDER, PROGRAM_LONG_DESC, FEES
FROM BU_APPS.ADM_PROGRAMS_RULES
WHERE
TERM_CODE = '144310'
AND WAPP_CODE = 'UG'
and f_check_rule(290613,RULE_CODE)='Y'
and PROGRAM_CODE like '%55%' ;

 
 
Insert into SATURN.SARETRY
   (SARETRY_AIDM, SARETRY_APPL_SEQNO, SARETRY_SEQNO, SARETRY_LOAD_IND, SARETRY_ACTIVITY_DATE, 
    SARETRY_DEGR_CDE, SARETRY_PRIORITY, SARETRY_ENTRY_DTE, SARETRY_EXIT_DTE, SARETRY_RSON_CDE_SSE, 
    SARETRY_DFMT_CDE, SARETRY_DEGR_DTE, SARETRY_DEGR_DESC, SARETRY_RSON_CDE_DEG, SARETRY_APPL_NO_SARADAP, 
    SARETRY_PRIORITY_NO, SARETRY_CURR_RULE)
 select 290613, 1, :no, 'N', sysdate, 
    NULL, :no, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL,  SOBCURR_CURR_RULE
    from sobcurr
    where SOBCURR_PROGRAM=:prog ;

 
 
Insert into SATURN.SAREFOS
   (SAREFOS_AIDM, SAREFOS_APPL_SEQNO, SAREFOS_ETRY_SEQNO, SAREFOS_SEQNO, SAREFOS_LOAD_IND, 
    SAREFOS_ACTIVITY_DATE, SAREFOS_FLVL_CDE, SAREFOS_IDQL_CDE, SAREFOS_IDEN_CDE, SAREFOS_STDY_DESC, 
    SAREFOS_HNRS_DESC, SAREFOS_LFOS_RULE)
select 290613, 1, :no, 1, 'N', 
    sysdate, 'M', NULL, NULL, NULL, 
    NULL, SORCMJR_CMJR_RULE
    from  SORCMJR 
    where SORCMJR_CURR_RULE=(select SOBCURR_CURR_RULE
    from sobcurr
    where SOBCURR_PROGRAM=:prog) ;
 


