select
F_GET_STD_ID(SGBSTDN_PIDM) ST_ID,SGBSTDN_STST_CODE ,SGBSTDN_PIDM ,SGBSTDN_MAJR_CODE_1,SGBSTDN_COLL_CODE_1,SGBSTDN_DEPT_CODE,SGBSTDN_PROGRAM_1


 from sgbstdn
where

--SGBSTDN_TERM_CODE_EFF='144330'
SGBSTDN_STYP_CODE = 'ã'
and exists (select '1' from request_master where object_code='WF_INTERNAL_VISITOR'
AND REQUESTER_PIDM=SGBSTDN_PIDM
AND REQUEST_STATUS='C'
)
AND sgbstdn_program_1 LIKE '1%38'
and substr(sgbstdn_program_1,3,2)!=SGBSTDN_COLL_CODE_1

AND SGBSTDN_STST_CODE !='ÎÌ'