
INSERT INTO SMRPRLE (SMRPRLE_PROGRAM,
                     SMRPRLE_PROGRAM_DESC,
                     SMRPRLE_ACTIVITY_DATE,
                     SMRPRLE_LEVL_CODE,
                     SMRPRLE_CURR_IND,
                     SMRPRLE_LOCKED_IND,
                     SMRPRLE_CURR_RULE_IND,
                     SMRPRLE_CAMP_CODE,
                     SMRPRLE_COLL_CODE,
                     SMRPRLE_DEGC_CODE,
                     SMRPRLE_PIDM,
                     SMRPRLE_LEVL_CODE_STU,
                     SMRPRLE_WEB_IND)
     VALUES ('1-3507-27',
             '”ﬂ— «—Ì… ÿ»Ì…',
             SYSDATE,
             'œ»',
             'Y',
             'N',
             'Y',
             '27',
             '35',
             'œ»',
             NULL,
             'œ»',
             'Y');

INSERT INTO SMRPRLE (SMRPRLE_PROGRAM,
                     SMRPRLE_PROGRAM_DESC,
                     SMRPRLE_ACTIVITY_DATE,
                     SMRPRLE_LEVL_CODE,
                     SMRPRLE_CURR_IND,
                     SMRPRLE_LOCKED_IND,
                     SMRPRLE_CURR_RULE_IND,
                     SMRPRLE_CAMP_CODE,
                     SMRPRLE_COLL_CODE,
                     SMRPRLE_DEGC_CODE,
                     SMRPRLE_PIDM,
                     SMRPRLE_LEVL_CODE_STU,
                     SMRPRLE_WEB_IND)
     VALUES ('2-3507-28',
             '”ﬂ— «—Ì… ÿ»Ì…',
             SYSDATE,
             'œ»',
             'Y',
             'N',
             'Y',
             '28',
             '35',
             'œ»',
             NULL,
             'œ»',
             'Y');

INSERT INTO SMRPRLE (SMRPRLE_PROGRAM,
                     SMRPRLE_PROGRAM_DESC,
                     SMRPRLE_ACTIVITY_DATE,
                     SMRPRLE_LEVL_CODE,
                     SMRPRLE_CURR_IND,
                     SMRPRLE_LOCKED_IND,
                     SMRPRLE_CURR_RULE_IND,
                     SMRPRLE_CAMP_CODE,
                     SMRPRLE_COLL_CODE,
                     SMRPRLE_DEGC_CODE,
                     SMRPRLE_PIDM,
                     SMRPRLE_LEVL_CODE_STU,
                     SMRPRLE_WEB_IND)
     VALUES ('1-3507-60',
             '”ﬂ— «—Ì… ÿ»Ì…',
             SYSDATE,
             'œ»',
             'Y',
             'N',
             'Y',
             '27',
             '35',
             'œ»',
             NULL,
             'œ»',
             'Y');

INSERT INTO SMRPRLE (SMRPRLE_PROGRAM,
                     SMRPRLE_PROGRAM_DESC,
                     SMRPRLE_ACTIVITY_DATE,
                     SMRPRLE_LEVL_CODE,
                     SMRPRLE_CURR_IND,
                     SMRPRLE_LOCKED_IND,
                     SMRPRLE_CURR_RULE_IND,
                     SMRPRLE_CAMP_CODE,
                     SMRPRLE_COLL_CODE,
                     SMRPRLE_DEGC_CODE,
                     SMRPRLE_PIDM,
                     SMRPRLE_LEVL_CODE_STU,
                     SMRPRLE_WEB_IND)
     VALUES ('2-3507-61',
             '”ﬂ— «—Ì… ÿ»Ì…',
             SYSDATE,
             'œ»',
             'Y',
             'N',
             'Y',
             '61',
             '35',
             'œ»',
             NULL,
             'œ»',
             'Y');

INSERT INTO SMRPRLE (SMRPRLE_PROGRAM,
                     SMRPRLE_PROGRAM_DESC,
                     SMRPRLE_ACTIVITY_DATE,
                     SMRPRLE_LEVL_CODE,
                     SMRPRLE_CURR_IND,
                     SMRPRLE_LOCKED_IND,
                     SMRPRLE_CURR_RULE_IND,
                     SMRPRLE_CAMP_CODE,
                     SMRPRLE_COLL_CODE,
                     SMRPRLE_DEGC_CODE,
                     SMRPRLE_PIDM,
                     SMRPRLE_LEVL_CODE_STU,
                     SMRPRLE_WEB_IND)
     VALUES ('1-3507-62',
             '”ﬂ— «—Ì… ÿ»Ì…',
             SYSDATE,
             'œ»',
             'Y',
             'N',
             'Y',
             '62',
             '35',
             'œ»',
             NULL,
             'œ»',
             'Y');

INSERT INTO SMRPRLE (SMRPRLE_PROGRAM,
                     SMRPRLE_PROGRAM_DESC,
                     SMRPRLE_ACTIVITY_DATE,
                     SMRPRLE_LEVL_CODE,
                     SMRPRLE_CURR_IND,
                     SMRPRLE_LOCKED_IND,
                     SMRPRLE_CURR_RULE_IND,
                     SMRPRLE_CAMP_CODE,
                     SMRPRLE_COLL_CODE,
                     SMRPRLE_DEGC_CODE,
                     SMRPRLE_PIDM,
                     SMRPRLE_LEVL_CODE_STU,
                     SMRPRLE_WEB_IND)
     VALUES ('2-3507-63',
             '”ﬂ— «—Ì… ÿ»Ì…',
             SYSDATE,
             'œ»',
             'Y',
             'N',
             'Y',
             '63',
             '35',
             'œ»',
             NULL,
             'œ»',
             'Y');

INSERT INTO SMRPRLE (SMRPRLE_PROGRAM,
                     SMRPRLE_PROGRAM_DESC,
                     SMRPRLE_ACTIVITY_DATE,
                     SMRPRLE_LEVL_CODE,
                     SMRPRLE_CURR_IND,
                     SMRPRLE_LOCKED_IND,
                     SMRPRLE_CURR_RULE_IND,
                     SMRPRLE_CAMP_CODE,
                     SMRPRLE_COLL_CODE,
                     SMRPRLE_DEGC_CODE,
                     SMRPRLE_PIDM,
                     SMRPRLE_LEVL_CODE_STU,
                     SMRPRLE_WEB_IND)
     VALUES ('1-3507-64',
             '”ﬂ— «—Ì… ÿ»Ì…',
             SYSDATE,
             'œ»',
             'Y',
             'N',
             'Y',
             '64',
             '35',
             'œ»',
             NULL,
             'œ»',
             'Y');

INSERT INTO SMRPRLE (SMRPRLE_PROGRAM,
                     SMRPRLE_PROGRAM_DESC,
                     SMRPRLE_ACTIVITY_DATE,
                     SMRPRLE_LEVL_CODE,
                     SMRPRLE_CURR_IND,
                     SMRPRLE_LOCKED_IND,
                     SMRPRLE_CURR_RULE_IND,
                     SMRPRLE_CAMP_CODE,
                     SMRPRLE_COLL_CODE,
                     SMRPRLE_DEGC_CODE,
                     SMRPRLE_PIDM,
                     SMRPRLE_LEVL_CODE_STU,
                     SMRPRLE_WEB_IND)
     VALUES ('2-3507-65',
             '”ﬂ— «—Ì… ÿ»Ì…',
             SYSDATE,
             'œ»',
             'Y',
             'N',
             'Y',
             '65',
             '35',
             'œ»',
             NULL,
             'œ»',
             'Y');

INSERT INTO SMRPRLE (SMRPRLE_PROGRAM,
                     SMRPRLE_PROGRAM_DESC,
                     SMRPRLE_ACTIVITY_DATE,
                     SMRPRLE_LEVL_CODE,
                     SMRPRLE_CURR_IND,
                     SMRPRLE_LOCKED_IND,
                     SMRPRLE_CURR_RULE_IND,
                     SMRPRLE_CAMP_CODE,
                     SMRPRLE_COLL_CODE,
                     SMRPRLE_DEGC_CODE,
                     SMRPRLE_PIDM,
                     SMRPRLE_LEVL_CODE_STU,
                     SMRPRLE_WEB_IND)
     VALUES ('1-3507-66',
             '”ﬂ— «—Ì… ÿ»Ì…',
             SYSDATE,
             'œ»',
             'Y',
             'N',
             'Y',
             '66',
             '35',
             'œ»',
             NULL,
             'œ»',
             'Y');

INSERT INTO SMRPRLE (SMRPRLE_PROGRAM,
                     SMRPRLE_PROGRAM_DESC,
                     SMRPRLE_ACTIVITY_DATE,
                     SMRPRLE_LEVL_CODE,
                     SMRPRLE_CURR_IND,
                     SMRPRLE_LOCKED_IND,
                     SMRPRLE_CURR_RULE_IND,
                     SMRPRLE_CAMP_CODE,
                     SMRPRLE_COLL_CODE,
                     SMRPRLE_DEGC_CODE,
                     SMRPRLE_PIDM,
                     SMRPRLE_LEVL_CODE_STU,
                     SMRPRLE_WEB_IND)
     VALUES ('2-3507-67',
             '”ﬂ— «—Ì… ÿ»Ì…',
             SYSDATE,
             'œ»',
             'Y',
             'N',
             'Y',
             '67',
             '35',
             'œ»',
             NULL,
             'œ»',
             'Y');
             
             
             -----------------
           INSERT INTO SOBCURR (SOBCURR_CURR_RULE,
                     SOBCURR_TERM_CODE_INIT,
                     SOBCURR_LEVL_CODE,
                     SOBCURR_ACTIVITY_DATE,
                     SOBCURR_PRIM_ROLL_IND,
                     SOBCURR_SECD_ROLL_IND,
                     SOBCURR_LOCK_IND,
                     SOBCURR_CAMP_CODE,
                     SOBCURR_COLL_CODE,
                     SOBCURR_DEGC_CODE,
                     SOBCURR_PROGRAM,
                     SOBCURR_STUDY_PATH_IND)
     SELECT 539 + ROWNUM,
            '000000',
            SMRPRLE_LEVL_CODE,
            SYSDATE,
            'Y',
            'N',
            'Y',
            SMRPRLE_CAMP_CODE,
            SMRPRLE_COLL_CODE,
            'œ»',
            SMRPRLE_PROGRAM,
            'N'
       FROM SMRPRLE
      WHERE     (   SMRPRLE_PROGRAM LIKE '%35%'
                 OR SMRPRLE_PROGRAM LIKE '%HRM%'
                 OR SMRPRLE_PROGRAM LIKE '%IOT%')
            AND SMRPRLE_PROGRAM NOT LIKE '%1437%'
            AND SMRPRLE_PROGRAM NOT LIKE '%1435%'
            AND SMRPRLE_PROGRAM NOT LIKE '%1440%'
   ORDER BY SMRPRLE_PROGRAM;

   ------------------


INSERT INTO SORCMJR (SORCMJR_CURR_RULE,
                     SORCMJR_CMJR_RULE,
                     SORCMJR_TERM_CODE_EFF,
                     SORCMJR_ADM_IND,
                     SORCMJR_STU_IND,
                     SORCMJR_HIS_IND,
                     SORCMJR_REC_IND,
                     SORCMJR_DAU_IND,
                     SORCMJR_ACTIVITY_DATE,
                     SORCMJR_MAJR_CODE,
                     SORCMJR_DEPT_CODE,
                     SORCMJR_DEGR_CDE,
                     SORCMJR_EDI_QLFR,
                     SORCMJR_EDI_VALUE,
                     SORCMJR_DISP_WEB_IND,
                     SORCMJR_DESC,
                     SORCMJR_AUTO_DEC_IND)
   SELECT SOBCURR_CURR_RULE,
          579+ROWNUM,
          '000000',
          'Y',
          'Y',
          'Y',
          'Y',
          'Y',
          SYSDATE,
          'HRMS',
          '3516',
          NULL,
          NULL,
          NULL,
          'Y',
             '«·„Ê«—œ «·»‘—Ì…'
          ||' - '|| DECODE (SOBCURR_CAMP_CODE,
                     '27', '«·⁄ﬁÌﬁ',
                     '28', '«·⁄ﬁÌﬁ',
                     '60', '»·Ã—‘Ì',
                     '61', '»·Ã—‘Ì',
                     '62', '«·„‰œﬁ',
                     '63', '«·„‰œﬁ',
                     '64', '«·„ŒÊ«…',
                     '65', '«·„ŒÊ«…',
                     '66', 'ﬁ·Ê…',
                     '67', 'ﬁ·Ê…')||' - '||DECODE(SUBSTR(SOBCURR_PROGRAM,1,1),'1','ÿ·«»','2','ÿ«·»« ') PROG_DESC,
          'N'
     FROM SOBCURR
    WHERE SOBCURR_PROGRAM LIKE '%HRM%'
    AND SOBCURR_PROGRAM NOT LIKE '%1437%'
AND SOBCURR_PROGRAM NOT LIKE '%1435%'
AND SOBCURR_PROGRAM NOT LIKE '%1440%' 

----------------------
INSERT INTO SORCMJR (SORCMJR_CURR_RULE,
                     SORCMJR_CMJR_RULE,
                     SORCMJR_TERM_CODE_EFF,
                     SORCMJR_ADM_IND,
                     SORCMJR_STU_IND,
                     SORCMJR_HIS_IND,
                     SORCMJR_REC_IND,
                     SORCMJR_DAU_IND,
                     SORCMJR_ACTIVITY_DATE,
                     SORCMJR_MAJR_CODE,
                     SORCMJR_DEPT_CODE,
                     SORCMJR_DEGR_CDE,
                     SORCMJR_EDI_QLFR,
                     SORCMJR_EDI_VALUE,
                     SORCMJR_DISP_WEB_IND,
                     SORCMJR_DESC,
                     SORCMJR_AUTO_DEC_IND)
   SELECT SOBCURR_CURR_RULE,
          589+ROWNUM,
          '000000',
          'Y',
          'Y',
          'Y',
          'Y',
          'Y',
          SYSDATE,
          '3507',
          '3516',
          NULL,
          NULL,
          NULL,
          'Y',
             '”ﬂ— «—Ì… ÿ»Ì…'
          ||' - '|| DECODE (SOBCURR_CAMP_CODE,
                     '27', '«·⁄ﬁÌﬁ',
                     '28', '«·⁄ﬁÌﬁ',
                     '60', '»·Ã—‘Ì',
                     '61', '»·Ã—‘Ì',
                     '62', '«·„‰œﬁ',
                     '63', '«·„‰œﬁ',
                     '64', '«·„ŒÊ«…',
                     '65', '«·„ŒÊ«…',
                     '66', 'ﬁ·Ê…',
                     '67', 'ﬁ·Ê…')||' - '||DECODE(SUBSTR(SOBCURR_PROGRAM,1,1),'1','ÿ·«»','2','ÿ«·»« ') PROG_DESC,
          'N'
     FROM SOBCURR
    WHERE SOBCURR_PROGRAM LIKE '%3507%'
    AND SOBCURR_PROGRAM NOT LIKE '%1437%'
AND SOBCURR_PROGRAM NOT LIKE '%1435%'
AND SOBCURR_PROGRAM NOT LIKE '%1440%'


------------
INSERT INTO SORCMJR (SORCMJR_CURR_RULE,
                     SORCMJR_CMJR_RULE,
                     SORCMJR_TERM_CODE_EFF,
                     SORCMJR_ADM_IND,
                     SORCMJR_STU_IND,
                     SORCMJR_HIS_IND,
                     SORCMJR_REC_IND,
                     SORCMJR_DAU_IND,
                     SORCMJR_ACTIVITY_DATE,
                     SORCMJR_MAJR_CODE,
                     SORCMJR_DEPT_CODE,
                     SORCMJR_DEGR_CDE,
                     SORCMJR_EDI_QLFR,
                     SORCMJR_EDI_VALUE,
                     SORCMJR_DISP_WEB_IND,
                     SORCMJR_DESC,
                     SORCMJR_AUTO_DEC_IND)
   SELECT SOBCURR_CURR_RULE,
          599+ROWNUM,
          '000000',
          'Y',
          'Y',
          'Y',
          'Y',
          'Y',
          SYSDATE,
          '3506',
          '3516',
          NULL,
          NULL,
          NULL,
          'Y',
             ' Õ—Ì— Ê”ﬂ— «—Ì…'
          ||' - '|| DECODE (SOBCURR_CAMP_CODE,
                     '27', '  «·⁄ﬁÌﬁ',
                     '28', '  «·»«Õ…',
                     '60', '»·Ã—‘Ì',
                     '61', '»·Ã—‘Ì',
                     '62', '«·„‰œﬁ',
                     '63', '«·„‰œﬁ',
                     '64', '«·„ŒÊ«…',
                     '65', '«·„ŒÊ«…',
                     '66', 'ﬁ·Ê…',
                     '67', 'ﬁ·Ê…')||' - '||DECODE(SUBSTR(SOBCURR_PROGRAM,1,1),'1','ÿ·«»','2','ÿ«·»« ') PROG_DESC,
          'N'
     FROM SOBCURR
    WHERE SOBCURR_PROGRAM LIKE '%3506%'
    AND SOBCURR_PROGRAM NOT LIKE '%1437%'
AND SOBCURR_PROGRAM NOT LIKE '%1435%'
AND SOBCURR_PROGRAM NOT LIKE '%1440%'

--------------------------
INSERT INTO SORCMJR (SORCMJR_CURR_RULE,
                     SORCMJR_CMJR_RULE,
                     SORCMJR_TERM_CODE_EFF,
                     SORCMJR_ADM_IND,
                     SORCMJR_STU_IND,
                     SORCMJR_HIS_IND,
                     SORCMJR_REC_IND,
                     SORCMJR_DAU_IND,
                     SORCMJR_ACTIVITY_DATE,
                     SORCMJR_MAJR_CODE,
                     SORCMJR_DEPT_CODE,
                     SORCMJR_DEGR_CDE,
                     SORCMJR_EDI_QLFR,
                     SORCMJR_EDI_VALUE,
                     SORCMJR_DISP_WEB_IND,
                     SORCMJR_DESC,
                     SORCMJR_AUTO_DEC_IND)
   SELECT SOBCURR_CURR_RULE,
          599+10+ROWNUM,
          '000000',
          'Y',
          'Y',
          'Y',
          'Y',
          'Y',
          SYSDATE,
          'IOT',
          '3502',
          NULL,
          NULL,
          NULL,
          'Y',
             '≈‰ —‰  «·√‘Ì«¡'
          ||' - '|| DECODE (SOBCURR_CAMP_CODE,
                     '27', '  «·⁄ﬁÌﬁ',
                     '28', '  «·»«Õ…',
                     '60', '»·Ã—‘Ì',
                     '61', '»·Ã—‘Ì',
                     '62', '«·„‰œﬁ',
                     '63', '«·„‰œﬁ',
                     '64', '«·„ŒÊ«…',
                     '65', '«·„ŒÊ«…',
                     '66', 'ﬁ·Ê…',
                     '67', 'ﬁ·Ê…')||' - '||DECODE(SUBSTR(SOBCURR_PROGRAM,1,1),'1','ÿ·«»','2','ÿ«·»« ') PROG_DESC,
          'N'
     FROM SOBCURR
    WHERE SOBCURR_PROGRAM LIKE '%IOT%'
    AND SOBCURR_PROGRAM NOT LIKE '%1437%'
AND SOBCURR_PROGRAM NOT LIKE '%1435%'
AND SOBCURR_PROGRAM NOT LIKE '%1440%'
-----------------------
INSERT INTO SORCMJR (SORCMJR_CURR_RULE,
                     SORCMJR_CMJR_RULE,
                     SORCMJR_TERM_CODE_EFF,
                     SORCMJR_ADM_IND,
                     SORCMJR_STU_IND,
                     SORCMJR_HIS_IND,
                     SORCMJR_REC_IND,
                     SORCMJR_DAU_IND,
                     SORCMJR_ACTIVITY_DATE,
                     SORCMJR_MAJR_CODE,
                     SORCMJR_DEPT_CODE,
                     SORCMJR_DEGR_CDE,
                     SORCMJR_EDI_QLFR,
                     SORCMJR_EDI_VALUE,
                     SORCMJR_DISP_WEB_IND,
                     SORCMJR_DESC,
                     SORCMJR_AUTO_DEC_IND)
   SELECT SOBCURR_CURR_RULE,
          599+20+ROWNUM,
          '000000',
          'Y',
          'Y',
          'Y',
          'Y',
          'Y',
          SYSDATE,
          '3503',
          '3502',
          NULL,
          NULL,
          NULL,
          'Y',
             ' ÿ»Ìﬁ«  «·Õ«”» «·„ﬂ »Ì…'
          ||' - '|| DECODE (SOBCURR_CAMP_CODE,
                     '27', '  «·⁄ﬁÌﬁ',
                     '28', '  «·»«Õ…',
                     '60', '»·Ã—‘Ì',
                     '61', '»·Ã—‘Ì',
                     '62', '«·„‰œﬁ',
                     '63', '«·„‰œﬁ',
                     '64', '«·„ŒÊ«…',
                     '65', '«·„ŒÊ«…',
                     '66', 'ﬁ·Ê…',
                     '67', 'ﬁ·Ê…')||' - '||DECODE(SUBSTR(SOBCURR_PROGRAM,1,1),'1','ÿ·«»','2','ÿ«·»« ') PROG_DESC,
          'N'
     FROM SOBCURR
    WHERE SOBCURR_PROGRAM LIKE '%3503%'
    AND SOBCURR_PROGRAM NOT LIKE '%1437%'
AND SOBCURR_PROGRAM NOT LIKE '%1435%'
AND SOBCURR_PROGRAM NOT LIKE '%1440%'