 select * from 
(
  SELECT DISTINCT SHRDGMR_PIDM  PIDM,f_get_std_id (SHRDGMR_PIDM)       stid,
                  f_get_std_name (SHRDGMR_PIDM)     stname,
                  SHRTTRM_TERM_CODE TERM_CODE,f_get_desc_fnc ('STVASTD', SHRTTRM_ASTD_CODE_END_OF_TERM, 60) ASATD ,
                  SHRTTRM_ASTD_CODE_END_OF_TERM ,ROUND(SHRLGPA_GPA,2) ,SHRLGPA_HOURS_ATTEMPTED
SHRLGPA_HOURS_EARNED ,
SHRLGPA_GPA_HOURS,SHRLGPA_HOURS_PASSED ,
SHRLGPA_QUALITY_POINTS 
 

    FROM shrdgmr, shrttrm, SHRLGPA
   WHERE     SHRDGMR_COLL_CODE_1 = '14'
         AND SHRDGMR_TERM_CODE_GRAD = '143920'
         AND SHRDGMR_DEGS_CODE = 'ÎÌ'
         AND SHRTTRM_PIDM = SHRDGMR_PIDM
         AND SHRLGPA_PIDM = SHRDGMR_PIDM
        AND SHRLGPA_GPA_TYPE_IND='O'
         and SHRTTRM_TERM_CODE='143920'
ORDER BY stid, SHRTTRM_TERM_CODE ASC

)
where  TERM_CODE=(select max(SHRTTRM_TERM_CODE) from SHRTTRM where SHRTTRM_PIDM=pidm and SHRTTRM_TERM_CODE<= '143920')