 INSERT INTO SMRPRLE 
 SELECT :newProgram, SMRPRLE_PROGRAM_DESC, SMRPRLE_ACTIVITY_DATE, 
   SMRPRLE_LEVL_CODE, SMRPRLE_CURR_IND, SMRPRLE_LOCKED_IND, 
   SMRPRLE_CURR_RULE_IND, SMRPRLE_CAMP_CODE, SMRPRLE_COLL_CODE, 
   SMRPRLE_DEGC_CODE, SMRPRLE_PIDM, SMRPRLE_LEVL_CODE_STU, 
   SMRPRLE_WEB_IND FROM SMRPRLE
 WHERE SMRPRLE_PROGRAM = :oldProgram ;
 
 
 -------------
INSERT INTO  smbpgen
 SELECT 
     :newProgram, SMBPGEN_TERM_CODE_EFF, SMBPGEN_ACTIVITY_DATE, 
   SMBPGEN_ACTIVE_IND, SMBPGEN_CAPTIVE_IND, SMBPGEN_CONNECTOR_OVERALL, 
   SMBPGEN_CONNECTOR_INST, SMBPGEN_CONNECTOR_I_TRAD, SMBPGEN_CONNECTOR_I_NONTRAD, 
   SMBPGEN_CONNECTOR_TRANSFER, SMBPGEN_CONNECTOR_LAST_INST, SMBPGEN_CONNECTOR_LAST_EARNED, 
   SMBPGEN_REQ_CREDITS_OVERALL, SMBPGEN_REQ_COURSES_OVERALL, SMBPGEN_REQ_CREDITS_INST, 
   SMBPGEN_REQ_COURSES_INST, SMBPGEN_REQ_CREDITS_I_TRAD, SMBPGEN_REQ_COURSES_I_TRAD, 
   SMBPGEN_MAX_CREDITS_I_NONTRAD, SMBPGEN_MAX_COURSES_I_NONTRAD, SMBPGEN_MAX_CREDITS_TRANSFER, 
   SMBPGEN_MAX_COURSES_TRANSFER, SMBPGEN_LAST_INST_CREDITS, SMBPGEN_LAST_INST_COURSES, 
   SMBPGEN_LAST_EARNED_CREDITS, SMBPGEN_LAST_EARNED_COURSES, SMBPGEN_MIN_GPA, 
   SMBPGEN_GRDE_CODE_MIN, SMBPGEN_MIN_PROGRAM_GPA, SMBPGEN_YEAR_RULE, 
   SMBPGEN_SINGLE_IND
FROM SATURN.SMBPGEN
WHERE
SMBPGEN_PROGRAM = :oldProgram ; 

INSERT INTO smralib
SELECT 
   replace(SMRALIB_AREA,'442','42'), SMRALIB_AREA_DESC, SMRALIB_LEVL_CODE_STU, 
   SMRALIB_LEVL_CODE, SMRALIB_DYNAMIC_IND, SMRALIB_PRINT_IND, 
   SMRALIB_ACTIVITY_DATE, SMRALIB_COMPL_USAGE_IND, SMRALIB_PREREQ_USAGE_IND, 
   SMRALIB_PRESCR_USAGE_IND
FROM SATURN.SMRALIB A 
WHERE EXISTS (SELECT '1' FROM SMRPAAP WHERE SMRPAAP_AREA=A.SMRALIB_AREA AND SMRPAAP_PROGRAM = :oldProgram  )  ;
------------------
 INSERT INTO SMRPAAP
 SELECT 
     :newProgram, SMRPAAP_TERM_CODE_EFF, SMRPAAP_ACTIVITY_DATE, 
   SMRPAAP_CRSE_REUSE_IND, SMRPAAP_ATTR_REUSE_IND,  replace(SMRPAAP_AREA,'442','42'), 
   SMRPAAP_YEAR_RULE, SMRPAAP_AREA_PRIORITY, SMRPAAP_WITHIN_IND
FROM SATURN.SMRPAAP
WHERE
SMRPAAP_PROGRAM = :oldProgram ;
----quering areas 
 
-------------------------areas 

  insert into smbagen
SELECT 
    replace(SMBAGEN_AREA,'442','42'), SMBAGEN_TERM_CODE_EFF, SMBAGEN_ACTIVITY_DATE, 
   SMBAGEN_ACTIVE_IND, SMBAGEN_CRSE_REUSE_IND, SMBAGEN_ATTR_REUSE_IND, 
   SMBAGEN_CONNECTOR_OVERALL, SMBAGEN_CONNECTOR_INST, SMBAGEN_CONNECTOR_I_TRAD, 
   SMBAGEN_CONNECTOR_I_NONTRAD, SMBAGEN_CONNECTOR_TRANSFER, SMBAGEN_WITHIN_IND, 
   SMBAGEN_GC_IND, SMBAGEN_AREA_PRIORITY, SMBAGEN_YEAR_RULE, 
   SMBAGEN_MIN_AREA_GPA, SMBAGEN_GRDE_CODE_MIN, SMBAGEN_COMPL_CREDITS, 
   SMBAGEN_COMPL_COURSES, SMBAGEN_REQ_CREDITS_OVERALL, SMBAGEN_REQ_COURSES_OVERALL, 
   SMBAGEN_REQ_CREDITS_INST, SMBAGEN_REQ_COURSES_INST, SMBAGEN_REQ_CREDITS_I_TRAD, 
   SMBAGEN_REQ_COURSES_I_TRAD, SMBAGEN_MAX_CREDITS_I_NONTRAD, SMBAGEN_MAX_COURSES_I_NONTRAD, 
   SMBAGEN_MAX_CREDITS_TRANSFER, SMBAGEN_MAX_COURSES_TRANSFER
FROM SATURN.SMBAGEN A
 
WHERE EXISTS (SELECT '1' FROM SMRPAAP WHERE SMRPAAP_AREA=A.SMBAGEN_AREA AND SMRPAAP_PROGRAM = :oldProgram  ) ;

   insert into smracaa
   
   SELECT 
     replace(SMRACAA_AREA,'442','42'), SMRACAA_TERM_CODE_EFF, SMRACAA_ACTIVITY_DATE, 
   SMRACAA_TRANSFER_IND, SMRACAA_SEQNO, SMRACAA_SPLIT_COURSE_IND, 
   SMRACAA_CONNECTOR_REQ, SMRACAA_CONNECTOR_MAX, SMRACAA_CONNECTOR_TRANSFER, 
   SMRACAA_CNT_IN_GPA_IND, SMRACAA_SET, SMRACAA_SUBSET, 
   SMRACAA_RULE, SMRACAA_SUBJ_CODE, SMRACAA_CRSE_NUMB_LOW, 
   SMRACAA_CRSE_NUMB_HIGH, SMRACAA_ATTR_CODE, SMRACAA_ATTS_CODE, 
   SMRACAA_CAMP_CODE, SMRACAA_COLL_CODE, SMRACAA_DEPT_CODE, 
   SMRACAA_YEAR_RULE, SMRACAA_TERM_CODE_FROM, SMRACAA_TERM_CODE_TO, 
   SMRACAA_REQ_CREDITS, SMRACAA_REQ_COURSES, SMRACAA_MAX_CREDITS, 
   SMRACAA_MAX_COURSES, SMRACAA_MIN_CRED_CRSE, SMRACAA_MAX_CRED_CRSE, 
   SMRACAA_COMPL_CREDITS, SMRACAA_COMPL_COURSES, SMRACAA_GRDE_CODE_MIN, 
   SMRACAA_MAX_CREDITS_TRANSFER, SMRACAA_MAX_COURSES_TRANSFER, SMRACAA_END_FUNCTION, 
   SMRACAA_CATALOG_IND, SMRACAA_TESC_CODE, SMRACAA_MIN_VALUE, 
   SMRACAA_MAX_VALUE, SMRACAA_CONCURRENCY_IND
FROM SATURN.SMRACAA A
 
WHERE EXISTS (SELECT '1' FROM SMRPAAP WHERE SMRPAAP_AREA=A.SMRACAA_AREA AND SMRPAAP_PROGRAM = :oldProgram  ) ;

INSERT INTO smbarul
SELECT 
    SMBARUL_KEY_RULE, SMBARUL_DESC, replace(SMBARUL_AREA,'442','42'), 
   SMBARUL_TERM_CODE_EFF, SMBARUL_CONNECTOR_COND, SMBARUL_CONNECTOR_MAX_COND, 
   SMBARUL_CONNECTOR_REQ, SMBARUL_CONNECTOR_MAX, SMBARUL_ACTIVITY_DATE, 
   SMBARUL_REQ_CRED_COND, SMBARUL_REQ_COURSES_COND, SMBARUL_MAX_CRED_COND, 
   SMBARUL_MAX_COURSES_COND, SMBARUL_REQ_NUMB_COND, SMBARUL_REQ_CREDITS, 
   SMBARUL_REQ_COURSES, SMBARUL_MAX_CREDITS, SMBARUL_MAX_COURSES
FROM SATURN.SMBARUL A 

WHERE EXISTS (SELECT '1' FROM SMRPAAP WHERE SMRPAAP_AREA=A.SMBARUL_AREA AND SMRPAAP_PROGRAM = :oldProgram  ) ;

UPDATE SOBCURR SET SOBCURR_PROGRAM=:newProgram
where SOBCURR_PROGRAM=:oldProgram;


delete smbarul 

delete  smrpaap WHERE
SMRPAAP_PROGRAM = :oldProgram ; 
delete
smbpgen
WHERE
SMBPGEN_PROGRAM = :oldProgram ; 

delete smrprle 
 WHERE SMRPRLE_PROGRAM = :oldProgram  ;



