SELECT 
   ROWID, REQUEST_NO, SEQUENCE_NO, ITEM_CODE, 
   ITEM_VALUE, ACTIVITY_DATE, USER_ID, 
   ATTRIBUTE_CODE
FROM BU_APPS.REQUEST_DETAILS A
WHERE
ITEM_CODE = 'COLLEGE'
AND ITEM_VALUE = '00'
AND EXISTS (SELECT '1' FROM REQUEST_MASTER WHERE REQUEST_NO=A.REQUEST_NO AND OBJECT_CODE LIKE '%GRAD%' AND REQUEST_STATUS='P'
AND OBJECT_CODE !='WF_GRADE_APPROVAL') ;


F_GET_PATH_TYPE