/* Formatted on 6/24/2020 9:57:03 AM (QP5 v5.360) */
SELECT M.REQUEST_NO,
       f_get_std_id (REQUESTER_PIDM)                       std_id,
       f_get_std_name (REQUESTER_PIDM)                     std_name,
       F_GET_DESC_FNC ('STVCOLL', COLL.ITEM_VALUE, 30)     COLLEGE,
       F_GET_DESC_FNC ('STVDEPT', DEPT.ITEM_VALUE, 30)     DEPARTMENT,
       F_GET_DESC_FNC ('STVSBGI', UNI.ITEM_VALUE, 30)      UNIVERSITY ,
       NVL((SELECT 'угЬс'
          FROM SFRSTCR
         WHERE     SFRSTCR_TERM_CODE = TERM.ITEM_VALUE
               AND SFRSTCR_PIDM = M.REQUESTER_PIDM
               AND SFRSTCR_RSTS_CODE IN ('RE', 'RW')
               AND ROWNUM < 2) ,'лэб угЬс')REGISTERD
  FROM BU_APPS.REQUEST_MASTER  M,
       REQUEST_DETAILS         COLL,
       REQUEST_DETAILS         DEPT,
       REQUEST_DETAILS         UNI,
       REQUEST_DETAILS         TERM
 WHERE     OBJECT_CODE = 'WF_EXTERNAL_VISITOR'
       AND REQUEST_STATUS = 'C'
       AND M.REQUEST_NO = COLL.REQUEST_NO
       AND COLL.SEQUENCE_NO = 1
       AND COLL.ITEM_CODE = 'COLLEGE'
       AND M.REQUEST_NO = DEPT.REQUEST_NO
       AND DEPT.SEQUENCE_NO = 1
       AND DEPT.ITEM_CODE = 'DEPARTMENT'
       AND M.REQUEST_NO = UNI.REQUEST_NO
       AND UNI.SEQUENCE_NO = 1
       AND UNI.ITEM_CODE = 'UNIVERSITY'
       AND M.REQUEST_NO = TERM.REQUEST_NO
       AND TERM.SEQUENCE_NO = 1
       AND TERM.ITEM_CODE = 'TERM'
       AND TERM.ITEM_VALUE = '144030'
      ORDER BY 6,7