SELECT TO_CHAR(MIN(REQUEST_DATE),'YYYY') ISSUE_YEAR,OBJECT_DESC ,DECODE(OBJECT_TYPE,'W','„⁄«„·… ≈·ﬂ —Ê‰Ì…',' ﬁ—Ì— ≈·ﬂ —Ê‰Ì') OBJECTTYPE FROM REQUEST_MASTER M,OBJECT_DEFINITION O
WHERE M.OBJECT_CODE=O.OBJECT_CODE
GROUP BY OBJECT_DESC,OBJECT_TYPE
ORDER BY 1

 
