UPDATE   SFRSTCR SET SFRSTCR_RSTS_CODE='DD'
WHERE SFRSTCR_TERM_CODE='144010'
AND SFRSTCR_RSTS_CODE IN ('RE','RW')
AND EXISTS (

SELECT 'C' FROM SGBSTDN  A
WHERE A.SGBSTDN_TERM_CODE_EFF =(SELECT MAX(SGBSTDN_TERM_CODE_EFF) FROM SGBSTDN
WHERE SGBSTDN_PIDM=A.SGBSTDN_PIDM
and SGBSTDN_TERM_CODE_EFF<='144010'
 )
 AND A.SGBSTDN_PIDM=SFRSTCR_PIDM
AND SGBSTDN_STST_CODE IN ('ãÓ' ,'ØÓ','ãÎ')
AND A.SGBSTDN_STYP_CODE ='ã'
 
--AND SUBSTR(F_GET_STD_ID(A.SGBSTDN_PIDM),1,3)='441'

 )  ;