
SELECT * FROM RWTPAYR
WHERE
RWTPAYR_TRAN_NUMBER='924'

;

 SELECT * from  TBRACCD trns
where exists 
(select 1 from 

SATURN.RWTPAYR crnt
where RWTPAYR_TRAN_NUMBER=924
and RWTPAYR_pidm=TBRACCD_pidm
 )

and TBRACCD_TERM_CODE='144510'
and TBRACCD_DETAIL_CODE in ('уп.к','уп.Ч')
and to_char(TBRACCD_EFFECTIVE_DATE,'mm/dd/yyyy')='10/10/2023'
and TBRACCD_DESC like '%10/2023%'
/*and TBRACCD_TRAN_NUMBER=(select max(TBRACCD_TRAN_NUMBER) from TBRACCD where TBRACCD_pidm=trns.TBRACCD_pidm 
and  TBRACCD_TERM_CODE=trns.TBRACCD_TERM_CODE
and TBRACCD_DETAIL_CODE=trns.TBRACCD_DETAIL_CODE
and TBRACCD_AMOUNT=trns.TBRACCD_AMOUNT
)*/
;

--- DIFFERENCES 

SELECT  RWTPAYR_pidm FROM RWTPAYR
WHERE
RWTPAYR_TRAN_NUMBER='924'

MINUS

 SELECT TBRACCD_pidm from  TBRACCD trns
where exists 
(select 1 from 

SATURN.RWTPAYR crnt
where RWTPAYR_TRAN_NUMBER=924
and RWTPAYR_pidm=TBRACCD_pidm
 )

and TBRACCD_TERM_CODE='144510'
and TBRACCD_DETAIL_CODE in ('уп.к','уп.Ч')
and to_char(TBRACCD_EFFECTIVE_DATE,'mm/dd/yyyy')='10/10/2023'
and TBRACCD_DESC like '%10/2023%'
/*and TBRACCD_TRAN_NUMBER=(select max(TBRACCD_TRAN_NUMBER) from TBRACCD where TBRACCD_pidm=trns.TBRACCD_pidm 
and  TBRACCD_TERM_CODE=trns.TBRACCD_TERM_CODE
and TBRACCD_DETAIL_CODE=trns.TBRACCD_DETAIL_CODE
and TBRACCD_AMOUNT=trns.TBRACCD_AMOUNT
)*/
;




------ DELETING 

delete  from  TBRACCD trns
where exists 
(select 1 from 

SATURN.RWTPAYR crnt
where RWTPAYR_TRAN_NUMBER=924
and RWTPAYR_pidm=TBRACCD_pidm
 )

and TBRACCD_TERM_CODE='144510'
and TBRACCD_DETAIL_CODE in ('уп.к','уп.Ч')
and to_char(TBRACCD_EFFECTIVE_DATE,'mm/dd/yyyy')='10/10/2023'
and TBRACCD_DESC like '%10/2023%'
and TBRACCD_TRAN_NUMBER=(select max(TBRACCD_TRAN_NUMBER) from TBRACCD where TBRACCD_pidm=trns.TBRACCD_pidm 
and  TBRACCD_TERM_CODE=trns.TBRACCD_TERM_CODE
and TBRACCD_DETAIL_CODE=trns.TBRACCD_DETAIL_CODE
and TBRACCD_AMOUNT=trns.TBRACCD_AMOUNT


)
 ;
 
 
 DELETE    FROM RWTPAYR
WHERE
RWTPAYR_TRAN_NUMBER='924' ;







