/* Formatted on 10/8/2020 10:41:00 PM (QP5 v5.360) */
SELECT COUNT (distinct SUBJECT_CODE || COURSE_NUMBER), '143310' ,REQUIRED_COURSES
  FROM VW_ACADEMIC_PLANS
 WHERE PROGRAM_CODE = :prog AND EFFECTIVE_TERM = '143310'
 group by PROGRAM_CODE ,REQUIRED_COURSES
UNION
SELECT COUNT (distinct SUBJECT_CODE || COURSE_NUMBER), '143810' ,REQUIRED_COURSES
  FROM VW_ACADEMIC_PLANS
 WHERE PROGRAM_CODE = :prog AND EFFECTIVE_TERM = '143810'
  group by PROGRAM_CODE ,REQUIRED_COURSES
ORDER BY 2