SELECT STVDEPT_CODE,STVDEPT_DESC 
FROM STVDEPT 
WHERE EXISTS
( SELECT 'X' FROM GORFBPR
WHERE GORFBPR_FGAC_USER_ID=upper(:USER1)
  AND ( REPLACE(GORFBPR_FBPR_CODE,'DEPT_') =STVDEPT_CODE ) )
  AND SUBSTR(STVDEPT_CODE,1,2)= :COLL_CODE 
  UNION
 SELECT STVDEPT_CODE,STVDEPT_DESC 
FROM STVDEPT 
WHERE NOT EXISTS
( SELECT 'X' FROM GORFBPR
WHERE GORFBPR_FGAC_USER_ID=upper(:USER1)
  ) AND SUBSTR(STVDEPT_CODE,1,2)= :COLL_CODE  ;
  
  
   ;



SELECT STVDEPT_CODE,STVDEPT_DESC 
FROM STVDEPT 
WHERE EXISTS
( SELECT 'X' FROM GORFBPR
WHERE GORFBPR_FGAC_USER_ID=upper(:U1SER)
  AND ( REPLACE(GORFBPR_FBPR_CODE,'DEPT_') =STVDEPT_CODE ) )
  AND SUBSTR(STVDEPT_CODE,1,2)= :TXT_COLL_CODE 
  UNION
 SELECT STVDEPT_CODE,STVDEPT_DESC 
FROM STVDEPT 
WHERE NOT EXISTS
( SELECT 'X' FROM GORFBPR
WHERE GORFBPR_FGAC_USER_ID=upper(:U1SER)
  ) AND SUBSTR(STVDEPT_CODE,1,2)= :TXT_COLL_CODE ;
  
  
  
  xwskxtrn.dispLogin