SELECT 
   COLL_CODE ,F_GET_DESC_FNC('STVCOLL',COLL_CODE,30) , MAJR_CODE, F_GET_DESC_FNC('STVMAJR',MAJR_CODE,30) , 
    SSNID, 
   STUDENT_NAME, MOBILE1, MOBILE2, 
   SEX, BDATE, EMAIL, 
   MYUNI, MYCOLL, MYPROG, 
   CGPA, EARNED_HRS, decode(REQUEST_STATUS,'A','„Ê«›ﬁ…','P','„⁄·ﬁ','„—›Ê÷') status
FROM BU_APPS.XTRNL_TRANSFER_DETAILS
WHERE
TERM_CODE = '144340'
ORDER BY 1 , 3