SELECT STUDENT_SSN,
       STUDENT_PIDM,
       ADMISSION_TYPE,
       APPLICATION_COMPLETE_IND,
       APPLICATION_PUSH_IND,
       FIRST_NAME_AR,
       MIDDLE_NAME_AR,
       LAST_NAME_AR,
       FIRST_NAME_EN,
       MIDDLE_NAME_EN,
       LAST_NAME_EN,
       GENDER
  FROM BU_APPS.STU_MAIN_DATA_VW
 WHERE STUDENT_SSN = '1116262229'
 
 and exists (select '1' from VW_APPLICANT_CHOICES where APPLICANT_PIDM=STUDENT_PIDM and APPLICANT_DECISION in ('WA','CA'));

DELETE  FROM  SARAPPD WHERE sarappd_pidm= :l_pidm AND SARAPPD_APDC_CODE in ( 'CM' ,'CA' ,'WM' ,'WA' ,'CU') ;

  INSERT INTO adm_student_confirmation(ADMIT_TERM, APPLICANT_PIDM, ACTIVITY_DATE, USER_ID)
VALUES ('144310',:l_PIDM,SYSDATE,USER);