SELECT 
    ROLE_CODE, USER_PIDM, ACTIVITY_DATE, 
   USERID, ACTIVE, USER_MAIL, 
   SEND_EMAIL_FLAG
FROM BU_APPS.ROLE_USERS A 
WHERE
ROLE_CODE ='RO_DEPT_MANAGER'
AND NOT EXISTS (SELECT '1'   
 
FROM BU_APPS.USERS_ATTRIBUTES
WHERE
ATTRIBUTE_CODE = 'TRN_ALLOW_APPROVALS'
AND USER_PIDM=A.USER_PIDM
) ;

Insert into BU_APPS.USERS_ATTRIBUTES
   (USER_PIDM, ATTRIBUTE_CODE, ATTRIBUTE_VALUE, ACTIVITY_DATE, USER_ID)
SELECT DISTINCT A.USER_PIDM, 'TRN_ALLOW_APPROVALS', 'N', TO_DATE('6/4/2020 10:39:40 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'SAISUSR' 
 FROM BU_APPS.ROLE_USERS A 
WHERE
ROLE_CODE ='RO_DEPT_MANAGER'
AND NOT EXISTS (SELECT '1'   
 
FROM BU_APPS.USERS_ATTRIBUTES
WHERE
ATTRIBUTE_CODE = 'TRN_ALLOW_APPROVALS'
AND USER_PIDM=A.USER_PIDM
) ;

SELECT * FROM BU_APPS.USERS_ATTRIBUTES T
WHERE T.ATTRIBUTE_CODE='TRN_ALLOW_APPROVALS'
AND EXISTS (SELECT '1' FROM BU_APPS.ROLE_USERS
WHERE ROLE_CODE ='RO_DEPT_MANAGER'
AND USER_PIDM=T.USER_PIDM )
;
UPDATE  BU_APPS.USERS_ATTRIBUTES T  SET T.ATTRIBUTE_VALUE='Y'
WHERE T.ATTRIBUTE_CODE='TRN_ALLOW_APPROVALS'
AND EXISTS (SELECT '1' FROM BU_APPS.ROLE_USERS
WHERE ROLE_CODE ='RO_DEPT_MANAGER'
AND USER_PIDM=T.USER_PIDM )
AND T.ATTRIBUTE_VALUE='N'
;


------------------------------------------------
/* Formatted on 8/13/2020 4:08:40 PM (QP5 v5.360) */
UPDATE dev_sys_parameters
   SET PARAMETER_value = 'Y'
 WHERE PARAMETER_CODE = 'ALLOW_TRANSFER_APPROVAL';

UPDATE BU_APPS.USERS_ATTRIBUTES T
   SET T.ATTRIBUTE_VALUE = 'Y'
 WHERE     T.ATTRIBUTE_CODE = 'TRN_ALLOW_APPROVALS'
       AND EXISTS
               (SELECT '1'
                  FROM BU_APPS.ROLE_USERS
                 WHERE     ROLE_CODE = 'RO_DEPT_MANAGER'
                       AND USER_PIDM = T.USER_PIDM)
       AND T.ATTRIBUTE_VALUE = 'N';

UPDATE BU_APPS.USERS_ATTRIBUTES T
   SET T.ATTRIBUTE_VALUE = 'Y'
 WHERE     T.ATTRIBUTE_CODE = 'TRN_ALLOW_APPROVALS'
       AND EXISTS
               (SELECT '1'
                  FROM BU_APPS.ROLE_USERS
                 WHERE     ROLE_CODE = 'RO_COLLEGE_DEAN'
                       AND USER_PIDM = T.USER_PIDM)
       AND T.ATTRIBUTE_VALUE = 'N'