SET DEFINE OFF;
Insert into GURAUOB
   (GURAUOB_AUDIT_TIME, GURAUOB_AUDIT_ACTION, GURAUOB_OBJECT, GURAUOB_ROLE, GURAUOB_USERID, 
    GURAUOB_ACTIVITY_DATE, GURAUOB_USER_ID, GURAUOB_COMMENTS, GURAUOB_DATA_ORIGIN)
 Values
   (TO_TIMESTAMP('3/23/2014 7:55:57.440147 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'U', 'SSASECT', 'BAN_DEFAULT_M', 'BAN_STUDENT_C', 
    TO_DATE('09/16/1995 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'BANSECR_CONVERSION', NULL, NULL);
Insert into GURAUOB
   (GURAUOB_AUDIT_TIME, GURAUOB_AUDIT_ACTION, GURAUOB_OBJECT, GURAUOB_ROLE, GURAUOB_USERID, 
    GURAUOB_ACTIVITY_DATE, GURAUOB_USER_ID, GURAUOB_COMMENTS, GURAUOB_DATA_ORIGIN)
 Values
   (TO_TIMESTAMP('3/23/2014 7:55:57.780185 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'U', 'SSASECT', 'BAN_DEFAULT_Q', 'BAHA_N_FAC_LOAD_C', 
    TO_DATE('01/28/2012 12:20:38', 'MM/DD/YYYY HH24:MI:SS'), 'BANSECR_CONVERSION', NULL, NULL);
Insert into GURAUOB
   (GURAUOB_AUDIT_TIME, GURAUOB_AUDIT_ACTION, GURAUOB_OBJECT, GURAUOB_ROLE, GURAUOB_USERID, 
    GURAUOB_ACTIVITY_DATE, GURAUOB_USER_ID, GURAUOB_COMMENTS, GURAUOB_DATA_ORIGIN)
 Values
   (TO_TIMESTAMP('3/23/2014 7:55:57.890066 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'U', 'SSASECT', 'BAN_DEFAULT_Q', 'FRAFEE', 
    TO_DATE('02/03/2014 11:34:46', 'MM/DD/YYYY HH24:MI:SS'), 'BANSECR_CONVERSION', NULL, NULL);
Insert into GURAUOB
   (GURAUOB_AUDIT_TIME, GURAUOB_AUDIT_ACTION, GURAUOB_OBJECT, GURAUOB_ROLE, GURAUOB_USERID, 
    GURAUOB_ACTIVITY_DATE, GURAUOB_USER_ID, GURAUOB_COMMENTS, GURAUOB_DATA_ORIGIN)
 Values
   (TO_TIMESTAMP('3/23/2014 7:55:57.891079 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'U', 'SSASECT', 'BAN_DEFAULT_Q', 'MOMARY', 
    TO_DATE('02/10/2014 13:55:42', 'MM/DD/YYYY HH24:MI:SS'), 'BANSECR_CONVERSION', NULL, NULL);
Insert into GURAUOB
   (GURAUOB_AUDIT_TIME, GURAUOB_AUDIT_ACTION, GURAUOB_OBJECT, GURAUOB_ROLE, GURAUOB_USERID, 
    GURAUOB_ACTIVITY_DATE, GURAUOB_USER_ID, GURAUOB_COMMENTS, GURAUOB_DATA_ORIGIN)
 Values
   (TO_TIMESTAMP('3/23/2014 7:55:57.894098 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'U', 'SSASECT', 'BAN_DEFAULT_M', 'KMALZAHRANI', 
    TO_DATE('01/30/2014 11:39:44', 'MM/DD/YYYY HH24:MI:SS'), 'BANSECR_CONVERSION', NULL, NULL);
Insert into GURAUOB
   (GURAUOB_AUDIT_TIME, GURAUOB_AUDIT_ACTION, GURAUOB_OBJECT, GURAUOB_ROLE, GURAUOB_USERID, 
    GURAUOB_ACTIVITY_DATE, GURAUOB_USER_ID, GURAUOB_COMMENTS, GURAUOB_DATA_ORIGIN)
 Values
   (TO_TIMESTAMP('3/23/2014 7:55:57.819524 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'U', 'SSASECT', 'BAN_DEFAULT_M', 'USER_SECTIONS', 
    TO_DATE('01/27/2009 11:04:16', 'MM/DD/YYYY HH24:MI:SS'), 'BANSECR_CONVERSION', NULL, NULL);
Insert into GURAUOB
   (GURAUOB_AUDIT_TIME, GURAUOB_AUDIT_ACTION, GURAUOB_OBJECT, GURAUOB_ROLE, GURAUOB_USERID, 
    GURAUOB_ACTIVITY_DATE, GURAUOB_USER_ID, GURAUOB_COMMENTS, GURAUOB_DATA_ORIGIN)
 Values
   (TO_TIMESTAMP('3/23/2014 7:55:57.830621 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'U', 'SSASECT', 'BAN_DEFAULT_M', 'BAHA_N_SECT1_C', 
    TO_DATE('04/23/2012 09:05:19', 'MM/DD/YYYY HH24:MI:SS'), 'BANSECR_CONVERSION', NULL, NULL);
Insert into GURAUOB
   (GURAUOB_AUDIT_TIME, GURAUOB_AUDIT_ACTION, GURAUOB_OBJECT, GURAUOB_ROLE, GURAUOB_USERID, 
    GURAUOB_ACTIVITY_DATE, GURAUOB_USER_ID, GURAUOB_COMMENTS, GURAUOB_DATA_ORIGIN)
 Values
   (TO_TIMESTAMP('3/23/2014 7:55:57.853827 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'U', 'SSASECT', 'BAN_DEFAULT_Q', 'HMADKOR', 
    TO_DATE('11/12/2013 11:51:35', 'MM/DD/YYYY HH24:MI:SS'), 'BANSECR_CONVERSION', NULL, NULL);
Insert into GURAUOB
   (GURAUOB_AUDIT_TIME, GURAUOB_AUDIT_ACTION, GURAUOB_OBJECT, GURAUOB_ROLE, GURAUOB_USERID, 
    GURAUOB_ACTIVITY_DATE, GURAUOB_USER_ID, GURAUOB_COMMENTS, GURAUOB_DATA_ORIGIN)
 Values
   (TO_TIMESTAMP('5/1/2014 9:44:58.209682 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'I', 'SSASECT', 'BAN_DEFAULT_Q', 'WMAQABLEH', 
    TO_DATE('05/01/2014 09:44:58', 'MM/DD/YYYY HH24:MI:SS'), 'BANSECR', NULL, NULL);
Insert into GURAUOB
   (GURAUOB_AUDIT_TIME, GURAUOB_AUDIT_ACTION, GURAUOB_OBJECT, GURAUOB_ROLE, GURAUOB_USERID, 
    GURAUOB_ACTIVITY_DATE, GURAUOB_USER_ID, GURAUOB_COMMENTS, GURAUOB_DATA_ORIGIN)
 Values
   (TO_TIMESTAMP('5/1/2014 10:58:00.683693 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'I', 'SSASECT', 'BAN_DEFAULT_Q', 'SSMOHAMMED', 
    TO_DATE('05/01/2014 10:58:00', 'MM/DD/YYYY HH24:MI:SS'), 'BANSECR', NULL, NULL);
Insert into GURAUOB
   (GURAUOB_AUDIT_TIME, GURAUOB_AUDIT_ACTION, GURAUOB_OBJECT, GURAUOB_ROLE, GURAUOB_USERID, 
    GURAUOB_ACTIVITY_DATE, GURAUOB_USER_ID, GURAUOB_COMMENTS, GURAUOB_DATA_ORIGIN)
 Values
   (TO_TIMESTAMP('5/1/2014 10:58:27.259695 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'U', 'SSASECT', 'BAN_DEFAULT_M', 'SSMOHAMMED', 
    TO_DATE('05/01/2014 10:58:27', 'MM/DD/YYYY HH24:MI:SS'), 'BANSECR', NULL, NULL);
Insert into GURAUOB
   (GURAUOB_AUDIT_TIME, GURAUOB_AUDIT_ACTION, GURAUOB_OBJECT, GURAUOB_ROLE, GURAUOB_USERID, 
    GURAUOB_ACTIVITY_DATE, GURAUOB_USER_ID, GURAUOB_COMMENTS, GURAUOB_DATA_ORIGIN)
 Values
   (TO_TIMESTAMP('11/27/2014 10:11:37.973034 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'I', 'SSASECT', 'BAN_DEFAULT_Q', 'MDAHIYAT', 
    TO_DATE('11/27/2014 10:11:37', 'MM/DD/YYYY HH24:MI:SS'), 'BANSECR', NULL, NULL);
Insert into GURAUOB
   (GURAUOB_AUDIT_TIME, GURAUOB_AUDIT_ACTION, GURAUOB_OBJECT, GURAUOB_ROLE, GURAUOB_USERID, 
    GURAUOB_ACTIVITY_DATE, GURAUOB_USER_ID, GURAUOB_COMMENTS, GURAUOB_DATA_ORIGIN)
 Values
   (TO_TIMESTAMP('11/27/2014 10:11:53.592038 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'D', 'SSASECT', 'BAN_DEFAULT_Q', 'MDAHIYAT', 
    TO_DATE('11/27/2014 10:11:37', 'MM/DD/YYYY HH24:MI:SS'), 'BANSECR', NULL, NULL);
Insert into GURAUOB
   (GURAUOB_AUDIT_TIME, GURAUOB_AUDIT_ACTION, GURAUOB_OBJECT, GURAUOB_ROLE, GURAUOB_USERID, 
    GURAUOB_ACTIVITY_DATE, GURAUOB_USER_ID, GURAUOB_COMMENTS, GURAUOB_DATA_ORIGIN)
 Values
   (TO_TIMESTAMP('5/15/2014 9:46:13.620980 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'I', 'SSASECT', 'BAN_DEFAULT_Q', 'MNASSER', 
    TO_DATE('05/15/2014 09:46:13', 'MM/DD/YYYY HH24:MI:SS'), 'BANSECR', NULL, NULL);
Insert into GURAUOB
   (GURAUOB_AUDIT_TIME, GURAUOB_AUDIT_ACTION, GURAUOB_OBJECT, GURAUOB_ROLE, GURAUOB_USERID, 
    GURAUOB_ACTIVITY_DATE, GURAUOB_USER_ID, GURAUOB_COMMENTS, GURAUOB_DATA_ORIGIN)
 Values
   (TO_TIMESTAMP('5/15/2014 9:46:23.703982 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'D', 'SSASECT', 'BAN_DEFAULT_Q', 'MNASSER', 
    TO_DATE('05/15/2014 09:46:13', 'MM/DD/YYYY HH24:MI:SS'), 'BANSECR', NULL, NULL);
Insert into GURAUOB
   (GURAUOB_AUDIT_TIME, GURAUOB_AUDIT_ACTION, GURAUOB_OBJECT, GURAUOB_ROLE, GURAUOB_USERID, 
    GURAUOB_ACTIVITY_DATE, GURAUOB_USER_ID, GURAUOB_COMMENTS, GURAUOB_DATA_ORIGIN)
 Values
   (TO_TIMESTAMP('5/4/2014 11:20:18.722706 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'D', 'SSASECT', 'BAN_DEFAULT_M', 'SSMOHAMMED', 
    TO_DATE('05/01/2014 10:58:27', 'MM/DD/YYYY HH24:MI:SS'), 'BANSECR', NULL, NULL);
Insert into GURAUOB
   (GURAUOB_AUDIT_TIME, GURAUOB_AUDIT_ACTION, GURAUOB_OBJECT, GURAUOB_ROLE, GURAUOB_USERID, 
    GURAUOB_ACTIVITY_DATE, GURAUOB_USER_ID, GURAUOB_COMMENTS, GURAUOB_DATA_ORIGIN)
 Values
   (TO_TIMESTAMP('8/5/2014 7:02:35.568204 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'D', 'SSASECT', 'BAN_DEFAULT_Q', 'KMALZAHRANI', 
    TO_DATE('06/19/2014 10:10:05', 'MM/DD/YYYY HH24:MI:SS'), 'BANSECR', NULL, NULL);
Insert into GURAUOB
   (GURAUOB_AUDIT_TIME, GURAUOB_AUDIT_ACTION, GURAUOB_OBJECT, GURAUOB_ROLE, GURAUOB_USERID, 
    GURAUOB_ACTIVITY_DATE, GURAUOB_USER_ID, GURAUOB_COMMENTS, GURAUOB_DATA_ORIGIN)
 Values
   (TO_TIMESTAMP('8/24/2014 11:38:35.878847 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'I', 'SSASECT', 'BAN_DEFAULT_Q', 'SASALRAGEEB', 
    TO_DATE('08/24/2014 11:38:35', 'MM/DD/YYYY HH24:MI:SS'), 'BANSECR', NULL, NULL);
Insert into GURAUOB
   (GURAUOB_AUDIT_TIME, GURAUOB_AUDIT_ACTION, GURAUOB_OBJECT, GURAUOB_ROLE, GURAUOB_USERID, 
    GURAUOB_ACTIVITY_DATE, GURAUOB_USER_ID, GURAUOB_COMMENTS, GURAUOB_DATA_ORIGIN)
 Values
   (TO_TIMESTAMP('8/24/2014 11:38:43.509851 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'D', 'SSASECT', 'BAN_DEFAULT_Q', 'SASALRAGEEB', 
    TO_DATE('08/24/2014 11:38:35', 'MM/DD/YYYY HH24:MI:SS'), 'BANSECR', NULL, NULL);
Insert into GURAUOB
   (GURAUOB_AUDIT_TIME, GURAUOB_AUDIT_ACTION, GURAUOB_OBJECT, GURAUOB_ROLE, GURAUOB_USERID, 
    GURAUOB_ACTIVITY_DATE, GURAUOB_USER_ID, GURAUOB_COMMENTS, GURAUOB_DATA_ORIGIN)
 Values
   (TO_TIMESTAMP('6/19/2014 10:10:05.009413 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'U', 'SSASECT', 'BAN_DEFAULT_Q', 'KMALZAHRANI', 
    TO_DATE('06/19/2014 10:10:05', 'MM/DD/YYYY HH24:MI:SS'), 'BANSECR', NULL, NULL);
Insert into GURAUOB
   (GURAUOB_AUDIT_TIME, GURAUOB_AUDIT_ACTION, GURAUOB_OBJECT, GURAUOB_ROLE, GURAUOB_USERID, 
    GURAUOB_ACTIVITY_DATE, GURAUOB_USER_ID, GURAUOB_COMMENTS, GURAUOB_DATA_ORIGIN)
 Values
   (TO_TIMESTAMP('10/20/2014 11:00:32.092016 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'D', 'SSASECT', 'BAN_DEFAULT_Q', 'FRAFEE', 
    TO_DATE('02/03/2014 11:34:46', 'MM/DD/YYYY HH24:MI:SS'), 'BANSECR', NULL, NULL);
Insert into GURAUOB
   (GURAUOB_AUDIT_TIME, GURAUOB_AUDIT_ACTION, GURAUOB_OBJECT, GURAUOB_ROLE, GURAUOB_USERID, 
    GURAUOB_ACTIVITY_DATE, GURAUOB_USER_ID, GURAUOB_COMMENTS, GURAUOB_DATA_ORIGIN)
 Values
   (TO_TIMESTAMP('10/20/2014 11:01:45.914028 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'I', 'SSASECT', 'BAN_DEFAULT_Q', 'AAOMARY', 
    TO_DATE('10/20/2014 11:01:45', 'MM/DD/YYYY HH24:MI:SS'), 'BANSECR', NULL, NULL);
Insert into GURAUOB
   (GURAUOB_AUDIT_TIME, GURAUOB_AUDIT_ACTION, GURAUOB_OBJECT, GURAUOB_ROLE, GURAUOB_USERID, 
    GURAUOB_ACTIVITY_DATE, GURAUOB_USER_ID, GURAUOB_COMMENTS, GURAUOB_DATA_ORIGIN)
 Values
   (TO_TIMESTAMP('10/20/2014 11:01:52.475032 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'D', 'SSASECT', 'BAN_DEFAULT_Q', 'AAOMARY', 
    TO_DATE('10/20/2014 11:01:45', 'MM/DD/YYYY HH24:MI:SS'), 'BANSECR', NULL, NULL);
Insert into GURAUOB
   (GURAUOB_AUDIT_TIME, GURAUOB_AUDIT_ACTION, GURAUOB_OBJECT, GURAUOB_ROLE, GURAUOB_USERID, 
    GURAUOB_ACTIVITY_DATE, GURAUOB_USER_ID, GURAUOB_COMMENTS, GURAUOB_DATA_ORIGIN)
 Values
   (TO_TIMESTAMP('7/28/2015 1:05:37.583801 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'U', 'SSASECT', 'BAN_DEFAULT_M', 'MKHALIFA', 
    TO_DATE('07/28/2015 13:05:37', 'MM/DD/YYYY HH24:MI:SS'), 'BANSECR', NULL, NULL);
Insert into GURAUOB
   (GURAUOB_AUDIT_TIME, GURAUOB_AUDIT_ACTION, GURAUOB_OBJECT, GURAUOB_ROLE, GURAUOB_USERID, 
    GURAUOB_ACTIVITY_DATE, GURAUOB_USER_ID, GURAUOB_COMMENTS, GURAUOB_DATA_ORIGIN)
 Values
   (TO_TIMESTAMP('8/17/2015 2:24:21.811207 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'U', 'SSASECT', 'BAN_DEFAULT_Q', 'TAKEL', 
    TO_DATE('08/17/2015 14:24:21', 'MM/DD/YYYY HH24:MI:SS'), 'BANSECR', NULL, NULL);
Insert into GURAUOB
   (GURAUOB_AUDIT_TIME, GURAUOB_AUDIT_ACTION, GURAUOB_OBJECT, GURAUOB_ROLE, GURAUOB_USERID, 
    GURAUOB_ACTIVITY_DATE, GURAUOB_USER_ID, GURAUOB_COMMENTS, GURAUOB_DATA_ORIGIN)
 Values
   (TO_TIMESTAMP('9/3/2015 12:56:52.374491 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'U', 'SSASECT', 'BAN_DEFAULT_M', 'TAKEL', 
    TO_DATE('09/03/2015 12:56:52', 'MM/DD/YYYY HH24:MI:SS'), 'BANSECR', NULL, NULL);
Insert into GURAUOB
   (GURAUOB_AUDIT_TIME, GURAUOB_AUDIT_ACTION, GURAUOB_OBJECT, GURAUOB_ROLE, GURAUOB_USERID, 
    GURAUOB_ACTIVITY_DATE, GURAUOB_USER_ID, GURAUOB_COMMENTS, GURAUOB_DATA_ORIGIN)
 Values
   (TO_TIMESTAMP('7/5/2015 1:49:53.310401 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'I', 'SSASECT', 'BAN_DEFAULT_Q', 'MKHALIFA', 
    TO_DATE('07/05/2015 13:49:53', 'MM/DD/YYYY HH24:MI:SS'), 'BANSECR', NULL, NULL);
Insert into GURAUOB
   (GURAUOB_AUDIT_TIME, GURAUOB_AUDIT_ACTION, GURAUOB_OBJECT, GURAUOB_ROLE, GURAUOB_USERID, 
    GURAUOB_ACTIVITY_DATE, GURAUOB_USER_ID, GURAUOB_COMMENTS, GURAUOB_DATA_ORIGIN)
 Values
   (TO_TIMESTAMP('8/10/2015 11:40:03.423001 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'I', 'SSASECT', 'BAN_DEFAULT_M', 'TAKEL', 
    TO_DATE('08/10/2015 11:40:03', 'MM/DD/YYYY HH24:MI:SS'), 'BANSECR', NULL, NULL);
Insert into GURAUOB
   (GURAUOB_AUDIT_TIME, GURAUOB_AUDIT_ACTION, GURAUOB_OBJECT, GURAUOB_ROLE, GURAUOB_USERID, 
    GURAUOB_ACTIVITY_DATE, GURAUOB_USER_ID, GURAUOB_COMMENTS, GURAUOB_DATA_ORIGIN)
 Values
   (TO_TIMESTAMP('10/26/2016 10:05:20.707829 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'U', 'SSASECT', 'BAN_DEFAULT_Q', 'MMAHMAD', 
    TO_DATE('10/26/2016 10:05:20', 'MM/DD/YYYY HH24:MI:SS'), 'BANSECR', NULL, NULL);
Insert into GURAUOB
   (GURAUOB_AUDIT_TIME, GURAUOB_AUDIT_ACTION, GURAUOB_OBJECT, GURAUOB_ROLE, GURAUOB_USERID, 
    GURAUOB_ACTIVITY_DATE, GURAUOB_USER_ID, GURAUOB_COMMENTS, GURAUOB_DATA_ORIGIN)
 Values
   (TO_TIMESTAMP('8/17/2015 2:57:11.721330 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'D', 'SSASECT', 'BAN_DEFAULT_M', 'MKHALIFA', 
    TO_DATE('07/28/2015 13:05:37', 'MM/DD/YYYY HH24:MI:SS'), 'BANSECR', NULL, NULL);
Insert into GURAUOB
   (GURAUOB_AUDIT_TIME, GURAUOB_AUDIT_ACTION, GURAUOB_OBJECT, GURAUOB_ROLE, GURAUOB_USERID, 
    GURAUOB_ACTIVITY_DATE, GURAUOB_USER_ID, GURAUOB_COMMENTS, GURAUOB_DATA_ORIGIN)
 Values
   (TO_TIMESTAMP('9/10/2015 8:22:29.043606 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'D', 'SSASECT', 'BAN_DEFAULT_M', 'TAKEL', 
    TO_DATE('09/03/2015 12:56:52', 'MM/DD/YYYY HH24:MI:SS'), 'BANSECR', NULL, NULL);
Insert into GURAUOB
   (GURAUOB_AUDIT_TIME, GURAUOB_AUDIT_ACTION, GURAUOB_OBJECT, GURAUOB_ROLE, GURAUOB_USERID, 
    GURAUOB_ACTIVITY_DATE, GURAUOB_USER_ID, GURAUOB_COMMENTS, GURAUOB_DATA_ORIGIN)
 Values
   (TO_TIMESTAMP('4/19/2015 8:43:39.092602 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'D', 'SSASECT', 'BAN_DEFAULT_Q', 'WMAQABLEH', 
    TO_DATE('05/01/2014 09:44:58', 'MM/DD/YYYY HH24:MI:SS'), 'BANSECR', NULL, NULL);
Insert into GURAUOB
   (GURAUOB_AUDIT_TIME, GURAUOB_AUDIT_ACTION, GURAUOB_OBJECT, GURAUOB_ROLE, GURAUOB_USERID, 
    GURAUOB_ACTIVITY_DATE, GURAUOB_USER_ID, GURAUOB_COMMENTS, GURAUOB_DATA_ORIGIN)
 Values
   (TO_TIMESTAMP('4/8/2015 10:19:09.159426 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'D', 'SSASECT', 'BAN_DEFAULT_Q', 'MOMARY', 
    TO_DATE('02/10/2014 13:55:42', 'MM/DD/YYYY HH24:MI:SS'), 'BANSECR', NULL, NULL);
Insert into GURAUOB
   (GURAUOB_AUDIT_TIME, GURAUOB_AUDIT_ACTION, GURAUOB_OBJECT, GURAUOB_ROLE, GURAUOB_USERID, 
    GURAUOB_ACTIVITY_DATE, GURAUOB_USER_ID, GURAUOB_COMMENTS, GURAUOB_DATA_ORIGIN)
 Values
   (TO_TIMESTAMP('4/8/2015 10:20:32.591427 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'D', 'SSASECT', 'BAN_DEFAULT_Q', 'HMADKOR', 
    TO_DATE('11/12/2013 11:51:35', 'MM/DD/YYYY HH24:MI:SS'), 'BANSECR', NULL, NULL);
Insert into GURAUOB
   (GURAUOB_AUDIT_TIME, GURAUOB_AUDIT_ACTION, GURAUOB_OBJECT, GURAUOB_ROLE, GURAUOB_USERID, 
    GURAUOB_ACTIVITY_DATE, GURAUOB_USER_ID, GURAUOB_COMMENTS, GURAUOB_DATA_ORIGIN)
 Values
   (TO_TIMESTAMP('9/8/2015 6:21:59.587605 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'I', 'SSASECT', 'BAN_DEFAULT_M', 'MMAHMAD', 
    TO_DATE('09/08/2015 18:21:59', 'MM/DD/YYYY HH24:MI:SS'), 'BANSECR', NULL, NULL);
Insert into GURAUOB
   (GURAUOB_AUDIT_TIME, GURAUOB_AUDIT_ACTION, GURAUOB_OBJECT, GURAUOB_ROLE, GURAUOB_USERID, 
    GURAUOB_ACTIVITY_DATE, GURAUOB_USER_ID, GURAUOB_COMMENTS, GURAUOB_DATA_ORIGIN)
 Values
   (TO_TIMESTAMP('7/1/2017 3:25:01.622805 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'D', 'SSASECT', 'BAN_DEFAULT_Q', 'MMAHMAD', 
    TO_DATE('10/26/2016 10:05:20', 'MM/DD/YYYY HH24:MI:SS'), 'BANSECR', NULL, NULL);
Insert into GURAUOB
   (GURAUOB_AUDIT_TIME, GURAUOB_AUDIT_ACTION, GURAUOB_OBJECT, GURAUOB_ROLE, GURAUOB_USERID, 
    GURAUOB_ACTIVITY_DATE, GURAUOB_USER_ID, GURAUOB_COMMENTS, GURAUOB_DATA_ORIGIN)
 Values
   (TO_TIMESTAMP('12/10/2017 12:40:50.084411 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'I', 'SSASECT', 'BAN_DEFAULT_M', 'BU_SECTIONS', 
    TO_DATE('12/10/2017 12:40:50', 'MM/DD/YYYY HH24:MI:SS'), 'BANSECR', NULL, NULL);
Insert into GURAUOB
   (GURAUOB_AUDIT_TIME, GURAUOB_AUDIT_ACTION, GURAUOB_OBJECT, GURAUOB_ROLE, GURAUOB_USERID, 
    GURAUOB_ACTIVITY_DATE, GURAUOB_USER_ID, GURAUOB_COMMENTS, GURAUOB_DATA_ORIGIN)
 Values
   (TO_TIMESTAMP('12/6/2017 2:18:43.870863 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'I', 'SSASECT', 'BAN_DEFAULT_M', 'BU_SCHEDULE_COORDINATOR', 
    TO_DATE('12/06/2017 14:18:43', 'MM/DD/YYYY HH24:MI:SS'), 'BANSECR', NULL, NULL);
Insert into GURAUOB
   (GURAUOB_AUDIT_TIME, GURAUOB_AUDIT_ACTION, GURAUOB_OBJECT, GURAUOB_ROLE, GURAUOB_USERID, 
    GURAUOB_ACTIVITY_DATE, GURAUOB_USER_ID, GURAUOB_COMMENTS, GURAUOB_DATA_ORIGIN)
 Values
   (TO_TIMESTAMP('1/2/2018 9:54:33.176656 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'I', 'SSASECT', 'BAN_DEFAULT_M', 'AALABDULLAH', 
    TO_DATE('01/02/2018 09:54:33', 'MM/DD/YYYY HH24:MI:SS'), 'BANSECR_ALIALZANDI', NULL, NULL);
Insert into GURAUOB
   (GURAUOB_AUDIT_TIME, GURAUOB_AUDIT_ACTION, GURAUOB_OBJECT, GURAUOB_ROLE, GURAUOB_USERID, 
    GURAUOB_ACTIVITY_DATE, GURAUOB_USER_ID, GURAUOB_COMMENTS, GURAUOB_DATA_ORIGIN)
 Values
   (TO_TIMESTAMP('1/2/2018 9:56:27.675662 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'I', 'SSASECT', 'BAN_DEFAULT_M', 'AGHAMDI', 
    TO_DATE('01/02/2018 09:56:27', 'MM/DD/YYYY HH24:MI:SS'), 'BANSECR_ALIALZANDI', NULL, NULL);
Insert into GURAUOB
   (GURAUOB_AUDIT_TIME, GURAUOB_AUDIT_ACTION, GURAUOB_OBJECT, GURAUOB_ROLE, GURAUOB_USERID, 
    GURAUOB_ACTIVITY_DATE, GURAUOB_USER_ID, GURAUOB_COMMENTS, GURAUOB_DATA_ORIGIN)
 Values
   (TO_TIMESTAMP('1/2/2018 10:11:01.873672 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'I', 'SSASECT', 'BAN_DEFAULT_M', 'KAALGHAMDI', 
    TO_DATE('01/02/2018 10:11:01', 'MM/DD/YYYY HH24:MI:SS'), 'BANSECR_ALIALZANDI', NULL, NULL);
Insert into GURAUOB
   (GURAUOB_AUDIT_TIME, GURAUOB_AUDIT_ACTION, GURAUOB_OBJECT, GURAUOB_ROLE, GURAUOB_USERID, 
    GURAUOB_ACTIVITY_DATE, GURAUOB_USER_ID, GURAUOB_COMMENTS, GURAUOB_DATA_ORIGIN)
 Values
   (TO_TIMESTAMP('1/2/2018 10:12:44.653676 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'I', 'SSASECT', 'BAN_DEFAULT_M', 'ESSAMALGHAMDI', 
    TO_DATE('01/02/2018 10:12:44', 'MM/DD/YYYY HH24:MI:SS'), 'BANSECR_ALIALZANDI', NULL, NULL);
Insert into GURAUOB
   (GURAUOB_AUDIT_TIME, GURAUOB_AUDIT_ACTION, GURAUOB_OBJECT, GURAUOB_ROLE, GURAUOB_USERID, 
    GURAUOB_ACTIVITY_DATE, GURAUOB_USER_ID, GURAUOB_COMMENTS, GURAUOB_DATA_ORIGIN)
 Values
   (TO_TIMESTAMP('1/2/2018 10:14:04.599688 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'I', 'SSASECT', 'BAN_DEFAULT_M', 'MAHMEDALGHAMDI', 
    TO_DATE('01/02/2018 10:14:04', 'MM/DD/YYYY HH24:MI:SS'), 'BANSECR_ALIALZANDI', NULL, NULL);
Insert into GURAUOB
   (GURAUOB_AUDIT_TIME, GURAUOB_AUDIT_ACTION, GURAUOB_OBJECT, GURAUOB_ROLE, GURAUOB_USERID, 
    GURAUOB_ACTIVITY_DATE, GURAUOB_USER_ID, GURAUOB_COMMENTS, GURAUOB_DATA_ORIGIN)
 Values
   (TO_TIMESTAMP('1/2/2018 10:14:48.798693 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'I', 'SSASECT', 'BAN_DEFAULT_M', 'RALGHAMDI', 
    TO_DATE('01/02/2018 10:14:48', 'MM/DD/YYYY HH24:MI:SS'), 'BANSECR_ALIALZANDI', NULL, NULL);
Insert into GURAUOB
   (GURAUOB_AUDIT_TIME, GURAUOB_AUDIT_ACTION, GURAUOB_OBJECT, GURAUOB_ROLE, GURAUOB_USERID, 
    GURAUOB_ACTIVITY_DATE, GURAUOB_USER_ID, GURAUOB_COMMENTS, GURAUOB_DATA_ORIGIN)
 Values
   (TO_TIMESTAMP('1/2/2018 10:21:06.031716 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'I', 'SSASECT', 'BAN_DEFAULT_M', 'SAABDALLAH', 
    TO_DATE('01/02/2018 10:21:06', 'MM/DD/YYYY HH24:MI:SS'), 'BANSECR_ALIALZANDI', NULL, NULL);
Insert into GURAUOB
   (GURAUOB_AUDIT_TIME, GURAUOB_AUDIT_ACTION, GURAUOB_OBJECT, GURAUOB_ROLE, GURAUOB_USERID, 
    GURAUOB_ACTIVITY_DATE, GURAUOB_USER_ID, GURAUOB_COMMENTS, GURAUOB_DATA_ORIGIN)
 Values
   (TO_TIMESTAMP('1/2/2018 10:23:19.393728 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'I', 'SSASECT', 'BAN_DEFAULT_M', 'SMGHAMDI', 
    TO_DATE('01/02/2018 10:23:19', 'MM/DD/YYYY HH24:MI:SS'), 'BANSECR_ALIALZANDI', NULL, NULL);
Insert into GURAUOB
   (GURAUOB_AUDIT_TIME, GURAUOB_AUDIT_ACTION, GURAUOB_OBJECT, GURAUOB_ROLE, GURAUOB_USERID, 
    GURAUOB_ACTIVITY_DATE, GURAUOB_USER_ID, GURAUOB_COMMENTS, GURAUOB_DATA_ORIGIN)
 Values
   (TO_TIMESTAMP('1/2/2018 10:24:12.661733 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'I', 'SSASECT', 'BAN_DEFAULT_M', 'SNSN1419', 
    TO_DATE('01/02/2018 10:24:12', 'MM/DD/YYYY HH24:MI:SS'), 'BANSECR_ALIALZANDI', NULL, NULL);
Insert into GURAUOB
   (GURAUOB_AUDIT_TIME, GURAUOB_AUDIT_ACTION, GURAUOB_OBJECT, GURAUOB_ROLE, GURAUOB_USERID, 
    GURAUOB_ACTIVITY_DATE, GURAUOB_USER_ID, GURAUOB_COMMENTS, GURAUOB_DATA_ORIGIN)
 Values
   (TO_TIMESTAMP('1/24/2018 12:46:17.356418 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'I', 'SSASECT', 'BAN_DEFAULT_M', 'ALKHATHAMI', 
    TO_DATE('01/24/2018 12:46:17', 'MM/DD/YYYY HH24:MI:SS'), 'BANSECR_ALIALZANDI', NULL, NULL);
Insert into GURAUOB
   (GURAUOB_AUDIT_TIME, GURAUOB_AUDIT_ACTION, GURAUOB_OBJECT, GURAUOB_ROLE, GURAUOB_USERID, 
    GURAUOB_ACTIVITY_DATE, GURAUOB_USER_ID, GURAUOB_COMMENTS, GURAUOB_DATA_ORIGIN)
 Values
   (TO_TIMESTAMP('4/4/2018 9:06:05.818601 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'I', 'SSASECT', 'BAN_DEFAULT_M', 'ASHALGHAMDI', 
    TO_DATE('04/04/2018 09:06:05', 'MM/DD/YYYY HH24:MI:SS'), 'BANSECR_KOALGHAMDI', NULL, NULL);
Insert into GURAUOB
   (GURAUOB_AUDIT_TIME, GURAUOB_AUDIT_ACTION, GURAUOB_OBJECT, GURAUOB_ROLE, GURAUOB_USERID, 
    GURAUOB_ACTIVITY_DATE, GURAUOB_USER_ID, GURAUOB_COMMENTS, GURAUOB_DATA_ORIGIN)
 Values
   (TO_TIMESTAMP('1/8/2018 8:45:51.496016 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'I', 'SSASECT', 'BAN_DEFAULT_M', 'AYMANALZAHRANI', 
    TO_DATE('01/08/2018 08:45:51', 'MM/DD/YYYY HH24:MI:SS'), 'BANSECR_ALIALZANDI', NULL, NULL);
Insert into GURAUOB
   (GURAUOB_AUDIT_TIME, GURAUOB_AUDIT_ACTION, GURAUOB_OBJECT, GURAUOB_ROLE, GURAUOB_USERID, 
    GURAUOB_ACTIVITY_DATE, GURAUOB_USER_ID, GURAUOB_COMMENTS, GURAUOB_DATA_ORIGIN)
 Values
   (TO_TIMESTAMP('6/25/2018 7:59:55.953056 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'D', 'SSASECT', 'BAN_DEFAULT_M', 'AYMANALZAHRANI', 
    TO_DATE('01/08/2018 08:45:51', 'MM/DD/YYYY HH24:MI:SS'), 'BANSECR_KOALGHAMDI', NULL, NULL);
Insert into GURAUOB
   (GURAUOB_AUDIT_TIME, GURAUOB_AUDIT_ACTION, GURAUOB_OBJECT, GURAUOB_ROLE, GURAUOB_USERID, 
    GURAUOB_ACTIVITY_DATE, GURAUOB_USER_ID, GURAUOB_COMMENTS, GURAUOB_DATA_ORIGIN)
 Values
   (TO_TIMESTAMP('11/11/2018 11:09:53.897601 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'I', 'SSASECT', 'BAN_DEFAULT_M', 'AAHAREDY', 
    TO_DATE('11/11/2018 11:09:53', 'MM/DD/YYYY HH24:MI:SS'), 'BANSECR_KOALGHAMDI', NULL, NULL);
Insert into GURAUOB
   (GURAUOB_AUDIT_TIME, GURAUOB_AUDIT_ACTION, GURAUOB_OBJECT, GURAUOB_ROLE, GURAUOB_USERID, 
    GURAUOB_ACTIVITY_DATE, GURAUOB_USER_ID, GURAUOB_COMMENTS, GURAUOB_DATA_ORIGIN)
 Values
   (TO_TIMESTAMP('11/12/2018 8:18:21.845602 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'I', 'SSASECT', 'BAN_DEFAULT_M', 'SALROBAI', 
    TO_DATE('11/12/2018 08:18:21', 'MM/DD/YYYY HH24:MI:SS'), 'BANSECR_KOALGHAMDI', NULL, NULL);
Insert into GURAUOB
   (GURAUOB_AUDIT_TIME, GURAUOB_AUDIT_ACTION, GURAUOB_OBJECT, GURAUOB_ROLE, GURAUOB_USERID, 
    GURAUOB_ACTIVITY_DATE, GURAUOB_USER_ID, GURAUOB_COMMENTS, GURAUOB_DATA_ORIGIN)
 Values
   (TO_TIMESTAMP('11/12/2018 8:40:55.812603 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'I', 'SSASECT', 'BAN_DEFAULT_M', 'EAMADY', 
    TO_DATE('11/12/2018 08:40:55', 'MM/DD/YYYY HH24:MI:SS'), 'BANSECR_KOALGHAMDI', NULL, NULL);
Insert into GURAUOB
   (GURAUOB_AUDIT_TIME, GURAUOB_AUDIT_ACTION, GURAUOB_OBJECT, GURAUOB_ROLE, GURAUOB_USERID, 
    GURAUOB_ACTIVITY_DATE, GURAUOB_USER_ID, GURAUOB_COMMENTS, GURAUOB_DATA_ORIGIN)
 Values
   (TO_TIMESTAMP('11/12/2018 9:09:42.247604 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'I', 'SSASECT', 'BAN_DEFAULT_M', 'MAKEEN', 
    TO_DATE('11/12/2018 09:09:42', 'MM/DD/YYYY HH24:MI:SS'), 'BANSECR_KOALGHAMDI', NULL, NULL);
Insert into GURAUOB
   (GURAUOB_AUDIT_TIME, GURAUOB_AUDIT_ACTION, GURAUOB_OBJECT, GURAUOB_ROLE, GURAUOB_USERID, 
    GURAUOB_ACTIVITY_DATE, GURAUOB_USER_ID, GURAUOB_COMMENTS, GURAUOB_DATA_ORIGIN)
 Values
   (TO_TIMESTAMP('11/12/2018 9:10:48.951605 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'I', 'SSASECT', 'BAN_DEFAULT_M', 'JMALGHAMDI', 
    TO_DATE('11/12/2018 09:10:48', 'MM/DD/YYYY HH24:MI:SS'), 'BANSECR_KOALGHAMDI', NULL, NULL);
Insert into GURAUOB
   (GURAUOB_AUDIT_TIME, GURAUOB_AUDIT_ACTION, GURAUOB_OBJECT, GURAUOB_ROLE, GURAUOB_USERID, 
    GURAUOB_ACTIVITY_DATE, GURAUOB_USER_ID, GURAUOB_COMMENTS, GURAUOB_DATA_ORIGIN)
 Values
   (TO_TIMESTAMP('11/12/2018 9:13:25.873606 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'I', 'SSASECT', 'BAN_DEFAULT_M', 'MALTHUOBITI', 
    TO_DATE('11/12/2018 09:13:25', 'MM/DD/YYYY HH24:MI:SS'), 'BANSECR_KOALGHAMDI', NULL, NULL);
Insert into GURAUOB
   (GURAUOB_AUDIT_TIME, GURAUOB_AUDIT_ACTION, GURAUOB_OBJECT, GURAUOB_ROLE, GURAUOB_USERID, 
    GURAUOB_ACTIVITY_DATE, GURAUOB_USER_ID, GURAUOB_COMMENTS, GURAUOB_DATA_ORIGIN)
 Values
   (TO_TIMESTAMP('11/12/2018 9:14:04.577608 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'I', 'SSASECT', 'BAN_DEFAULT_M', 'SALEHAIA', 
    TO_DATE('11/12/2018 09:14:04', 'MM/DD/YYYY HH24:MI:SS'), 'BANSECR_KOALGHAMDI', NULL, NULL);
Insert into GURAUOB
   (GURAUOB_AUDIT_TIME, GURAUOB_AUDIT_ACTION, GURAUOB_OBJECT, GURAUOB_ROLE, GURAUOB_USERID, 
    GURAUOB_ACTIVITY_DATE, GURAUOB_USER_ID, GURAUOB_COMMENTS, GURAUOB_DATA_ORIGIN)
 Values
   (TO_TIMESTAMP('11/12/2018 9:35:06.717609 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'I', 'SSASECT', 'BAN_DEFAULT_M', 'MAREF', 
    TO_DATE('11/12/2018 09:35:06', 'MM/DD/YYYY HH24:MI:SS'), 'BANSECR_KOALGHAMDI', NULL, NULL);
Insert into GURAUOB
   (GURAUOB_AUDIT_TIME, GURAUOB_AUDIT_ACTION, GURAUOB_OBJECT, GURAUOB_ROLE, GURAUOB_USERID, 
    GURAUOB_ACTIVITY_DATE, GURAUOB_USER_ID, GURAUOB_COMMENTS, GURAUOB_DATA_ORIGIN)
 Values
   (TO_TIMESTAMP('12/3/2018 9:45:01.306203 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'I', 'SSASECT', 'BAN_DEFAULT_M', 'SSALOMARI', 
    TO_DATE('12/03/2018 09:45:01', 'MM/DD/YYYY HH24:MI:SS'), 'BANSECR_KOALGHAMDI', NULL, NULL);
Insert into GURAUOB
   (GURAUOB_AUDIT_TIME, GURAUOB_AUDIT_ACTION, GURAUOB_OBJECT, GURAUOB_ROLE, GURAUOB_USERID, 
    GURAUOB_ACTIVITY_DATE, GURAUOB_USER_ID, GURAUOB_COMMENTS, GURAUOB_DATA_ORIGIN)
 Values
   (TO_TIMESTAMP('12/9/2018 8:49:19.492214 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'I', 'SSASECT', 'BAN_DEFAULT_M', 'AIASA123', 
    TO_DATE('12/09/2018 08:49:19', 'MM/DD/YYYY HH24:MI:SS'), 'BANSECR_KOALGHAMDI', NULL, NULL);
Insert into GURAUOB
   (GURAUOB_AUDIT_TIME, GURAUOB_AUDIT_ACTION, GURAUOB_OBJECT, GURAUOB_ROLE, GURAUOB_USERID, 
    GURAUOB_ACTIVITY_DATE, GURAUOB_USER_ID, GURAUOB_COMMENTS, GURAUOB_DATA_ORIGIN)
 Values
   (TO_TIMESTAMP('12/9/2018 8:51:52.783215 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'I', 'SSASECT', 'BAN_DEFAULT_M', 'RALHARBI', 
    TO_DATE('12/09/2018 08:51:52', 'MM/DD/YYYY HH24:MI:SS'), 'BANSECR_KOALGHAMDI', NULL, NULL);
Insert into GURAUOB
   (GURAUOB_AUDIT_TIME, GURAUOB_AUDIT_ACTION, GURAUOB_OBJECT, GURAUOB_ROLE, GURAUOB_USERID, 
    GURAUOB_ACTIVITY_DATE, GURAUOB_USER_ID, GURAUOB_COMMENTS, GURAUOB_DATA_ORIGIN)
 Values
   (TO_TIMESTAMP('12/10/2018 8:42:23.065403 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'I', 'SSASECT', 'BAN_DEFAULT_M', 'LALSHEIKH', 
    TO_DATE('12/10/2018 08:42:23', 'MM/DD/YYYY HH24:MI:SS'), 'BANSECR_KOALGHAMDI', NULL, NULL);
Insert into GURAUOB
   (GURAUOB_AUDIT_TIME, GURAUOB_AUDIT_ACTION, GURAUOB_OBJECT, GURAUOB_ROLE, GURAUOB_USERID, 
    GURAUOB_ACTIVITY_DATE, GURAUOB_USER_ID, GURAUOB_COMMENTS, GURAUOB_DATA_ORIGIN)
 Values
   (TO_TIMESTAMP('12/10/2018 8:48:27.396425 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'I', 'SSASECT', 'BAN_DEFAULT_M', 'AAGHAMDI', 
    TO_DATE('12/10/2018 08:48:27', 'MM/DD/YYYY HH24:MI:SS'), 'BANSECR_KOALGHAMDI', NULL, NULL);
Insert into GURAUOB
   (GURAUOB_AUDIT_TIME, GURAUOB_AUDIT_ACTION, GURAUOB_OBJECT, GURAUOB_ROLE, GURAUOB_USERID, 
    GURAUOB_ACTIVITY_DATE, GURAUOB_USER_ID, GURAUOB_COMMENTS, GURAUOB_DATA_ORIGIN)
 Values
   (TO_TIMESTAMP('12/10/2018 8:50:42.098447 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'I', 'SSASECT', 'BAN_DEFAULT_M', 'KHGHAMDI', 
    TO_DATE('12/10/2018 08:50:42', 'MM/DD/YYYY HH24:MI:SS'), 'BANSECR_KOALGHAMDI', NULL, NULL);
Insert into GURAUOB
   (GURAUOB_AUDIT_TIME, GURAUOB_AUDIT_ACTION, GURAUOB_OBJECT, GURAUOB_ROLE, GURAUOB_USERID, 
    GURAUOB_ACTIVITY_DATE, GURAUOB_USER_ID, GURAUOB_COMMENTS, GURAUOB_DATA_ORIGIN)
 Values
   (TO_TIMESTAMP('1/7/2019 10:55:44.360314 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'D', 'SSASECT', 'BAN_DEFAULT_M', 'ASHALGHAMDI', 
    TO_DATE('04/04/2018 09:06:05', 'MM/DD/YYYY HH24:MI:SS'), 'BU_APPS', NULL, NULL);
Insert into GURAUOB
   (GURAUOB_AUDIT_TIME, GURAUOB_AUDIT_ACTION, GURAUOB_OBJECT, GURAUOB_ROLE, GURAUOB_USERID, 
    GURAUOB_ACTIVITY_DATE, GURAUOB_USER_ID, GURAUOB_COMMENTS, GURAUOB_DATA_ORIGIN)
 Values
   (TO_TIMESTAMP('11/14/2018 12:11:05.845613 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'I', 'SSASECT', 'BAN_DEFAULT_M', 'MALKHAZMARI', 
    TO_DATE('11/14/2018 12:11:05', 'MM/DD/YYYY HH24:MI:SS'), 'BANSECR_KOALGHAMDI', NULL, NULL);
Insert into GURAUOB
   (GURAUOB_AUDIT_TIME, GURAUOB_AUDIT_ACTION, GURAUOB_OBJECT, GURAUOB_ROLE, GURAUOB_USERID, 
    GURAUOB_ACTIVITY_DATE, GURAUOB_USER_ID, GURAUOB_COMMENTS, GURAUOB_DATA_ORIGIN)
 Values
   (TO_TIMESTAMP('11/15/2018 9:51:44.599623 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'I', 'SSASECT', 'BAN_DEFAULT_M', 'MALMANAH', 
    TO_DATE('11/15/2018 09:51:44', 'MM/DD/YYYY HH24:MI:SS'), 'BANSECR_KOALGHAMDI', NULL, NULL);
Insert into GURAUOB
   (GURAUOB_AUDIT_TIME, GURAUOB_AUDIT_ACTION, GURAUOB_OBJECT, GURAUOB_ROLE, GURAUOB_USERID, 
    GURAUOB_ACTIVITY_DATE, GURAUOB_USER_ID, GURAUOB_COMMENTS, GURAUOB_DATA_ORIGIN)
 Values
   (TO_TIMESTAMP('11/15/2018 10:43:58.893626 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'I', 'SSASECT', 'BAN_DEFAULT_M', 'MWAZAB', 
    TO_DATE('11/15/2018 10:43:58', 'MM/DD/YYYY HH24:MI:SS'), 'BANSECR_KOALGHAMDI', NULL, NULL);
Insert into GURAUOB
   (GURAUOB_AUDIT_TIME, GURAUOB_AUDIT_ACTION, GURAUOB_OBJECT, GURAUOB_ROLE, GURAUOB_USERID, 
    GURAUOB_ACTIVITY_DATE, GURAUOB_USER_ID, GURAUOB_COMMENTS, GURAUOB_DATA_ORIGIN)
 Values
   (TO_TIMESTAMP('10/14/2018 12:02:17.270024 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'I', 'SSASECT', 'BAN_DEFAULT_M', 'AALQARNI', 
    TO_DATE('10/14/2018 12:02:17', 'MM/DD/YYYY HH24:MI:SS'), 'BANSECR_KOALGHAMDI', NULL, NULL);
Insert into GURAUOB
   (GURAUOB_AUDIT_TIME, GURAUOB_AUDIT_ACTION, GURAUOB_OBJECT, GURAUOB_ROLE, GURAUOB_USERID, 
    GURAUOB_ACTIVITY_DATE, GURAUOB_USER_ID, GURAUOB_COMMENTS, GURAUOB_DATA_ORIGIN)
 Values
   (TO_TIMESTAMP('11/7/2018 1:36:16.426519 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'I', 'SSASECT', 'BAN_DEFAULT_M', 'YALAHMAD', 
    TO_DATE('11/07/2018 13:36:16', 'MM/DD/YYYY HH24:MI:SS'), 'BANSECR_KOALGHAMDI', NULL, NULL);
Insert into GURAUOB
   (GURAUOB_AUDIT_TIME, GURAUOB_AUDIT_ACTION, GURAUOB_OBJECT, GURAUOB_ROLE, GURAUOB_USERID, 
    GURAUOB_ACTIVITY_DATE, GURAUOB_USER_ID, GURAUOB_COMMENTS, GURAUOB_DATA_ORIGIN)
 Values
   (TO_TIMESTAMP('1/7/2019 11:09:24.219618 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'D', 'SSASECT', 'BAN_DEFAULT_M', 'YALAHMAD', 
    TO_DATE('11/07/2018 13:36:16', 'MM/DD/YYYY HH24:MI:SS'), 'BU_APPS', NULL, NULL);
Insert into GURAUOB
   (GURAUOB_AUDIT_TIME, GURAUOB_AUDIT_ACTION, GURAUOB_OBJECT, GURAUOB_ROLE, GURAUOB_USERID, 
    GURAUOB_ACTIVITY_DATE, GURAUOB_USER_ID, GURAUOB_COMMENTS, GURAUOB_DATA_ORIGIN)
 Values
   (TO_TIMESTAMP('1/7/2019 11:09:24.220620 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'D', 'SSASECT', 'BAN_DEFAULT_M', 'MALMANAH', 
    TO_DATE('11/15/2018 09:51:44', 'MM/DD/YYYY HH24:MI:SS'), 'BU_APPS', NULL, NULL);
Insert into GURAUOB
   (GURAUOB_AUDIT_TIME, GURAUOB_AUDIT_ACTION, GURAUOB_OBJECT, GURAUOB_ROLE, GURAUOB_USERID, 
    GURAUOB_ACTIVITY_DATE, GURAUOB_USER_ID, GURAUOB_COMMENTS, GURAUOB_DATA_ORIGIN)
 Values
   (TO_TIMESTAMP('1/7/2019 11:09:27.188760 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'I', 'SSASECT', 'BAN_DEFAULT_M', 'BU_VICE_DEAN', 
    TO_DATE('01/07/2019 11:09:27', 'MM/DD/YYYY HH24:MI:SS'), 'BANSECR', NULL, NULL);
Insert into GURAUOB
   (GURAUOB_AUDIT_TIME, GURAUOB_AUDIT_ACTION, GURAUOB_OBJECT, GURAUOB_ROLE, GURAUOB_USERID, 
    GURAUOB_ACTIVITY_DATE, GURAUOB_USER_ID, GURAUOB_COMMENTS, GURAUOB_DATA_ORIGIN)
 Values
   (TO_TIMESTAMP('1/7/2019 11:27:25.093845 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'D', 'SSASECT', 'BAN_DEFAULT_M', 'LALSHEIKH', 
    TO_DATE('12/10/2018 08:42:23', 'MM/DD/YYYY HH24:MI:SS'), 'BU_APPS', NULL, NULL);
Insert into GURAUOB
   (GURAUOB_AUDIT_TIME, GURAUOB_AUDIT_ACTION, GURAUOB_OBJECT, GURAUOB_ROLE, GURAUOB_USERID, 
    GURAUOB_ACTIVITY_DATE, GURAUOB_USER_ID, GURAUOB_COMMENTS, GURAUOB_DATA_ORIGIN)
 Values
   (TO_TIMESTAMP('1/7/2019 11:11:29.344765 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'U', 'SSASECT', 'BAN_DEFAULT_Q', 'BU_VICE_DEAN', 
    TO_DATE('01/07/2019 11:11:29', 'MM/DD/YYYY HH24:MI:SS'), 'BANSECR', NULL, NULL);
Insert into GURAUOB
   (GURAUOB_AUDIT_TIME, GURAUOB_AUDIT_ACTION, GURAUOB_OBJECT, GURAUOB_ROLE, GURAUOB_USERID, 
    GURAUOB_ACTIVITY_DATE, GURAUOB_USER_ID, GURAUOB_COMMENTS, GURAUOB_DATA_ORIGIN)
 Values
   (TO_TIMESTAMP('1/7/2019 11:36:09.999894 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'I', 'SSASECT', 'BAN_DEFAULT_M', 'EAMADY', 
    TO_DATE('01/07/2019 11:36:09', 'MM/DD/YYYY HH24:MI:SS'), 'BANSECR', NULL, NULL);
Insert into GURAUOB
   (GURAUOB_AUDIT_TIME, GURAUOB_AUDIT_ACTION, GURAUOB_OBJECT, GURAUOB_ROLE, GURAUOB_USERID, 
    GURAUOB_ACTIVITY_DATE, GURAUOB_USER_ID, GURAUOB_COMMENTS, GURAUOB_DATA_ORIGIN)
 Values
   (TO_TIMESTAMP('1/7/2019 2:47:05.537941 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'U', 'SSASECT', 'BAN_DEFAULT_M', 'BU_VICE_DEAN', 
    TO_DATE('01/07/2019 14:47:05', 'MM/DD/YYYY HH24:MI:SS'), 'BANSECR', NULL, NULL);
Insert into GURAUOB
   (GURAUOB_AUDIT_TIME, GURAUOB_AUDIT_ACTION, GURAUOB_OBJECT, GURAUOB_ROLE, GURAUOB_USERID, 
    GURAUOB_ACTIVITY_DATE, GURAUOB_USER_ID, GURAUOB_COMMENTS, GURAUOB_DATA_ORIGIN)
 Values
   (TO_TIMESTAMP('1/8/2019 9:34:26.142947 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'I', 'SSASECT', 'BAN_DEFAULT_M', 'MABURAS', 
    TO_DATE('01/08/2019 09:34:26', 'MM/DD/YYYY HH24:MI:SS'), 'BANSECR', NULL, NULL);
Insert into GURAUOB
   (GURAUOB_AUDIT_TIME, GURAUOB_AUDIT_ACTION, GURAUOB_OBJECT, GURAUOB_ROLE, GURAUOB_USERID, 
    GURAUOB_ACTIVITY_DATE, GURAUOB_USER_ID, GURAUOB_COMMENTS, GURAUOB_DATA_ORIGIN)
 Values
   (TO_TIMESTAMP('2/26/2019 3:55:01.825935 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'I', 'SSASECT', 'BAN_DEFAULT_M', 'AALSURUR', 
    TO_DATE('02/26/2019 15:55:01', 'MM/DD/YYYY HH24:MI:SS'), 'BANSECR', NULL, NULL);
Insert into GURAUOB
   (GURAUOB_AUDIT_TIME, GURAUOB_AUDIT_ACTION, GURAUOB_OBJECT, GURAUOB_ROLE, GURAUOB_USERID, 
    GURAUOB_ACTIVITY_DATE, GURAUOB_USER_ID, GURAUOB_COMMENTS, GURAUOB_DATA_ORIGIN)
 Values
   (TO_TIMESTAMP('2/19/2019 12:12:37.166637 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'I', 'SSASECT', 'BAN_DEFAULT_M', 'BJALZAHRANI', 
    TO_DATE('02/19/2019 12:12:37', 'MM/DD/YYYY HH24:MI:SS'), 'BANSECR', NULL, NULL);
Insert into GURAUOB
   (GURAUOB_AUDIT_TIME, GURAUOB_AUDIT_ACTION, GURAUOB_OBJECT, GURAUOB_ROLE, GURAUOB_USERID, 
    GURAUOB_ACTIVITY_DATE, GURAUOB_USER_ID, GURAUOB_COMMENTS, GURAUOB_DATA_ORIGIN)
 Values
   (TO_TIMESTAMP('2/27/2019 1:52:59.653976 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'D', 'SSASECT', 'BAN_DEFAULT_M', 'NAMZAHRNI', 
    TO_DATE('02/26/2019 15:48:11', 'MM/DD/YYYY HH24:MI:SS'), 'BANSECR', NULL, NULL);
Insert into GURAUOB
   (GURAUOB_AUDIT_TIME, GURAUOB_AUDIT_ACTION, GURAUOB_OBJECT, GURAUOB_ROLE, GURAUOB_USERID, 
    GURAUOB_ACTIVITY_DATE, GURAUOB_USER_ID, GURAUOB_COMMENTS, GURAUOB_DATA_ORIGIN)
 Values
   (TO_TIMESTAMP('2/27/2019 1:53:48.600016 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'I', 'SSASECT', 'BAN_DEFAULT_M', 'NAMZAHRANI', 
    TO_DATE('02/27/2019 13:53:48', 'MM/DD/YYYY HH24:MI:SS'), 'BANSECR', NULL, NULL);
Insert into GURAUOB
   (GURAUOB_AUDIT_TIME, GURAUOB_AUDIT_ACTION, GURAUOB_OBJECT, GURAUOB_ROLE, GURAUOB_USERID, 
    GURAUOB_ACTIVITY_DATE, GURAUOB_USER_ID, GURAUOB_COMMENTS, GURAUOB_DATA_ORIGIN)
 Values
   (TO_TIMESTAMP('3/7/2019 12:39:29.792225 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'I', 'SSASECT', 'BAN_DEFAULT_M', 'AALGHAMDI', 
    TO_DATE('03/07/2019 12:39:29', 'MM/DD/YYYY HH24:MI:SS'), 'BANSECR', NULL, NULL);
Insert into GURAUOB
   (GURAUOB_AUDIT_TIME, GURAUOB_AUDIT_ACTION, GURAUOB_OBJECT, GURAUOB_ROLE, GURAUOB_USERID, 
    GURAUOB_ACTIVITY_DATE, GURAUOB_USER_ID, GURAUOB_COMMENTS, GURAUOB_DATA_ORIGIN)
 Values
   (TO_TIMESTAMP('2/26/2019 3:48:11.436827 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'I', 'SSASECT', 'BAN_DEFAULT_M', 'NAMZAHRNI', 
    TO_DATE('02/26/2019 15:48:11', 'MM/DD/YYYY HH24:MI:SS'), 'BANSECR', NULL, NULL);
Insert into GURAUOB
   (GURAUOB_AUDIT_TIME, GURAUOB_AUDIT_ACTION, GURAUOB_OBJECT, GURAUOB_ROLE, GURAUOB_USERID, 
    GURAUOB_ACTIVITY_DATE, GURAUOB_USER_ID, GURAUOB_COMMENTS, GURAUOB_DATA_ORIGIN)
 Values
   (TO_TIMESTAMP('2/26/2019 3:50:59.609863 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'I', 'SSASECT', 'BAN_DEFAULT_M', 'NMAALGHAMDI', 
    TO_DATE('02/26/2019 15:50:59', 'MM/DD/YYYY HH24:MI:SS'), 'BANSECR', NULL, NULL);
Insert into GURAUOB
   (GURAUOB_AUDIT_TIME, GURAUOB_AUDIT_ACTION, GURAUOB_OBJECT, GURAUOB_ROLE, GURAUOB_USERID, 
    GURAUOB_ACTIVITY_DATE, GURAUOB_USER_ID, GURAUOB_COMMENTS, GURAUOB_DATA_ORIGIN)
 Values
   (TO_TIMESTAMP('2/26/2019 3:53:15.728899 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'I', 'SSASECT', 'BAN_DEFAULT_M', 'NMALZAHRANI', 
    TO_DATE('02/26/2019 15:53:15', 'MM/DD/YYYY HH24:MI:SS'), 'BANSECR', NULL, NULL);
Insert into GURAUOB
   (GURAUOB_AUDIT_TIME, GURAUOB_AUDIT_ACTION, GURAUOB_OBJECT, GURAUOB_ROLE, GURAUOB_USERID, 
    GURAUOB_ACTIVITY_DATE, GURAUOB_USER_ID, GURAUOB_COMMENTS, GURAUOB_DATA_ORIGIN)
 Values
   (TO_TIMESTAMP('1/7/2019 11:09:24.202464 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'D', 'SSASECT', 'BAN_DEFAULT_M', 'MALKHAZMARI', 
    TO_DATE('11/14/2018 12:11:05', 'MM/DD/YYYY HH24:MI:SS'), 'BU_APPS', NULL, NULL);
Insert into GURAUOB
   (GURAUOB_AUDIT_TIME, GURAUOB_AUDIT_ACTION, GURAUOB_OBJECT, GURAUOB_ROLE, GURAUOB_USERID, 
    GURAUOB_ACTIVITY_DATE, GURAUOB_USER_ID, GURAUOB_COMMENTS, GURAUOB_DATA_ORIGIN)
 Values
   (TO_TIMESTAMP('1/7/2019 11:09:24.205495 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'D', 'SSASECT', 'BAN_DEFAULT_M', 'AALQARNI', 
    TO_DATE('10/14/2018 12:02:17', 'MM/DD/YYYY HH24:MI:SS'), 'BU_APPS', NULL, NULL);
Insert into GURAUOB
   (GURAUOB_AUDIT_TIME, GURAUOB_AUDIT_ACTION, GURAUOB_OBJECT, GURAUOB_ROLE, GURAUOB_USERID, 
    GURAUOB_ACTIVITY_DATE, GURAUOB_USER_ID, GURAUOB_COMMENTS, GURAUOB_DATA_ORIGIN)
 Values
   (TO_TIMESTAMP('1/7/2019 11:09:24.206500 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'D', 'SSASECT', 'BAN_DEFAULT_M', 'AAHAREDY', 
    TO_DATE('11/11/2018 11:09:53', 'MM/DD/YYYY HH24:MI:SS'), 'BU_APPS', NULL, NULL);
Insert into GURAUOB
   (GURAUOB_AUDIT_TIME, GURAUOB_AUDIT_ACTION, GURAUOB_OBJECT, GURAUOB_ROLE, GURAUOB_USERID, 
    GURAUOB_ACTIVITY_DATE, GURAUOB_USER_ID, GURAUOB_COMMENTS, GURAUOB_DATA_ORIGIN)
 Values
   (TO_TIMESTAMP('1/7/2019 11:09:24.206501 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'D', 'SSASECT', 'BAN_DEFAULT_M', 'SALROBAI', 
    TO_DATE('11/12/2018 08:18:21', 'MM/DD/YYYY HH24:MI:SS'), 'BU_APPS', NULL, NULL);
Insert into GURAUOB
   (GURAUOB_AUDIT_TIME, GURAUOB_AUDIT_ACTION, GURAUOB_OBJECT, GURAUOB_ROLE, GURAUOB_USERID, 
    GURAUOB_ACTIVITY_DATE, GURAUOB_USER_ID, GURAUOB_COMMENTS, GURAUOB_DATA_ORIGIN)
 Values
   (TO_TIMESTAMP('1/7/2019 11:09:24.206502 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'D', 'SSASECT', 'BAN_DEFAULT_M', 'EAMADY', 
    TO_DATE('11/12/2018 08:40:55', 'MM/DD/YYYY HH24:MI:SS'), 'BU_APPS', NULL, NULL);
Insert into GURAUOB
   (GURAUOB_AUDIT_TIME, GURAUOB_AUDIT_ACTION, GURAUOB_OBJECT, GURAUOB_ROLE, GURAUOB_USERID, 
    GURAUOB_ACTIVITY_DATE, GURAUOB_USER_ID, GURAUOB_COMMENTS, GURAUOB_DATA_ORIGIN)
 Values
   (TO_TIMESTAMP('1/7/2019 11:09:24.206503 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'D', 'SSASECT', 'BAN_DEFAULT_M', 'MAKEEN', 
    TO_DATE('11/12/2018 09:09:42', 'MM/DD/YYYY HH24:MI:SS'), 'BU_APPS', NULL, NULL);
Insert into GURAUOB
   (GURAUOB_AUDIT_TIME, GURAUOB_AUDIT_ACTION, GURAUOB_OBJECT, GURAUOB_ROLE, GURAUOB_USERID, 
    GURAUOB_ACTIVITY_DATE, GURAUOB_USER_ID, GURAUOB_COMMENTS, GURAUOB_DATA_ORIGIN)
 Values
   (TO_TIMESTAMP('1/7/2019 11:09:24.206504 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'D', 'SSASECT', 'BAN_DEFAULT_M', 'MALTHUOBITI', 
    TO_DATE('11/12/2018 09:13:25', 'MM/DD/YYYY HH24:MI:SS'), 'BU_APPS', NULL, NULL);
Insert into GURAUOB
   (GURAUOB_AUDIT_TIME, GURAUOB_AUDIT_ACTION, GURAUOB_OBJECT, GURAUOB_ROLE, GURAUOB_USERID, 
    GURAUOB_ACTIVITY_DATE, GURAUOB_USER_ID, GURAUOB_COMMENTS, GURAUOB_DATA_ORIGIN)
 Values
   (TO_TIMESTAMP('1/7/2019 11:09:24.207506 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'D', 'SSASECT', 'BAN_DEFAULT_M', 'MAREF', 
    TO_DATE('11/12/2018 09:35:06', 'MM/DD/YYYY HH24:MI:SS'), 'BU_APPS', NULL, NULL);
Insert into GURAUOB
   (GURAUOB_AUDIT_TIME, GURAUOB_AUDIT_ACTION, GURAUOB_OBJECT, GURAUOB_ROLE, GURAUOB_USERID, 
    GURAUOB_ACTIVITY_DATE, GURAUOB_USER_ID, GURAUOB_COMMENTS, GURAUOB_DATA_ORIGIN)
 Values
   (TO_TIMESTAMP('1/7/2019 11:09:24.210528 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'D', 'SSASECT', 'BAN_DEFAULT_M', 'SSALOMARI', 
    TO_DATE('12/03/2018 09:45:01', 'MM/DD/YYYY HH24:MI:SS'), 'BU_APPS', NULL, NULL);
Insert into GURAUOB
   (GURAUOB_AUDIT_TIME, GURAUOB_AUDIT_ACTION, GURAUOB_OBJECT, GURAUOB_ROLE, GURAUOB_USERID, 
    GURAUOB_ACTIVITY_DATE, GURAUOB_USER_ID, GURAUOB_COMMENTS, GURAUOB_DATA_ORIGIN)
 Values
   (TO_TIMESTAMP('1/7/2019 11:09:24.210529 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'D', 'SSASECT', 'BAN_DEFAULT_M', 'AIASA123', 
    TO_DATE('12/09/2018 08:49:19', 'MM/DD/YYYY HH24:MI:SS'), 'BU_APPS', NULL, NULL);
Insert into GURAUOB
   (GURAUOB_AUDIT_TIME, GURAUOB_AUDIT_ACTION, GURAUOB_OBJECT, GURAUOB_ROLE, GURAUOB_USERID, 
    GURAUOB_ACTIVITY_DATE, GURAUOB_USER_ID, GURAUOB_COMMENTS, GURAUOB_DATA_ORIGIN)
 Values
   (TO_TIMESTAMP('1/7/2019 11:09:24.210530 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'D', 'SSASECT', 'BAN_DEFAULT_M', 'RALHARBI', 
    TO_DATE('12/09/2018 08:51:52', 'MM/DD/YYYY HH24:MI:SS'), 'BU_APPS', NULL, NULL);
Insert into GURAUOB
   (GURAUOB_AUDIT_TIME, GURAUOB_AUDIT_ACTION, GURAUOB_OBJECT, GURAUOB_ROLE, GURAUOB_USERID, 
    GURAUOB_ACTIVITY_DATE, GURAUOB_USER_ID, GURAUOB_COMMENTS, GURAUOB_DATA_ORIGIN)
 Values
   (TO_TIMESTAMP('5/22/2019 11:10:12.090622 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'I', 'SSASECT', 'BAN_DEFAULT_M', 'JMALGHAMDI', 
    TO_DATE('05/22/2019 11:10:12', 'MM/DD/YYYY HH24:MI:SS'), 'BANSECR', NULL, NULL);
Insert into GURAUOB
   (GURAUOB_AUDIT_TIME, GURAUOB_AUDIT_ACTION, GURAUOB_OBJECT, GURAUOB_ROLE, GURAUOB_USERID, 
    GURAUOB_ACTIVITY_DATE, GURAUOB_USER_ID, GURAUOB_COMMENTS, GURAUOB_DATA_ORIGIN)
 Values
   (TO_TIMESTAMP('5/19/2019 11:41:38.523616 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'I', 'SSASECT', 'BAN_DEFAULT_M', 'AALQARNI', 
    TO_DATE('05/19/2019 11:41:38', 'MM/DD/YYYY HH24:MI:SS'), 'BANSECR', NULL, NULL);
Insert into GURAUOB
   (GURAUOB_AUDIT_TIME, GURAUOB_AUDIT_ACTION, GURAUOB_OBJECT, GURAUOB_ROLE, GURAUOB_USERID, 
    GURAUOB_ACTIVITY_DATE, GURAUOB_USER_ID, GURAUOB_COMMENTS, GURAUOB_DATA_ORIGIN)
 Values
   (TO_TIMESTAMP('5/19/2019 11:45:55.064618 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'I', 'SSASECT', 'BAN_DEFAULT_M', 'MAALZAHRANI', 
    TO_DATE('05/19/2019 11:45:55', 'MM/DD/YYYY HH24:MI:SS'), 'BANSECR', NULL, NULL);
Insert into GURAUOB
   (GURAUOB_AUDIT_TIME, GURAUOB_AUDIT_ACTION, GURAUOB_OBJECT, GURAUOB_ROLE, GURAUOB_USERID, 
    GURAUOB_ACTIVITY_DATE, GURAUOB_USER_ID, GURAUOB_COMMENTS, GURAUOB_DATA_ORIGIN)
 Values
   (TO_TIMESTAMP('5/19/2019 11:46:55.371619 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'I', 'SSASECT', 'BAN_DEFAULT_M', 'SSMOHAMMED', 
    TO_DATE('05/19/2019 11:46:55', 'MM/DD/YYYY HH24:MI:SS'), 'BANSECR', NULL, NULL);
Insert into GURAUOB
   (GURAUOB_AUDIT_TIME, GURAUOB_AUDIT_ACTION, GURAUOB_OBJECT, GURAUOB_ROLE, GURAUOB_USERID, 
    GURAUOB_ACTIVITY_DATE, GURAUOB_USER_ID, GURAUOB_COMMENTS, GURAUOB_DATA_ORIGIN)
 Values
   (TO_TIMESTAMP('5/19/2019 11:15:22.619601 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'U', 'SSASECT', 'BAN_DEFAULT_M', 'ALKHATHAMI2', 
    TO_DATE('01/24/2018 12:46:17', 'MM/DD/YYYY HH24:MI:SS'), 'BANSECR_ALIALZANDI', NULL, NULL);
Insert into GURAUOB
   (GURAUOB_AUDIT_TIME, GURAUOB_AUDIT_ACTION, GURAUOB_OBJECT, GURAUOB_ROLE, GURAUOB_USERID, 
    GURAUOB_ACTIVITY_DATE, GURAUOB_USER_ID, GURAUOB_COMMENTS, GURAUOB_DATA_ORIGIN)
 Values
   (TO_TIMESTAMP('5/19/2019 11:17:48.129602 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'U', 'SSASECT', 'BAN_DEFAULT_M', 'ALKHATHAMI', 
    TO_DATE('01/24/2018 12:46:17', 'MM/DD/YYYY HH24:MI:SS'), 'BANSECR_ALIALZANDI', NULL, NULL);
Insert into GURAUOB
   (GURAUOB_AUDIT_TIME, GURAUOB_AUDIT_ACTION, GURAUOB_OBJECT, GURAUOB_ROLE, GURAUOB_USERID, 
    GURAUOB_ACTIVITY_DATE, GURAUOB_USER_ID, GURAUOB_COMMENTS, GURAUOB_DATA_ORIGIN)
 Values
   (TO_TIMESTAMP('5/19/2019 11:36:46.343603 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'D', 'SSASECT', 'BAN_DEFAULT_M', 'USER_SECTIONS', 
    TO_DATE('01/27/2009 11:04:16', 'MM/DD/YYYY HH24:MI:SS'), 'BANSECR', NULL, NULL);
Insert into GURAUOB
   (GURAUOB_AUDIT_TIME, GURAUOB_AUDIT_ACTION, GURAUOB_OBJECT, GURAUOB_ROLE, GURAUOB_USERID, 
    GURAUOB_ACTIVITY_DATE, GURAUOB_USER_ID, GURAUOB_COMMENTS, GURAUOB_DATA_ORIGIN)
 Values
   (TO_TIMESTAMP('5/19/2019 11:36:47.971604 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'D', 'SSASECT', 'BAN_DEFAULT_M', 'SNSN1419', 
    TO_DATE('01/02/2018 10:24:12', 'MM/DD/YYYY HH24:MI:SS'), 'BANSECR', NULL, NULL);
Insert into GURAUOB
   (GURAUOB_AUDIT_TIME, GURAUOB_AUDIT_ACTION, GURAUOB_OBJECT, GURAUOB_ROLE, GURAUOB_USERID, 
    GURAUOB_ACTIVITY_DATE, GURAUOB_USER_ID, GURAUOB_COMMENTS, GURAUOB_DATA_ORIGIN)
 Values
   (TO_TIMESTAMP('5/19/2019 11:37:10.269605 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'D', 'SSASECT', 'BAN_DEFAULT_M', 'MWAZAB', 
    TO_DATE('11/15/2018 10:43:58', 'MM/DD/YYYY HH24:MI:SS'), 'BANSECR', NULL, NULL);
Insert into GURAUOB
   (GURAUOB_AUDIT_TIME, GURAUOB_AUDIT_ACTION, GURAUOB_OBJECT, GURAUOB_ROLE, GURAUOB_USERID, 
    GURAUOB_ACTIVITY_DATE, GURAUOB_USER_ID, GURAUOB_COMMENTS, GURAUOB_DATA_ORIGIN)
 Values
   (TO_TIMESTAMP('5/19/2019 11:37:15.227606 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'D', 'SSASECT', 'BAN_DEFAULT_M', 'MABURAS', 
    TO_DATE('01/08/2019 09:34:26', 'MM/DD/YYYY HH24:MI:SS'), 'BANSECR', NULL, NULL);
Insert into GURAUOB
   (GURAUOB_AUDIT_TIME, GURAUOB_AUDIT_ACTION, GURAUOB_OBJECT, GURAUOB_ROLE, GURAUOB_USERID, 
    GURAUOB_ACTIVITY_DATE, GURAUOB_USER_ID, GURAUOB_COMMENTS, GURAUOB_DATA_ORIGIN)
 Values
   (TO_TIMESTAMP('5/19/2019 11:37:22.408607 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'D', 'SSASECT', 'BAN_DEFAULT_M', 'ESSAMALGHAMDI', 
    TO_DATE('01/02/2018 10:12:44', 'MM/DD/YYYY HH24:MI:SS'), 'BANSECR', NULL, NULL);
Insert into GURAUOB
   (GURAUOB_AUDIT_TIME, GURAUOB_AUDIT_ACTION, GURAUOB_OBJECT, GURAUOB_ROLE, GURAUOB_USERID, 
    GURAUOB_ACTIVITY_DATE, GURAUOB_USER_ID, GURAUOB_COMMENTS, GURAUOB_DATA_ORIGIN)
 Values
   (TO_TIMESTAMP('5/19/2019 11:37:24.485608 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'D', 'SSASECT', 'BAN_DEFAULT_M', 'JMALGHAMDI', 
    TO_DATE('11/12/2018 09:10:48', 'MM/DD/YYYY HH24:MI:SS'), 'BANSECR', NULL, NULL);
Insert into GURAUOB
   (GURAUOB_AUDIT_TIME, GURAUOB_AUDIT_ACTION, GURAUOB_OBJECT, GURAUOB_ROLE, GURAUOB_USERID, 
    GURAUOB_ACTIVITY_DATE, GURAUOB_USER_ID, GURAUOB_COMMENTS, GURAUOB_DATA_ORIGIN)
 Values
   (TO_TIMESTAMP('5/19/2019 11:37:33.564609 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'D', 'SSASECT', 'BAN_DEFAULT_M', 'EAMADY', 
    TO_DATE('01/07/2019 11:36:09', 'MM/DD/YYYY HH24:MI:SS'), 'BANSECR', NULL, NULL);
Insert into GURAUOB
   (GURAUOB_AUDIT_TIME, GURAUOB_AUDIT_ACTION, GURAUOB_OBJECT, GURAUOB_ROLE, GURAUOB_USERID, 
    GURAUOB_ACTIVITY_DATE, GURAUOB_USER_ID, GURAUOB_COMMENTS, GURAUOB_DATA_ORIGIN)
 Values
   (TO_TIMESTAMP('5/19/2019 11:37:36.788610 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'D', 'SSASECT', 'BAN_DEFAULT_M', 'BU_VICE_DEAN', 
    TO_DATE('01/07/2019 14:47:05', 'MM/DD/YYYY HH24:MI:SS'), 'BANSECR', NULL, NULL);
Insert into GURAUOB
   (GURAUOB_AUDIT_TIME, GURAUOB_AUDIT_ACTION, GURAUOB_OBJECT, GURAUOB_ROLE, GURAUOB_USERID, 
    GURAUOB_ACTIVITY_DATE, GURAUOB_USER_ID, GURAUOB_COMMENTS, GURAUOB_DATA_ORIGIN)
 Values
   (TO_TIMESTAMP('5/19/2019 11:37:53.380611 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'D', 'SSASECT', 'BAN_DEFAULT_M', 'BAN_STUDENT_C', 
    TO_DATE('09/16/1995 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'BANSECR', NULL, NULL);
Insert into GURAUOB
   (GURAUOB_AUDIT_TIME, GURAUOB_AUDIT_ACTION, GURAUOB_OBJECT, GURAUOB_ROLE, GURAUOB_USERID, 
    GURAUOB_ACTIVITY_DATE, GURAUOB_USER_ID, GURAUOB_COMMENTS, GURAUOB_DATA_ORIGIN)
 Values
   (TO_TIMESTAMP('5/19/2019 11:37:56.291612 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'D', 'SSASECT', 'BAN_DEFAULT_Q', 'BAHA_N_FAC_LOAD_C', 
    TO_DATE('01/28/2012 12:20:38', 'MM/DD/YYYY HH24:MI:SS'), 'BANSECR', NULL, NULL);
Insert into GURAUOB
   (GURAUOB_AUDIT_TIME, GURAUOB_AUDIT_ACTION, GURAUOB_OBJECT, GURAUOB_ROLE, GURAUOB_USERID, 
    GURAUOB_ACTIVITY_DATE, GURAUOB_USER_ID, GURAUOB_COMMENTS, GURAUOB_DATA_ORIGIN)
 Values
   (TO_TIMESTAMP('5/19/2019 11:37:58.918613 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'D', 'SSASECT', 'BAN_DEFAULT_M', 'BAHA_N_SECT1_C', 
    TO_DATE('04/23/2012 09:05:19', 'MM/DD/YYYY HH24:MI:SS'), 'BANSECR', NULL, NULL);
Insert into GURAUOB
   (GURAUOB_AUDIT_TIME, GURAUOB_AUDIT_ACTION, GURAUOB_OBJECT, GURAUOB_ROLE, GURAUOB_USERID, 
    GURAUOB_ACTIVITY_DATE, GURAUOB_USER_ID, GURAUOB_COMMENTS, GURAUOB_DATA_ORIGIN)
 Values
   (TO_TIMESTAMP('5/19/2019 11:38:05.115614 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'D', 'SSASECT', 'BAN_DEFAULT_M', 'BU_SCHEDULE_COORDINATOR', 
    TO_DATE('12/06/2017 14:18:43', 'MM/DD/YYYY HH24:MI:SS'), 'BANSECR', NULL, NULL);
Insert into GURAUOB
   (GURAUOB_AUDIT_TIME, GURAUOB_AUDIT_ACTION, GURAUOB_OBJECT, GURAUOB_ROLE, GURAUOB_USERID, 
    GURAUOB_ACTIVITY_DATE, GURAUOB_USER_ID, GURAUOB_COMMENTS, GURAUOB_DATA_ORIGIN)
 Values
   (TO_TIMESTAMP('5/19/2019 11:38:07.285615 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'D', 'SSASECT', 'BAN_DEFAULT_M', 'BU_SECTIONS', 
    TO_DATE('12/10/2017 12:40:50', 'MM/DD/YYYY HH24:MI:SS'), 'BANSECR', NULL, NULL);
Insert into GURAUOB
   (GURAUOB_AUDIT_TIME, GURAUOB_AUDIT_ACTION, GURAUOB_OBJECT, GURAUOB_ROLE, GURAUOB_USERID, 
    GURAUOB_ACTIVITY_DATE, GURAUOB_USER_ID, GURAUOB_COMMENTS, GURAUOB_DATA_ORIGIN)
 Values
   (TO_TIMESTAMP('8/26/2019 8:15:31.426803 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'I', 'SSASECT', 'BAN_DEFAULT_M', 'MWAZAB', 
    TO_DATE('08/26/2019 08:15:31', 'MM/DD/YYYY HH24:MI:SS'), 'BANSECR', NULL, NULL);
Insert into GURAUOB
   (GURAUOB_AUDIT_TIME, GURAUOB_AUDIT_ACTION, GURAUOB_OBJECT, GURAUOB_ROLE, GURAUOB_USERID, 
    GURAUOB_ACTIVITY_DATE, GURAUOB_USER_ID, GURAUOB_COMMENTS, GURAUOB_DATA_ORIGIN)
 Values
   (TO_TIMESTAMP('8/26/2019 10:49:21.720809 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'I', 'SSASECT', 'BAN_DEFAULT_M', 'BU_VICE_DEAN', 
    TO_DATE('08/26/2019 10:49:21', 'MM/DD/YYYY HH24:MI:SS'), 'BANSECR', NULL, NULL);
Insert into GURAUOB
   (GURAUOB_AUDIT_TIME, GURAUOB_AUDIT_ACTION, GURAUOB_OBJECT, GURAUOB_ROLE, GURAUOB_USERID, 
    GURAUOB_ACTIVITY_DATE, GURAUOB_USER_ID, GURAUOB_COMMENTS, GURAUOB_DATA_ORIGIN)
 Values
   (TO_TIMESTAMP('8/27/2019 1:22:10.656814 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'I', 'SSASECT', 'BAN_DEFAULT_M', 'SAMIALGHAMDI', 
    TO_DATE('08/27/2019 13:22:10', 'MM/DD/YYYY HH24:MI:SS'), 'BANSECR', NULL, NULL);
Insert into GURAUOB
   (GURAUOB_AUDIT_TIME, GURAUOB_AUDIT_ACTION, GURAUOB_OBJECT, GURAUOB_ROLE, GURAUOB_USERID, 
    GURAUOB_ACTIVITY_DATE, GURAUOB_USER_ID, GURAUOB_COMMENTS, GURAUOB_DATA_ORIGIN)
 Values
   (TO_TIMESTAMP('8/27/2019 1:24:05.082819 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'D', 'SSASECT', 'BAN_DEFAULT_M', 'SAMIALGHAMDI', 
    TO_DATE('08/27/2019 13:22:10', 'MM/DD/YYYY HH24:MI:SS'), 'BANSECR', NULL, NULL);
Insert into GURAUOB
   (GURAUOB_AUDIT_TIME, GURAUOB_AUDIT_ACTION, GURAUOB_OBJECT, GURAUOB_ROLE, GURAUOB_USERID, 
    GURAUOB_ACTIVITY_DATE, GURAUOB_USER_ID, GURAUOB_COMMENTS, GURAUOB_DATA_ORIGIN)
 Values
   (TO_TIMESTAMP('1/7/2020 8:29:26.150202 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'D', 'SSASECT', 'BAN_DEFAULT_M', 'BU_VICE_DEAN', 
    TO_DATE('08/26/2019 10:49:21', 'MM/DD/YYYY HH24:MI:SS'), 'BANSECR', NULL, NULL);
Insert into GURAUOB
   (GURAUOB_AUDIT_TIME, GURAUOB_AUDIT_ACTION, GURAUOB_OBJECT, GURAUOB_ROLE, GURAUOB_USERID, 
    GURAUOB_ACTIVITY_DATE, GURAUOB_USER_ID, GURAUOB_COMMENTS, GURAUOB_DATA_ORIGIN)
 Values
   (TO_TIMESTAMP('8/4/2019 5:39:42.919403 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'I', 'SSASECT', 'BAN_DEFAULT_M', 'SSALOMARI', 
    TO_DATE('08/04/2019 05:39:42', 'MM/DD/YYYY HH24:MI:SS'), 'BANSECR_KOALGHAMDI', NULL, NULL);
Insert into GURAUOB
   (GURAUOB_AUDIT_TIME, GURAUOB_AUDIT_ACTION, GURAUOB_OBJECT, GURAUOB_ROLE, GURAUOB_USERID, 
    GURAUOB_ACTIVITY_DATE, GURAUOB_USER_ID, GURAUOB_COMMENTS, GURAUOB_DATA_ORIGIN)
 Values
   (TO_TIMESTAMP('5/26/2019 2:24:03.015801 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'I', 'SSASECT', 'BAN_DEFAULT_M', 'SALROBAI', 
    TO_DATE('05/26/2019 14:24:02', 'MM/DD/YYYY HH24:MI:SS'), 'BANSECR', NULL, NULL);
Insert into GURAUOB
   (GURAUOB_AUDIT_TIME, GURAUOB_AUDIT_ACTION, GURAUOB_OBJECT, GURAUOB_ROLE, GURAUOB_USERID, 
    GURAUOB_ACTIVITY_DATE, GURAUOB_USER_ID, GURAUOB_COMMENTS, GURAUOB_DATA_ORIGIN)
 Values
   (TO_TIMESTAMP('5/28/2019 12:35:40.036803 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'I', 'SSASECT', 'BAN_DEFAULT_M', 'SAISUSR', 
    TO_DATE('05/28/2019 12:35:40', 'MM/DD/YYYY HH24:MI:SS'), 'BANSECR', NULL, NULL);
Insert into GURAUOB
   (GURAUOB_AUDIT_TIME, GURAUOB_AUDIT_ACTION, GURAUOB_OBJECT, GURAUOB_ROLE, GURAUOB_USERID, 
    GURAUOB_ACTIVITY_DATE, GURAUOB_USER_ID, GURAUOB_COMMENTS, GURAUOB_DATA_ORIGIN)
 Values
   (TO_TIMESTAMP('8/26/2019 10:46:43.111805 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'I', 'SSASECT', 'BAN_DEFAULT_M', 'RALHARBI', 
    TO_DATE('08/26/2019 10:46:43', 'MM/DD/YYYY HH24:MI:SS'), 'BANSECR_KOALGHAMDI', NULL, NULL);
Insert into GURAUOB
   (GURAUOB_AUDIT_TIME, GURAUOB_AUDIT_ACTION, GURAUOB_OBJECT, GURAUOB_ROLE, GURAUOB_USERID, 
    GURAUOB_ACTIVITY_DATE, GURAUOB_USER_ID, GURAUOB_COMMENTS, GURAUOB_DATA_ORIGIN)
 Values
   (TO_TIMESTAMP('8/26/2019 10:47:47.174806 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'I', 'SSASECT', 'BAN_DEFAULT_M', 'MAKEEN', 
    TO_DATE('08/26/2019 10:47:47', 'MM/DD/YYYY HH24:MI:SS'), 'BANSECR_KOALGHAMDI', NULL, NULL);
Insert into GURAUOB
   (GURAUOB_AUDIT_TIME, GURAUOB_AUDIT_ACTION, GURAUOB_OBJECT, GURAUOB_ROLE, GURAUOB_USERID, 
    GURAUOB_ACTIVITY_DATE, GURAUOB_USER_ID, GURAUOB_COMMENTS, GURAUOB_DATA_ORIGIN)
 Values
   (TO_TIMESTAMP('8/26/2019 10:48:10.483807 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'I', 'SSASECT', 'BAN_DEFAULT_M', 'AAHAREDY', 
    TO_DATE('08/26/2019 10:48:10', 'MM/DD/YYYY HH24:MI:SS'), 'BANSECR_KOALGHAMDI', NULL, NULL);
Insert into GURAUOB
   (GURAUOB_AUDIT_TIME, GURAUOB_AUDIT_ACTION, GURAUOB_OBJECT, GURAUOB_ROLE, GURAUOB_USERID, 
    GURAUOB_ACTIVITY_DATE, GURAUOB_USER_ID, GURAUOB_COMMENTS, GURAUOB_DATA_ORIGIN)
 Values
   (TO_TIMESTAMP('8/26/2019 10:48:44.356808 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'I', 'SSASECT', 'BAN_DEFAULT_M', 'AIASA123', 
    TO_DATE('08/26/2019 10:48:44', 'MM/DD/YYYY HH24:MI:SS'), 'BANSECR_KOALGHAMDI', NULL, NULL);
Insert into GURAUOB
   (GURAUOB_AUDIT_TIME, GURAUOB_AUDIT_ACTION, GURAUOB_OBJECT, GURAUOB_ROLE, GURAUOB_USERID, 
    GURAUOB_ACTIVITY_DATE, GURAUOB_USER_ID, GURAUOB_COMMENTS, GURAUOB_DATA_ORIGIN)
 Values
   (TO_TIMESTAMP('8/26/2019 10:49:52.186810 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'I', 'SSASECT', 'BAN_DEFAULT_M', 'MALMANAH', 
    TO_DATE('08/26/2019 10:49:52', 'MM/DD/YYYY HH24:MI:SS'), 'BANSECR_KOALGHAMDI', NULL, NULL);
Insert into GURAUOB
   (GURAUOB_AUDIT_TIME, GURAUOB_AUDIT_ACTION, GURAUOB_OBJECT, GURAUOB_ROLE, GURAUOB_USERID, 
    GURAUOB_ACTIVITY_DATE, GURAUOB_USER_ID, GURAUOB_COMMENTS, GURAUOB_DATA_ORIGIN)
 Values
   (TO_TIMESTAMP('8/26/2019 10:51:19.956811 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'I', 'SSASECT', 'BAN_DEFAULT_M', 'MALTHUOBITI', 
    TO_DATE('08/26/2019 10:51:19', 'MM/DD/YYYY HH24:MI:SS'), 'BANSECR_KOALGHAMDI', NULL, NULL);
COMMIT;
