/* Formatted on 10/31/2019 9:48:40 AM (QP5 v5.227.12220.39754) */



SELECT  DISTINCT SMRACAA_TERM_CODE_EFF ,SOBCURR_COLL_CODE ,f_get_desc_fnc('STVCOLL' ,SOBCURR_COLL_CODE  , 30  ) coll_desc, SORCMJR_DEPT_CODE,f_get_desc_fnc('STVDEPT' ,SORCMJR_DEPT_CODE  , 30  ) DEPT_DESC,SOBCURR_PROGRAM ,SMRPAAP_AREA ,
       SMRACAA_SUBJ_CODE || SMRACAA_CRSE_NUMB_LOW course_code ,SCBCRSE_TITLE
  FROM SMRACAA, SMBAGEN ,SMRPAAP ,SOBCURR ,SORCMJR,SCBCRSE
 WHERE     SMRACAA_TERM_CODE_EFF = '143810'
       AND SMBAGEN_AREA = SMRACAA_AREA
       AND SMBAGEN_TERM_CODE_EFF = SMRACAA_TERM_CODE_EFF
       AND SOBCURR_COLL_CODE NOT IN ('17','19','42','18')
       AND SMRPAAP_AREA=SMRACAA_AREA
       AND SMRPAAP_TERM_CODE_EFF=SMRACAA_TERM_CODE_EFF
       AND SOBCURR_PROGRAM=SMRPAAP_PROGRAM
       AND SOBCURR_PROGRAM LIKE '1%'
       AND SMBAGEN_ACTIVE_IND = 'Y'
       --AND SORCMJR_TERM_CODE_EFF='144010'
       AND SORCMJR_CURR_RULE(+)=SOBCURR_CURR_RULE
       AND SCBCRSE_SUBJ_CODE||SCBCRSE_CRSE_NUMB =SMRACAA_SUBJ_CODE || SMRACAA_CRSE_NUMB_LOW 
       AND SCBCRSE_EFF_TERM=(SELECT MAX(SCBCRSE_EFF_TERM) FROM SCBCRSE WHERE  SCBCRSE_SUBJ_CODE||SCBCRSE_CRSE_NUMB =SMRACAA_SUBJ_CODE || SMRACAA_CRSE_NUMB_LOW )
       AND SMRACAA_SUBJ_CODE || SMRACAA_CRSE_NUMB_LOW IN 

(SELECT   
       DISTINCT SMRACAA_SUBJ_CODE || SMRACAA_CRSE_NUMB_LOW course_code  
  FROM SMRACAA, SMBAGEN ,SMRPAAP ,SOBCURR
 WHERE     SMRACAA_TERM_CODE_EFF = '143810'
       AND SMBAGEN_AREA = SMRACAA_AREA
       AND SMBAGEN_TERM_CODE_EFF = SMRACAA_TERM_CODE_EFF
       AND SOBCURR_COLL_CODE NOT IN ('17','19','42','18')
       AND SMRPAAP_AREA=SMRACAA_AREA
       AND SMRPAAP_TERM_CODE_EFF=SMRACAA_TERM_CODE_EFF
       AND SOBCURR_PROGRAM=SMRPAAP_PROGRAM
         AND SOBCURR_PROGRAM LIKE '1%'
       AND SMBAGEN_ACTIVE_IND = 'Y'
       AND SMRACAA_SUBJ_CODE||SMRACAA_CRSE_NUMB_LOW='41021268'
       GROUP BY SMRACAA_SUBJ_CODE || SMRACAA_CRSE_NUMB_LOW 
       HAVING COUNT(SMRACAA_SUBJ_CODE || SMRACAA_CRSE_NUMB_LOW )>1 )
       
       ORDER BY course_code ,SOBCURR_COLL_CODE,SMRPAAP_AREA
       
       ;