SELECT B.SPRIDEN_ID ,LENGTH (SPRIDEN_LAST_NAME) ,LENGTH (SPRIDEN_FIRST_NAME),LENGTH (SPRIDEN_MI),COL04
,SUBSTR(COL04,1,INSTR(COL04,' ',1,2)),LENGTH(SUBSTR(COL04,1,INSTR(COL04,' ',1,2)))+LENGTH (SPRIDEN_MI)
,SUBSTR(COL04,INSTR(COL04,' ',1,2)+1)
FROM SPRIDEN A ,BU_DEV.JAMEE_SPRIDEN_WRONG1 B
WHERE A.SPRIDEN_ID=B.SPRIDEN_ID
AND SPRIDEN_CHANGE_IND IS NULL
AND LENGTH (SPRIDEN_LAST_NAME)>30
--AND LENGTH(SUBSTR(COL04,1,INSTR(COL04,' ',1,2)))+LENGTH (SPRIDEN_MI)+1>30
--AND LENGTH(SUBSTR(COL04,INSTR(COL04,' ',1,2)+1))>30
;
SELECT * FROM BU_DEV.JAMEE_SPRIDEN_WRONG1 ;

UPDATE SPRIDEN A
SET SPRIDEN_LAST_NAME=(SELECT SUBSTR(COL04,INSTR(COL04,' ',1,2)+1) FROM BU_DEV.JAMEE_SPRIDEN_WRONG1 B WHERE A.SPRIDEN_ID=B.SPRIDEN_ID)
,SPRIDEN_MI=SPRIDEN_MI||' '||(SELECT SUBSTR(COL04,1,INSTR(COL04,' ',1,2))FROM BU_DEV.JAMEE_SPRIDEN_WRONG1 B WHERE A.SPRIDEN_ID=B.SPRIDEN_ID )
WHERE SPRIDEN_CHANGE_IND IS NULL
AND LENGTH (SPRIDEN_LAST_NAME)>30
AND A.SPRIDEN_ID IN (SELECT SPRIDEN_ID FROM BU_DEV.JAMEE_SPRIDEN_WRONG1 );


CREATE TABLE BU_DEV.SPRIDEN_BACKUP22_04_2021 AS SELECT * FROM SPRIDEN A 
WHERE SPRIDEN_CHANGE_IND IS NULL
AND LENGTH (SPRIDEN_LAST_NAME)>30
AND A.SPRIDEN_ID IN (SELECT SPRIDEN_ID FROM BU_DEV.JAMEE_SPRIDEN_WRONG1 ) ;



;

