 
Insert into SSRRTST
   (SSRRTST_TERM_CODE, SSRRTST_CRN, SSRRTST_SEQNO, SSRRTST_TESC_CODE, SSRRTST_TEST_SCORE, 
    SSRRTST_SUBJ_CODE_PREQ, SSRRTST_CRSE_NUMB_PREQ, SSRRTST_LEVL_CODE, SSRRTST_MIN_GRDE, SSRRTST_CONCURRENCY_IND, 
    SSRRTST_CONNECTOR, SSRRTST_LPAREN, SSRRTST_RPAREN, SSRRTST_ACTIVITY_DATE)
 Values
   ('144030', '30590', 2, NULL, NULL, 
    '1501', '1318', 'Ã„', 'œ', NULL, 
    NULL, NULL, NULL, TO_DATE('05/14/2020 17:01:14', 'MM/DD/YYYY HH24:MI:SS'));
Insert into SSRRTST
   (SSRRTST_TERM_CODE, SSRRTST_CRN, SSRRTST_SEQNO, SSRRTST_TESC_CODE, SSRRTST_TEST_SCORE, 
    SSRRTST_SUBJ_CODE_PREQ, SSRRTST_CRSE_NUMB_PREQ, SSRRTST_LEVL_CODE, SSRRTST_MIN_GRDE, SSRRTST_CONCURRENCY_IND, 
    SSRRTST_CONNECTOR, SSRRTST_LPAREN, SSRRTST_RPAREN, SSRRTST_ACTIVITY_DATE)
 Values
   ('144030', '30590', 4, NULL, NULL, 
    '1707', '3602', 'Ã„', 'œ', NULL, 
    'O', NULL, NULL, TO_DATE('05/22/2020 20:31:32', 'MM/DD/YYYY HH24:MI:SS'));
Insert into SSRRTST
   (SSRRTST_TERM_CODE, SSRRTST_CRN, SSRRTST_SEQNO, SSRRTST_TESC_CODE, SSRRTST_TEST_SCORE, 
    SSRRTST_SUBJ_CODE_PREQ, SSRRTST_CRSE_NUMB_PREQ, SSRRTST_LEVL_CODE, SSRRTST_MIN_GRDE, SSRRTST_CONCURRENCY_IND, 
    SSRRTST_CONNECTOR, SSRRTST_LPAREN, SSRRTST_RPAREN, SSRRTST_ACTIVITY_DATE)
 Values
   ('144030', '30590', 6, NULL, NULL, 
    '1909', '1301', 'Ã„', 'œ', NULL, 
    'O', NULL, NULL, TO_DATE('05/22/2020 20:31:32', 'MM/DD/YYYY HH24:MI:SS'));
 
 
Insert into SSRRTST
   (SSRRTST_TERM_CODE, SSRRTST_CRN, SSRRTST_SEQNO, SSRRTST_TESC_CODE, SSRRTST_TEST_SCORE, 
    SSRRTST_SUBJ_CODE_PREQ, SSRRTST_CRSE_NUMB_PREQ, SSRRTST_LEVL_CODE, SSRRTST_MIN_GRDE, SSRRTST_CONCURRENCY_IND, 
    SSRRTST_CONNECTOR, SSRRTST_LPAREN, SSRRTST_RPAREN, SSRRTST_ACTIVITY_DATE)
 Values
   ('144030', '30419', 2, NULL, NULL, 
    '1806', '1210', 'Ã„', 'œ', NULL, 
    NULL, NULL, NULL, TO_DATE('05/14/2020 17:01:13', 'MM/DD/YYYY HH24:MI:SS'));
Insert into SSRRTST
   (SSRRTST_TERM_CODE, SSRRTST_CRN, SSRRTST_SEQNO, SSRRTST_TESC_CODE, SSRRTST_TEST_SCORE, 
    SSRRTST_SUBJ_CODE_PREQ, SSRRTST_CRSE_NUMB_PREQ, SSRRTST_LEVL_CODE, SSRRTST_MIN_GRDE, SSRRTST_CONCURRENCY_IND, 
    SSRRTST_CONNECTOR, SSRRTST_LPAREN, SSRRTST_RPAREN, SSRRTST_ACTIVITY_DATE)
 Values
   ('144030', '30419', 3, NULL, NULL, 
    '4202', '1204', 'Ã„', 'œ', NULL, 
    'O', NULL, NULL, TO_DATE('05/18/2020 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into SSRRTST
   (SSRRTST_TERM_CODE, SSRRTST_CRN, SSRRTST_SEQNO, SSRRTST_TESC_CODE, SSRRTST_TEST_SCORE, 
    SSRRTST_SUBJ_CODE_PREQ, SSRRTST_CRSE_NUMB_PREQ, SSRRTST_LEVL_CODE, SSRRTST_MIN_GRDE, SSRRTST_CONCURRENCY_IND, 
    SSRRTST_CONNECTOR, SSRRTST_LPAREN, SSRRTST_RPAREN, SSRRTST_ACTIVITY_DATE)
 Values
   ('144030', '30419', 4, NULL, NULL, 
    '4202', '1214', 'Ã„', 'œ', NULL, 
    'O', NULL, NULL, TO_DATE('05/18/2020 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
 
