
update bu_dev.tmp_tbl03 set COL02=f_get_pidm(trim(COL01))

select distinct COL02 from bu_dev.tmp_tbl03
WHERE  COL02 IS NOT NULL

Insert into GLBSLCT
   (GLBSLCT_APPLICATION, GLBSLCT_SELECTION, GLBSLCT_CREATOR_ID, GLBSLCT_DESC, GLBSLCT_LOCK_IND, 
    GLBSLCT_ACTIVITY_DATE, GLBSLCT_TYPE_IND)
 Values
   ('STUDENT', 'DEG_MOGAHED06FEB19', 'SAISUSR', 'ÿ·»…  Œ—ÌÃ', 'N', 
    SYSDATE, NULL);
 
 
Insert into GLBEXTR
   SELECT 'STUDENT', 'DEG_MOGAHED06FEB19', 'SAISUSR', 'SAISUSR', PIDM, 
    SYSDATE, 'S', NULL  FROM 
(  SELECT DISTINCT COL02 PIDM
FROM bu_dev.tmp_tbl03
WHERE COL02 IS NOT NULL )
  