/* Formatted on 4/22/2020 2:34:11 PM (QP5 v5.354) */
DROP TABLE CAPP_MNPL_LOG_MAIN;

CREATE TABLE CAPP_MNPL_LOG_MAIN
(
    PROCESS_ID                     NUMBER (8),
    PROCESS_PURPOSE_IND            CHAR (1 CHAR),
    RUNNING_DATE                   DATE,
    USER_ID                        VARCHAR2 (20 CHAR),
    PROCESS_TERMINATION_STATUS     VARCHAR2 (20 CHAR),
    PROCESS_TERMINATION_MESSAGE    VARCHAR2 (400)
);

ALTER TABLE BU_APPS.CAPP_MNPL_LOG_MAIN
    ADD CONSTRAINT CAPP_MNPL_LOG_MAIN_PK PRIMARY KEY (PROCESS_ID);

CREATE PUBLIC SYNONYM CAPP_MNPL_LOG_MAIN FOR BU_APPS.CAPP_MNPL_LOG_MAIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON BU_APPS.CAPP_MNPL_LOG_MAIN TO PUBLIC;


-------------

CREATE TABLE CAPP_MNPL_LOG_HEADER
(
    PROCESS_ID              NUMBER (8),
    STD_PIDM                NUMBER (8),
    TOTAL_PROCESSED_CRSE    NUMBER (3),
    TOAL_PROCESSED_HRS      NUMBER (3)
);

ALTER TABLE BU_APPS.CAPP_MNPL_LOG_HEADER
    ADD CONSTRAINT CAPP_MNPL_LOG_HEADER_PK PRIMARY KEY (PROCESS_ID, STD_PIDM);


CREATE PUBLIC SYNONYM CAPP_MNPL_LOG_HEADER FOR BU_APPS.CAPP_MNPL_LOG_HEADER;
GRANT SELECT, INSERT, UPDATE, DELETE
    ON BU_APPS.CAPP_MNPL_LOG_HEADER
    TO PUBLIC;
    ----------------------------***
DROP TABLE CAPP_MNPL_LOG_DETAIL;

CREATE TABLE CAPP_MNPL_LOG_DETAIL
(
    PROCESS_ID             NUMBER (8),
    STD_PIDM               NUMBER (8),
    SEQNO                  NUMBER (6),
    LHS_SUBJ_CODE          VARCHAR2 (4),
    LHS_CRSE_NUMB          VARCHAR2 (5),
    LHS_CREDIT_HR          NUMBER (3),
    REQUIRED_IND           CHAR,
    RHS_SUBJ_CODE          VARCHAR2 (4),
    RHS_CRSE_NUMB          VARCHAR2 (5),
    RHS_SEQNO              NUMBER,
    RHS_EQVLNT_HR          NUMBER (3),
    MAPPING_SUCCESS_IND    CHAR,
    DATA_TARGET            VARCHAR2 (150),
    GRDE_CODE_FINAL        VARCHAR (4),
    FAILURE_MESSAGE        VARCHAR2 (250)
);

ALTER TABLE BU_APPS.CAPP_MNPL_LOG_DETAIL
    ADD CONSTRAINT CAPP_MNPL_LOG_DETAIL_PK PRIMARY KEY
            (PROCESS_ID, STD_PIDM, SEQNO);

CREATE PUBLIC SYNONYM CAPP_MNPL_LOG_DETAIL FOR BU_APPS.CAPP_MNPL_LOG_DETAIL;
GRANT SELECT, INSERT, UPDATE, DELETE
    ON BU_APPS.CAPP_MNPL_LOG_DETAIL
    TO PUBLIC;

    --- not used
DROP TABLE CAPP_MNPL_LOG_NOT_USED;

CREATE TABLE CAPP_MNPL_LOG_NOT_USED
(
    PROCESS_ID         NUMBER (8),
    STD_PIDM           NUMBER (8),
    SEQNO              NUMBER (6),
    SUBJ_CODE          VARCHAR2 (4),
    CRSE_NUMB          VARCHAR2 (5),
    TITLE              VARCHAR2 (30),
    GRDE_CODE_FINAL    VARCHAR (4)
);

ALTER TABLE BU_APPS.CAPP_MNPL_LOG_NOT_USED
    ADD CONSTRAINT CAPP_MNPL_LOG_NOT_USED_PK PRIMARY KEY
            (PROCESS_ID, STD_PIDM, SEQNO);

CREATE PUBLIC SYNONYM CAPP_MNPL_LOG_NOT_USED FOR BU_APPS.CAPP_MNPL_LOG_NOT_USED;
GRANT SELECT, INSERT, UPDATE, DELETE
    ON BU_APPS.CAPP_MNPL_LOG_NOT_USED
    TO PUBLIC;