 
CREATE VIEW CAPP_COURSES_VW AS 
SELECT SMBPGEN_PROGRAM,
       SMBPGEN_TERM_CODE_EFF,
       SMRPRLE_PROGRAM_DESC,
       SMBPGEN_REQ_CREDITS_OVERALL,
       SMBPGEN_REQ_COURSES_OVERALL,
       SMRPAAP_AREA_PRIORITY,
       SMRACAA_AREA,
       SMRALIB_area_desc,
       SMRPAAP_AREA,
       SMBAGEN_REQ_CREDITS_OVERALL,
       SMBAGEN_REQ_COURSES_OVERALL,
       CASE WHEN SMRACAA_RULE IS NULL THEN 'Y' ELSE 'N' END
           REQUIRED_FLAG,
       SMRACAA_SUBJ_CODE,
       SMRACAA_CRSE_NUMB_LOW,
       (SELECT a.scbcrse_title
          FROM scbcrse a
         WHERE     a.scbcrse_subj_code = SMRACAA_SUBJ_CODE
               AND a.scbcrse_crse_numb = SMRACAA_CRSE_NUMB_LOW
               AND SCBCRSE_EFF_TERM =
                   (SELECT MAX (SCBCRSE_EFF_TERM)
                      FROM scbcrse
                     WHERE     scbcrse_subj_code = SMRACAA_SUBJ_CODE
                           AND scbcrse_crse_numb = SMRACAA_CRSE_NUMB_LOW
                           AND SCBCRSE_EFF_TERM <= SMBPGEN_TERM_CODE_EFF))
           title,
       SMRACAA_RULE
  FROM smbpgen  a,
       smrpaap,
       smracaa,
       SMBAGEN,
       SMRALIB,
       SMRPRLE
 WHERE     SMBPGEN_PROGRAM || SMBPGEN_TERM_CODE_EFF =
           SMRPAAP_PROGRAM || SMRPAAP_TERM_CODE_EFF
       AND SMRPRLE.SMRPRLE_PROGRAM = SMBPGEN_PROGRAM
       AND SMBAGEN_AREA || SMBAGEN_TERM_CODE_EFF =
           SMRPAAP_AREA || SMRPAAP_TERM_CODE_EFF
       AND SMRPAAP_AREA || SMRPAAP_TERM_CODE_EFF =
           SMRACAA_AREA || SMRACAA_TERM_CODE_EFF
       AND SMRALIB_area = SMBAGEN_AREA
       AND SMRACAA_SUBJ_CODE IS NOT NULL
       AND SMRACAA_CRSE_NUMB_LOW IS NOT NULL
UNION
SELECT SMBPGEN_PROGRAM,
       SMBPGEN_TERM_CODE_EFF,
       SMRPRLE_PROGRAM_DESC,
       SMBPGEN_REQ_CREDITS_OVERALL,
       SMBPGEN_REQ_COURSES_OVERALL,
       SMRPAAP_AREA_PRIORITY,
       SMRACAA_AREA,
       SMRALIB_area_desc,
       SMRPAAP_AREA,
       SMBAGEN_REQ_CREDITS_OVERALL,
       SMBAGEN_REQ_COURSES_OVERALL,
       CASE WHEN SMRACAA_RULE IS NULL THEN 'Y' ELSE 'N' END
           REQUIRED_FLAG,
       SMRARUL_SUBJ_CODE,
       SMRARUL_CRSE_NUMB_LOW,
       (SELECT a.scbcrse_title
          FROM scbcrse a
         WHERE     a.scbcrse_subj_code = SMRARUL_SUBJ_CODE
               AND a.scbcrse_crse_numb = SMRARUL_CRSE_NUMB_LOW
               AND SCBCRSE_EFF_TERM =
                   (SELECT MAX (SCBCRSE_EFF_TERM)
                      FROM scbcrse
                     WHERE     scbcrse_subj_code = SMRARUL_SUBJ_CODE
                           AND scbcrse_crse_numb = SMRARUL_CRSE_NUMB_LOW
                           AND SCBCRSE_EFF_TERM <= SMBPGEN_TERM_CODE_EFF))
           title,
       SMRACAA_RULE
  FROM smbpgen  a,
       smrpaap,
       smracaa,
       SMBAGEN,
       SMRALIB,
       SMRPRLE,
       SMRARUL
 WHERE     SMBPGEN_PROGRAM || SMBPGEN_TERM_CODE_EFF =
           SMRPAAP_PROGRAM || SMRPAAP_TERM_CODE_EFF
       AND SMRPRLE.SMRPRLE_PROGRAM = SMBPGEN_PROGRAM
       AND SMBAGEN_AREA || SMBAGEN_TERM_CODE_EFF =
           SMRPAAP_AREA || SMRPAAP_TERM_CODE_EFF
       AND SMRPAAP_AREA || SMRPAAP_TERM_CODE_EFF =
           SMRACAA_AREA || SMRACAA_TERM_CODE_EFF
       AND SMRALIB_area = SMBAGEN_AREA
       AND SMRARUL_KEY_RULE || SMRARUL_AREA = SMRACAA_RULE || SMRACAA_AREA
ORDER BY
    SMBPGEN_PROGRAM,
    SMRACAA_AREA,
    SMRALIB_AREA_DESC,
    SMRPAAP_AREA_PRIORITY,
    SMRACAA_SUBJ_CODE,
    SMRACAA_CRSE_NUMB_LOW 