UPDATE   WF_REQUEST_FLOW A  SET A.NOTES='Ì—ÃÏ „—«Ã⁄… ﬁ”„ «·„·›«  »ﬂ·Ì… «·⁄·Ê„ ·«” ·«„ «·„·› Ê≈‰Â«¡ «·„⁄«„·…'
WHERE EXISTS (SELECT '1' FROM REQUEST_MASTER WHERE REQUEST_NO=A.REQUEST_NO 
AND  OBJECT_CODE in ('WF_CLEARANCE','WF_UN_WITHDRAW'))
AND A.ROLE_CODE='RO_DAR_AUDITOR'
AND A.ACTION_CODE='APPROVE'
AND A.NOTES IS NULL 