 
  SELECT  A.REQUEST_NO  AS "Request#",F_GET_STD_NAME(A.REQUESTER_PIDM) AS "Student Name" , A.REQUEST_DATE , DECODE(A.REQUEST_STATUS , 'P','Pending','R','Rejected','C','Completely Approved')REQUEST_STATUS ,WF_RQST_ITEMS (B.REQUEST_NO, 'REASON') Reason ,
         WF_RQST_ITEMS (B.REQUEST_NO, 'DEPARTMENT_CODE') AS "Department Code",
         STVDEPT_DESC AS "Department",
         WF_RQST_ITEMS (B.REQUEST_NO, 'CRN') AS "CRN",
         C.SCBCRSE_TITLE,
         WF_WITHDRAW_COURSE.GET_INSTRUCTOR_NAME (
            WF_RQST_ITEMS (B.REQUEST_NO, 'CRN'))
            AS "Instructor"
    FROM REQUEST_MASTER A,
         WF_REQUEST_FLOW B,
         STVDEPT D,
         SSBSECT S,
         SCBCRSE C
   WHERE     A.REQUEST_NO = B.REQUEST_NO
         AND A.OBJECT_CODE = 'WF_WITHDRAW_COURSE'
         AND B.SEQUENCE_NO = 1
         AND WF_RQST_ITEMS (B.REQUEST_NO, 'COLLEGE_CODE') = '16'
         AND D.STVDEPT_CODE = WF_RQST_ITEMS (B.REQUEST_NO, 'DEPARTMENT_CODE')
         AND S.SSBSECT_CRN = WF_RQST_ITEMS (B.REQUEST_NO, 'CRN')
         AND S.SSBSECT_TERM_CODE = '143920'
         AND S.SSBSECT_SUBJ_CODE = C.SCBCRSE_SUBJ_CODE
         AND S.SSBSECT_CRSE_NUMB = C.SCBCRSE_CRSE_NUMB
         AND C.SCBCRSE_EFF_TERM =
                (SELECT MAX (SCBCRSE_EFF_TERM)
                   FROM SCBCRSE
                  WHERE     SCBCRSE_SUBJ_CODE = C.SCBCRSE_SUBJ_CODE
                        AND SCBCRSE_CRSE_NUMB = C.SCBCRSE_CRSE_NUMB
                        AND SCBCRSE_EFF_TERM <= '143920')
 
ORDER BY 1  ,
         2 
          