/* Formatted on 1/31/2019 3:01:09 PM (QP5 v5.227.12220.39754) */
  SELECT SGBSTDN_BLCK_CODE,
         COUNT (SGBSTDN_BLCK_CODE),
         ROUND (COUNT (SGBSTDN_BLCK_CODE) / 2)
    FROM SGBSTDN A
   WHERE     SGBSTDN_TERM_CODE_EFF =
                (SELECT MAX (B.SGBSTDN_TERM_CODE_EFF)
                   FROM SGBSTDN B
                  WHERE     SGBSTDN_TERM_CODE_EFF <= '143920'
                        AND B.SGBSTDN_PIDM = A.SGBSTDN_PIDM)
         AND A.SGBSTDN_BLCK_CODE IN ('C1', 'C2', 'O1', 'O2')
GROUP BY SGBSTDN_BLCK_CODE;