/* Formatted on 4/5/2020 5:46:07 PM (QP5 v5.354) */
CREATE TABLE SYVPRDF
(
    SYVPRDF_PROGRAM          VARCHAR2 (12),
    SYVPRDF_TERM_CODE_EFF    VARCHAR2 (6),
    SYVPRDF_RULE_CODE        VARCHAR2 (20) NOT NULL,
    SYVPRDF_ACTIVE_IND       CHAR,
    SYVPRDF_ACTIVITY_DATE    DATE,
    SYVPRDF_USER_ID          VARCHAR2 (30)
);

ALTER TABLE SYVPRDF
    ADD CONSTRAINT SYVPRDF_PK PRIMARY KEY
            (SYVPRDF_PROGRAM, SYVPRDF_TERM_CODE_EFF);

CREATE PUBLIC SYNONYM SYVPRDF FOR BU_APPS.SYVPRDF;
GRANT  SELECT ,INSERT, UPDATE, DELETE ON BU_APPS.SYVPRDF TO PUBLIC;


--------

CREATE TABLE SYRPRCH
(
    SYRPRCH_PROGRAM          VARCHAR2 (12),
    SYRPRCH_TERM_CODE_EFF    VARCHAR2 (6),
    SYRPRCH_AREA             VARCHAR2 (10),
    SYRPRCH_AREA_DESC        VARCHAR (30),
    SYRPRCH_SEQNO            NUMBER (8),
    SYRPRCH_SUBJ_CODE        VARCHAR2 (4),
    SYRPRCH_CRSE_NUMB        VARCHAR2 (5),
    SYRPRCH_TTILE            VARCHAR (30),
    SYRPRCH_REQUIRED_IND     CHAR,
    SYRPRCH_CREDIT_HR        NUMBER (3),
    SYRPRCH_LEC_HR           NUMBER (3),
    SYRPRCH_LAB_HR           NUMBER (3),
    SYRPRCH_ACTIVITY_DATE    DATE,
    SYRPRCH_USER_ID          VARCHAR2 (20),
    SYRPRCH_DATA_ORGIN       VARCHAR2 (20)
);

CREATE PUBLIC SYNONYM SYRPRCH FOR BU_APPS.SYRPRCH;
GRANT SELECT ,INSERT, UPDATE, DELETE ON BU_APPS.SYRPRCH TO PUBLIC;

---------------------

CREATE TABLE SYRPRCD
(
    SYRPRCD_PROGRAM          VARCHAR2 (12),
    SYRPRCD_TERM_CODE_EFF    VARCHAR2 (6),
    SYRPRCD_AREA             VARCHAR2 (10),
    SYRPRCD_SUBJ_CODE_H      VARCHAR2 (4),
    SYRPRCD_CRSE_NUMB_H      VARCHAR2 (5),
    SYRPRCD_SUBJ_CODE        VARCHAR2 (4),
    SYRPRCD_CRSE_NUMB        VARCHAR2 (5),
    SYRPRCD_TTILE            VARCHAR (30),
    SYRPRCD_CREDIT_HR        NUMBER (3),
    SYRPRCD_LEC_HR           NUMBER (3),
    SYRPRCD_LAB_HR           NUMBER (3),
    SYRPRCD_EQLVNT_HR        NUMBER (3),
    SYRPRCD_JOIN_OPERATOR    VARCHAR2 (3),
    SYRPRCD_RT_BRACKET       CHAR,
    SYRPRCD_LT_BRACKET       CHAR,
    SYRPRCD_ACTIVITY_DATE    DATE,
    SYRPRCD_USER_ID          VARCHAR2 (20),
    SYRPRCD_DATA_ORGIN       VARCHAR2 (20)
);

CREATE PUBLIC SYNONYM SYRPRCD FOR BU_APPS.SYRPRCD;
GRANT SELECT ,INSERT, UPDATE, DELETE ON BU_APPS.SYRPRCD TO PUBLIC;