Insert into GENERAL.GUBOBJS
   (GUBOBJS_NAME, GUBOBJS_DESC, GUBOBJS_OBJT_CODE, GUBOBJS_SYSI_CODE, GUBOBJS_USER_ID, 
    GUBOBJS_ACTIVITY_DATE, GUBOBJS_HELP_IND, GUBOBJS_EXTRACT_ENABLED_IND, GUBOBJS_UI_VERSION)
 Values
   ('SWRWF10', 'Workflow Service Setup Report', 'JOBS', 'S', 'LOCAL', 
    TO_DATE('12/30/2018 9:31:17', 'MM/DD/YYYY HH24:MI:SS'), 'N', 'N', 'B');
Insert into BANSECR.GURUOBJ
   (GURUOBJ_OBJECT, GURUOBJ_ROLE, GURUOBJ_USERID, GURUOBJ_ACTIVITY_DATE, GURUOBJ_USER_ID)
 Values
   ('SWRWF10', 'BAN_DEFAULT_M', 'SAISUSR', TO_DATE('12/30/2018 9:42:45', 'MM/DD/YYYY HH24:MI:SS'), 'BANSECR');
Insert into BANSECR.GURUOBJ
   (GURUOBJ_OBJECT, GURUOBJ_ROLE, GURUOBJ_USERID, GURUOBJ_ACTIVITY_DATE, GURUOBJ_USER_ID)
 Values
   ('SWRWF10', 'BAN_DEFAULT_M', 'BU_APPS', TO_DATE('12/30/2018 9:42:45', 'MM/DD/YYYY HH24:MI:SS'), 'BANSECR');
Insert into BANSECR.GURAOBJ
   (GURAOBJ_OBJECT, GURAOBJ_DEFAULT_ROLE, GURAOBJ_CURRENT_VERSION, GURAOBJ_SYSI_CODE, GURAOBJ_ACTIVITY_DATE, 
    GURAOBJ_USER_ID, GURAOBJ_OWNER, GURAOBJ_ACCESS_TRACKING_IND)
 Values
   ('SWRWF10', 'BAN_DEFAULT_M', '8.6', 'S', sysdate, 
    'BU_DEV', 'PUBLIC', 'Y');   
	Insert into GJBJOBS
   (GJBJOBS_NAME, GJBJOBS_TITLE, GJBJOBS_ACTIVITY_DATE, GJBJOBS_SYSI_CODE, GJBJOBS_JOB_TYPE_IND, 
    GJBJOBS_DESC, GJBJOBS_COMMAND_NAME, GJBJOBS_PRNT_FORM, GJBJOBS_PRNT_CODE, GJBJOBS_LINE_COUNT, 
    GJBJOBS_VALIDATION)
 Values
   ('SWRWF10', 'Workflow Template Report', TO_DATE('02/05/2019 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'S', 'R', 
    'Workflow Template Report', NULL, NULL, NULL, NULL, 
    NULL);
    COMMIT;

