 
Insert into GENERAL.GJBJOBS
   (GJBJOBS_NAME, GJBJOBS_TITLE, GJBJOBS_ACTIVITY_DATE, GJBJOBS_SYSI_CODE, GJBJOBS_JOB_TYPE_IND, 
    GJBJOBS_DESC, GJBJOBS_COMMAND_NAME, GJBJOBS_PRNT_FORM, GJBJOBS_PRNT_CODE, GJBJOBS_LINE_COUNT, 
    GJBJOBS_VALIDATION)
 Values
   ('SYPCMPG', '„⁄«œ·… «·Œÿÿ «·œ—«”Ì…', SYSDATE, 'S', 'P', 
    '„⁄«œ·… «·Œÿÿ «·œ—«”Ì…', NULL, NULL, 'DATABASE', NULL, 
    NULL);
 
 
 
 
 
 
 
 
 
 
 
