
update  BANSECR.GURUOBJ set GURUOBJ_ROLE='BAN_DEFAULT_Q'
where GURUOBJ_OBJECT='SPAIDEN'
and GURUOBJ_USERID='AALABDULLAH';

select 'update  BANSECR.GURUOBJ set GURUOBJ_ROLE=''BAN_DEFAULT_Q''
where GURUOBJ_OBJECT=''SPAIDEN''
and GURUOBJ_USERID='''||GURUOBJ_USERID||''';'
from GURUOBJ
where GURUOBJ_OBJECT='SPAIDEN'
and GURUOBJ_ROLE='BAN_DEFAULT_M' ;


--------------
update  BANSECR.GURUOBJ set GURUOBJ_ROLE='BAN_DEFAULT_Q'
where GURUOBJ_OBJECT='SPAIDEN'
and GURUOBJ_USERID='AAAL';
