 
Insert into GLBSLCT
   (GLBSLCT_APPLICATION, GLBSLCT_SELECTION, GLBSLCT_CREATOR_ID, GLBSLCT_DESC, GLBSLCT_LOCK_IND, 
    GLBSLCT_ACTIVITY_DATE, GLBSLCT_TYPE_IND)
 Values
   ('STUDENT', 'BLOCK_REG_143910_k3', 'SAISUSR', 'ÿ·»… «·—“„', 'N', 
    SYSDATE, NULL);
 
 
Insert into GLBEXTR
   SELECT 'STUDENT', 'BLOCK_REG_143910_k3', 'SAISUSR', 'SAISUSR', SFRSTCR_PIDM, 
    SYSDATE, 'S', NULL  FROM 
(  SELECT SFRSTCR_PIDM
            FROM SFRSTCR
           WHERE     SFRSTCR_TERM_CODE = '143920'
                 AND SFRSTCR_RSTS_CODE IN ('RW', 'RE')
                 AND SFRSTCR_CRN = '28425'
        ORDER BY SFRSTCR_PIDM DESC)
 WHERE ROWNUM < 51 ;
 
 
 
 ---------------------------------------------------------------------------------
 Insert into GLBSLCT
   (GLBSLCT_APPLICATION, GLBSLCT_SELECTION, GLBSLCT_CREATOR_ID, GLBSLCT_DESC, GLBSLCT_LOCK_IND, 
    GLBSLCT_ACTIVITY_DATE, GLBSLCT_TYPE_IND)
 Values
   ('STUDENT', 'BLOCK_REG_143920_f16', 'SAISUSR', 'ÿ·»… «·—“„', 'N', 
    SYSDATE, NULL);
 
 
Insert into GLBEXTR
   SELECT 'STUDENT', 'BLOCK_REG_143920_f16', 'SAISUSR', 'SAISUSR', SGBSTDN_PIDM, 
    SYSDATE, 'S', NULL  FROM 
(  SELECT A.SGBSTDN_PIDM  
    FROM SGBSTDN A, bu_dev.temp_tbl01 C
   WHERE     SGBSTDN_TERM_CODE_EFF =
                (SELECT MAX (B.SGBSTDN_TERM_CODE_EFF)
                   FROM SGBSTDN B
                  WHERE     SGBSTDN_TERM_CODE_EFF <= '143920'
                        AND B.SGBSTDN_PIDM = A.SGBSTDN_PIDM)
         AND C.C_COL01 = A.SGBSTDN_PIDM
         AND A.SGBSTDN_BLCK_CODE = 'F16'
ORDER BY A.SGBSTDN_PIDM DESC)
 WHERE ROWNUM < 23 ;