

select a.request_no ,C.ITEM_VALUE from
request_master a ,REQUEST_DETAILS B ,REQUEST_DETAILS C ,WF_REQUEST_FLOW D
where 
object_code='WF_WITHDRAW_COURSE'
AND REQUEST_STATUS='P'
AND A.REQUEST_NO=B.REQUEST_NO 
AND B.SEQUENCE_NO=1
AND B.ITEM_CODE='TERM'
AND B.ITEM_VALUE='144020'
AND B.REQUEST_NO = C.REQUEST_NO
AND B.SEQUENCE_NO=C.SEQUENCE_NO
AND C.ITEM_CODE='CRN'
AND EXISTS (SELECT 'X' FROM GRADES_APPROVAL_EXECLUDED_CRN
WHERE TERM_CODE='144020'
AND CRN=C.ITEM_VALUE)
  AND D.REQUEST_NO = A.REQUEST_NO
  AND USER_PIDM IS NULL 
