/* Formatted on 4/29/2020 5:13:08 PM (QP5 v5.227.12220.39754) */
SELECT a.request_no ,F_GET_STD_NAME(A.REQUESTER_PIDM) NAME ,F_GET_STD_NAME(C.USER_PIDM ) NAME_EMP ,C.ACTION_CODE ,C.NOTES ,TO_CHAR(C.ACTIVITY_DATE,'DD-MM-YYYY HH24:MI')
  FROM request_master a , REQUEST_DETAILS TERM ,WF_REQUEST_FLOW  C
 WHERE objECT_code = 'WF_GRADE_CHANGE'  --AND REQUEST_STATUS = 'P'
 AND TERM.REQUEST_NO=A.REQUEST_NO
 AND TERM.SEQUENCE_NO=1
 AND TERM.ITEM_CODE='TERM'
 AND TERM.ITEM_VALUE='144020'
 AND C.REQUEST_NO=A.REQUEST_NO
 AND FLOW_SEQ=3
  
 ORDER BY 1