/* Formatted on 10/18/2023 2:24:51 PM (QP5 v5.371) */
SELECT COURSES_45.PROGRAM_CODE,
       COURSES_45.TERM_CODE_EFF,
       COURSES_45.AREA_CODE,
       COURSES_45.COURSE_SUBJ_CODE,
       COURSES_45.COURSE_CRSE_NUMB,
         (SELECT MAX (COURSES_45.SEQ_NO)
            FROM PROGRAM_EQUV_COURSES
           WHERE     COURSES_45.PROGRAM_CODE = '1M15ENGL45'
                 AND COURSES_45.TERM_CODE_EFF = '144510'
                 AND COURSE_SUBJ_CODE = COURSES_45.COURSE_SUBJ_CODE
                 AND COURSE_CRSE_NUMB = COURSES_45.COURSE_CRSE_NUMB)
       + ROW_NUMBER ()
             OVER (
                 PARTITION BY    COURSES_45.AREA_CODE
                              || COURSES_45.COURSE_SUBJ_CODE
                              || COURSES_45.COURSE_CRSE_NUMB
                 ORDER BY
                        COURSES_45.AREA_CODE
                     || COURSES_45.COURSE_SUBJ_CODE
                     || COURSES_45.COURSE_CRSE_NUMB)    SEQ_NO,
       COURSES_38.EQUV_SUBJ_CODE,
       COURSES_38.EQUV_CRSE_NUMB,
       COURSES_45.EQUV_HR,
       'OR',
       COURSES_38.RIGHT_BRACKET,
       COURSES_38.LEFT_BRACKET,
       SYSDATE,
       USER
  FROM PROGRAM_EQUV_COURSES COURSES_45, PROGRAM_EQUV_COURSES COURSES_38
 WHERE     COURSES_45.PROGRAM_CODE = '1M15ENGL45'
      -- AND COURSES_45.COURSE_SUBJ_CODE = 'ENGL'
       --AND COURSES_45.COURSE_CRSE_NUMB='1011'
       AND COURSES_45.TERM_CODE_EFF = '144510'
       --
       AND COURSES_38.PROGRAM_CODE = '1M15ENGL38'
       AND COURSES_38.COURSE_SUBJ_CODE = COURSES_45.EQUV_SUBJ_CODE
       AND COURSES_38.COURSE_CRSE_NUMB = COURSES_45.EQUV_CRSE_NUMB
       AND COURSES_38.TERM_CODE_EFF = '143310'