--
-- CAPP_MNPL_LOG_MAIN  (Table) 
--
CREATE TABLE BU_APPS.CAPP_MNPL_LOG_MAIN
(
  PROCESS_ID                   NUMBER(8),
  PROCESS_PURPOSE_IND          CHAR(1 CHAR),
  RUNNING_DATE                 DATE,
  USER_ID                      VARCHAR2(20 CHAR),
  PROCESS_TERMINATION_STATUS   VARCHAR2(20 CHAR),
  PROCESS_TERMINATION_MESSAGE  VARCHAR2(400 CHAR),
  PROGRAM_CODE                 VARCHAR2(12 CHAR),
  PROGRAM_TERM_CODE_EFF        VARCHAR2(6 CHAR)
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


--
-- CAPP_MNPL_LOG_MAIN_PK  (Index) 
--
CREATE UNIQUE INDEX BU_APPS.CAPP_MNPL_LOG_MAIN_PK ON BU_APPS.CAPP_MNPL_LOG_MAIN
(PROCESS_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


--
-- CAPP_MNPL_LOG_MAIN  (Synonym) 
--
CREATE OR REPLACE PUBLIC SYNONYM CAPP_MNPL_LOG_MAIN FOR BU_APPS.CAPP_MNPL_LOG_MAIN;


-- 
-- Non Foreign Key Constraints for Table CAPP_MNPL_LOG_MAIN 
-- 
ALTER TABLE BU_APPS.CAPP_MNPL_LOG_MAIN ADD (
  CONSTRAINT CAPP_MNPL_LOG_MAIN_PK
  PRIMARY KEY
  (PROCESS_ID)
  USING INDEX BU_APPS.CAPP_MNPL_LOG_MAIN_PK
  ENABLE VALIDATE);

GRANT DELETE, INSERT, SELECT, UPDATE ON BU_APPS.CAPP_MNPL_LOG_MAIN TO PUBLIC;




--
-- CAPP_MNPL_LOG_HEADER  (Table) 
--
CREATE TABLE BU_APPS.CAPP_MNPL_LOG_HEADER
(
  PROCESS_ID             NUMBER(8),
  PROGRAM_CODE           VARCHAR2(12 CHAR),
  PROGRAM_TERM_CODE_EFF  VARCHAR2(6 CHAR),
  STD_PIDM               NUMBER(8),
  TOTAL_PROCESSED_CRSE   NUMBER(3),
  TOTAL_PROCESSED_HRS    NUMBER(3)
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


--
-- CAPP_MNPL_LOG_HEADER_PK  (Index) 
--
CREATE UNIQUE INDEX BU_APPS.CAPP_MNPL_LOG_HEADER_PK ON BU_APPS.CAPP_MNPL_LOG_HEADER
(PROCESS_ID, STD_PIDM)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


--
-- CAPP_MNPL_LOG_HEADER  (Synonym) 
--
CREATE OR REPLACE PUBLIC SYNONYM CAPP_MNPL_LOG_HEADER FOR BU_APPS.CAPP_MNPL_LOG_HEADER;


-- 
-- Non Foreign Key Constraints for Table CAPP_MNPL_LOG_HEADER 
-- 
ALTER TABLE BU_APPS.CAPP_MNPL_LOG_HEADER ADD (
  CONSTRAINT CAPP_MNPL_LOG_HEADER_PK
  PRIMARY KEY
  (PROCESS_ID, STD_PIDM)
  USING INDEX BU_APPS.CAPP_MNPL_LOG_HEADER_PK
  ENABLE VALIDATE);

GRANT DELETE, INSERT, SELECT, UPDATE ON BU_APPS.CAPP_MNPL_LOG_HEADER TO PUBLIC;



--
-- CAPP_MNPL_LOG_DETAIL  (Table) 
--
CREATE TABLE BU_APPS.CAPP_MNPL_LOG_DETAIL
(
  PROCESS_ID           NUMBER(8),
  STD_PIDM             NUMBER(8),
  SEQNO                NUMBER(6),
  LHS_SUBJ_CODE        VARCHAR2(4 CHAR),
  LHS_CRSE_NUMB        VARCHAR2(5 CHAR),
  LHS_CREDIT_HR        NUMBER(3),
  REQUIRED_IND         CHAR(1 CHAR),
  RHS_SUBJ_CODE        VARCHAR2(4 CHAR),
  RHS_CRSE_NUMB        VARCHAR2(5 CHAR),
  RHS_SEQNO            NUMBER,
  RHS_EQVLNT_HR        NUMBER(3),
  MAPPING_SUCCESS_IND  CHAR(1 CHAR),
  DATA_TARGET          VARCHAR2(150 CHAR),
  GRDE_CODE_FINAL      VARCHAR2(4 CHAR),
  FAILURE_MESSAGE      VARCHAR2(250 CHAR)
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


--
-- CAPP_MNPL_LOG_DETAIL_PK  (Index) 
--
CREATE UNIQUE INDEX BU_APPS.CAPP_MNPL_LOG_DETAIL_PK ON BU_APPS.CAPP_MNPL_LOG_DETAIL
(PROCESS_ID, STD_PIDM, SEQNO)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


--
-- CAPP_MNPL_LOG_DETAIL  (Synonym) 
--
CREATE OR REPLACE PUBLIC SYNONYM CAPP_MNPL_LOG_DETAIL FOR BU_APPS.CAPP_MNPL_LOG_DETAIL;


-- 
-- Non Foreign Key Constraints for Table CAPP_MNPL_LOG_DETAIL 
-- 
ALTER TABLE BU_APPS.CAPP_MNPL_LOG_DETAIL ADD (
  CONSTRAINT CAPP_MNPL_LOG_DETAIL_PK
  PRIMARY KEY
  (PROCESS_ID, STD_PIDM, SEQNO)
  USING INDEX BU_APPS.CAPP_MNPL_LOG_DETAIL_PK
  ENABLE VALIDATE);

GRANT DELETE, INSERT, SELECT, UPDATE ON BU_APPS.CAPP_MNPL_LOG_DETAIL TO PUBLIC;




--
-- CAPP_MNPL_LOG_NOT_USED  (Table) 
--
CREATE TABLE BU_APPS.CAPP_MNPL_LOG_NOT_USED
(
  PROCESS_ID       NUMBER(8),
  STD_PIDM         NUMBER(8),
  SEQNO            NUMBER(6),
  SUBJ_CODE        VARCHAR2(4 CHAR),
  CRSE_NUMB        VARCHAR2(5 CHAR),
  CREDIT_HOURS     NUMBER(2),
  TITLE            VARCHAR2(30 CHAR),
  GRDE_CODE_FINAL  VARCHAR2(4 CHAR)
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


--
-- CAPP_MNPL_LOG_NOT_USED_PK  (Index) 
--
CREATE UNIQUE INDEX BU_APPS.CAPP_MNPL_LOG_NOT_USED_PK ON BU_APPS.CAPP_MNPL_LOG_NOT_USED
(PROCESS_ID, STD_PIDM, SEQNO)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


--
-- CAPP_MNPL_LOG_NOT_USED  (Synonym) 
--
CREATE OR REPLACE PUBLIC SYNONYM CAPP_MNPL_LOG_NOT_USED FOR BU_APPS.CAPP_MNPL_LOG_NOT_USED;


-- 
-- Non Foreign Key Constraints for Table CAPP_MNPL_LOG_NOT_USED 
-- 
ALTER TABLE BU_APPS.CAPP_MNPL_LOG_NOT_USED ADD (
  CONSTRAINT CAPP_MNPL_LOG_NOT_USED_PK
  PRIMARY KEY
  (PROCESS_ID, STD_PIDM, SEQNO)
  USING INDEX BU_APPS.CAPP_MNPL_LOG_NOT_USED_PK
  ENABLE VALIDATE);

GRANT DELETE, INSERT, SELECT, UPDATE ON BU_APPS.CAPP_MNPL_LOG_NOT_USED TO PUBLIC;




