 

--select * 
delete FROM  PROGRAM_EQUV_COURSES
    WHERE (PROGRAM_CODE, TERM_CODE_EFF, AREA_CODE, COURSE_SUBJ_CODE, COURSE_CRSE_NUMB, SEQ_NO ,EQUV_SUBJ_CODE, EQUV_CRSE_NUMB) NOT IN
    (
        SELECT PROGRAM_CODE, TERM_CODE_EFF, AREA_CODE, COURSE_SUBJ_CODE, COURSE_CRSE_NUMB, min(SEQ_NO) ,EQUV_SUBJ_CODE, EQUV_CRSE_NUMB
        FROM PROGRAM_EQUV_COURSES
        GROUP BY  PROGRAM_CODE, TERM_CODE_EFF, AREA_CODE, COURSE_SUBJ_CODE, COURSE_CRSE_NUMB ,EQUV_SUBJ_CODE, EQUV_CRSE_NUMB
    )
    and PROGRAM_CODE='1M15ARAB38'
    and TERM_CODE_EFF='143310'
    order by PROGRAM_CODE, TERM_CODE_EFF, AREA_CODE, COURSE_SUBJ_CODE, COURSE_CRSE_NUMB  ;
    
    
    select * FROM  PROGRAM_EQUV_COURSES
     where  PROGRAM_CODE='1M15ARAB38'
    and TERM_CODE_EFF='143310'
    and EQUV_SUBJ_CODE|| EQUV_CRSE_NUMB='11020103'
    order by PROGRAM_CODE, TERM_CODE_EFF, AREA_CODE, COURSE_SUBJ_CODE, COURSE_CRSE_NUMB ,EQUV_SUBJ_CODE, EQUV_CRSE_NUMB ;