BEGIN
   CAPP_MANIPULATION_FUNCTIONAL.LOG_DELETE(3900);
    /*  CAPP_MANIPULATION_FUNCTIONAL.LOG_DELETE(500);
          CAPP_MANIPULATION_FUNCTIONAL.LOG_DELETE(400);
          
          GENERAL.GJBPRUN
       */
          commit ;
    SYKCMPG.SYPCMPG;
   COMMIT;
END;

 