/* Formatted on 3/16/2023 3:54:37 PM (QP5 v5.371) */
SELECT DISTINCT SORCMJR_CMJR_RULE,
                SORLFOS_LFOS_RULE,
                SORLFOS_MAJR_CODE||
                SORLFOS_DEPT_CODE,
                SORCMJR_MAJR_CODE,
                SORCMJR_DEPT_CODE ,F_GET_DESC_FNC('STVDEPT',SORCMJR_DEPT_CODE,30) DEPT_DESC
  FROM SORLFOS, SORCMJR
 WHERE     SORCMJR_CMJR_RULE = SORLFOS_LFOS_RULE
      AND SORLFOS_MAJR_CODE || SORLFOS_DEPT_CODE != SORCMJR_MAJR_CODE || SORCMJR_DEPT_CODE
         --  AND SORCMJR_CMJR_RULE='829'
         ORDER BY 1 DESC
           
           ;
 
SELECT DISTINCT sgbstdn_MAJR_CODE_1||sgbstdn_DEPT_CODE FROM SGBSTDN WHERE SGBSTDN_CMJR_RULE_1_1='829' ;
          
            update SORLFOS set   (SORLFOS_MAJR_CODE ,SORLFOS_DEPT_CODE)=(SELECT SORCMJR_MAJR_CODE ,SORCMJR_DEPT_CODE FROM SORCMJR
WHERE SORCMJR_CMJR_RULE = SORLFOS_LFOS_RULE            
 )  
 where  
 SORLFOS_LFOS_RULE IN ( 
 



 
'831',
'828',
'827'  

 
 )

 
   ;
 
 
