 
Insert into BU_APPS.PROGRAM_DEFINITION
   (PROGRAM_CODE, TERM_CODE_EFF, RULE_CODE, ACTIVE_IND, ACTIVITY_DATE, 
    USER_ID)
 Values
   ('1M14MED38', '143310', 'R_CAPP_MED_33', 'Y', sysdate, 
    'BU_APPS');
 INSERT INTO PROGRAM_COURSES
SELECT 
    PROGRAM_CODE, '143310', AREA_CODE, 
   AREA_PRIORITY, SUBJ_CODE, CRSE_NUMB, 
   REQUIRED_IND, ACTIVITY_DATE, USER_ID
FROM BU_APPS.PROGRAM_COURSES
WHERE
PROGRAM_CODE = '1M32MENG38'
AND TERM_CODE_EFF='143810' ;

INSERT INTO BU_APPS.PROGRAM_EQUV_COURSES
SELECT 
  PROGRAM_CODE, '143310', AREA_CODE, 
   COURSE_SUBJ_CODE, COURSE_CRSE_NUMB, SEQ_NO, 
   EQUV_SUBJ_CODE, EQUV_CRSE_NUMB, EQUV_HR, 
   JOIN_OPERATOR, RIGHT_BRACKET, LEFT_BRACKET, 
   ACTIVITY_DATE, USER_ID
FROM BU_APPS.PROGRAM_EQUV_COURSES
WHERE
PROGRAM_CODE = '1M32MENG38'
AND TERM_CODE_EFF='143810' ;
