 F_CAPP_phcl_33
Insert into BU_APPS.RULE_ITEMS
   (ITEM_CODE, ITEM_DESC, DB_FUNCTION, ACTIVITY_DATE, USER_ID)
 Values
   ('I_CAPP_PHCL_33', 'Œÿ… ’Ìœ·… 33', 'F_CAPP_PHCL_33', SYSDATE,USER);
 
 
Insert into BU_APPS.RULE_DEFINITION
   (RULE_CODE, RULE_DESC, ACTIVITY_DATE, USER_ID)
 Values
   ('R_CAPP_PHCL_33', '’Ìœ·… 33', SYSDATE, USER);
 
 
Insert into BU_APPS.RULE_FORMATION
   (RULE_CODE, SEQENCE_NO, ITEM_CODE, OPERATOR, VALUE, 
    ACTIVITY_DATE, USER_ID)
 Values
   ('R_CAPP_PHCL_33', 1, 'I_CAPP_PHCL_33', '=', '''Y''', 
    SYSDATE, USER);
    
  
Insert into BU_APPS.PROGRAM_DEFINITION
   (PROGRAM_CODE, TERM_CODE_EFF, RULE_CODE, ACTIVE_IND, ACTIVITY_DATE, 
    USER_ID)
 Values
   ('1M32EENG38', '143310', 'R_CAPP_PHCL_33', 'Y',SYSDATE, 
    USER);
 

 
