1M38DH38

 F_CAPP_DH_38
 F_CAPP_IT_38
Insert into BU_APPS.RULE_ITEMS
   (ITEM_CODE, ITEM_DESC, DB_FUNCTION, ACTIVITY_DATE, USER_ID)
 Values
   ('I_CAPP_DH_38', 'Œÿ… DH 38', 'F_CAPP_DH_38', SYSDATE,USER);
 
 
Insert into BU_APPS.RULE_DEFINITION
   (RULE_CODE, RULE_DESC, ACTIVITY_DATE, USER_ID)
 Values
   ('R_CAPP_DH_38', 'DH 38', SYSDATE, USER);
 
 
Insert into BU_APPS.RULE_FORMATION
   (RULE_CODE, SEQENCE_NO, ITEM_CODE, OPERATOR, VALUE, 
    ACTIVITY_DATE, USER_ID)
 Values
   ('R_CAPP_DH_38', 1, 'I_CAPP_DH_38', '=', '''Y''', 
    SYSDATE, USER);
    
  
Insert into BU_APPS.PROGRAM_DEFINITION
   (PROGRAM_CODE, TERM_CODE_EFF, RULE_CODE, ACTIVE_IND, ACTIVITY_DATE, 
    USER_ID)
 Values
   ('1M38DH38', '143810', 'R_CAPP_DH_38', 'Y',SYSDATE, 
    USER);
 

 
