/* Formatted on 29/12/2020 14:06:07 (QP5 v5.227.12220.39754) */
CREATE TABLE BU_APPS.SYMTRCL_DEPT_MAPPING
(
   GENERAL_DEPT   VARCHAR2 (4 CHAR),
   DEPT_CODE      VARCHAR2 (4 CHAR),
   COLL_CODE      VARCHAR2 (4 CHAR),
   GENDER         VARCHAR2 (1 CHAR),
   CAMP_CODE      VARCHAR2 (3 CHAR),
   MAJOR_CODE     VARCHAR2 (4 CHAR),
   PROGRAM_CODE   VARCHAR2 (12 CHAR)
);

INSERT INTO BU_APPS.RULE_ITEMS (ITEM_CODE,
                                ITEM_DESC,
                                DB_FUNCTION,
                                ACTIVITY_DATE,
                                USER_ID)
     VALUES ('I_INTRNL_VSTOR',
             'ÿ«·» „‰ «·«ﬁ”«„ «·„ ‰«Ÿ—…',
             'F_INTRNL_VSTOR_FNC',
             TO_DATE ('12/29/2020 00:00:00', 'MM/DD/YYYY HH24:MI:SS'),
             'SAISUSR');


INSERT INTO BU_APPS.RULE_DEFINITION (RULE_CODE,
                                     RULE_DESC,
                                     ACTIVITY_DATE,
                                     USER_ID,
                                     ERROR_MSG)
     VALUES (
               'R_WF_INT_VIST',
               'ﬁ«⁄œ… ÿ·» “«∆— œ«Œ·Ì',
               TO_DATE ('12/29/2020 13:02:55', 'MM/DD/YYYY HH24:MI:SS'),
               'BU_APPS',
               'Â–Â «·Œœ„… „ «Õ… ›ﬁÿ ·ÿ·»… «·√ﬁ”«„ «·„ ‰«Ÿ—… ');

 
Insert into BU_APPS.RULE_FORMATION
   (RULE_CODE, SEQENCE_NO, ITEM_CODE, OPERATOR, VALUE, 
    ACTIVITY_DATE, USER_ID)
 Values
   ('R_WF_INT_VIST', 1, 'STD_STYP', 'IN', '(''„'')', 
    TO_DATE('12/29/2020 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'SAISUSR');
Insert into BU_APPS.RULE_FORMATION
   (RULE_CODE, SEQENCE_NO, ITEM_CODE, OPERATOR, VALUE, 
    CONNECTORS, ACTIVITY_DATE, USER_ID)
 Values
   ('R_WF_INT_VIST', 2, 'I_INTRNL_VSTOR', '=', '''Y''', 
    'AND', TO_DATE('12/29/2020 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'SAISUSR');
Insert into BU_APPS.RULE_FORMATION
   (RULE_CODE, SEQENCE_NO, ITEM_CODE, OPERATOR, VALUE, 
    CONNECTORS, ACTIVITY_DATE, USER_ID)
 Values
   ('R_WF_INT_VIST', 3, 'STD_LEVL', '=', '''Ã„''', 
    'AND', TO_DATE('12/30/2020 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'SAISUSR');
Insert into BU_APPS.RULE_FORMATION
   (RULE_CODE, SEQENCE_NO, ITEM_CODE, OPERATOR, VALUE, 
    CONNECTORS, ACTIVITY_DATE, USER_ID)
 Values
   ('R_WF_INT_VIST', 4, 'STD_STST', '=', '''AS''', 
    'AND', TO_DATE('12/30/2020 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'SAISUSR');
 




INSERT INTO BU_APPS.OBJECT_DEFINITION (OBJECT_CODE,
                                       OBJECT_DESC,
                                       OBJECT_TYPE,
                                       WEB_DISPLAY_IND,
                                       INSTRUCTIONS,
                                       ONE_STEP_FLOW,
                                       RULE_CODE,
                                       ACTIVITY_DATE,
                                       USER_ID,
                                       RULE_APPLY,
                                       SERVICE_ROLE)
     VALUES (
               'WF_INTERNAL_VISITOR',
               'ÿ·» “«∆— œ«Œ·Ì',
               'W',
               'Y',
               '«Œ — «·ﬂ·Ì… «·„‰«Ÿ—… À„ «÷€ÿ ⁄·Ï “—  ‰›Ì–',
               'N',
               'R_WF_INT_VIST',
               TO_DATE ('12/29/2020 00:00:00', 'MM/DD/YYYY HH24:MI:SS'),
               'SAISUSR',
               'A',
               'S');



INSERT INTO BU_APPS.WF_OBJECT_ATTRIBUTES (OBJECT_CODE,
                                          ATTRIBUTE_CODE,
                                          ACTIVITY_DATE,
                                          USER_ID)
     VALUES ('WF_INTERNAL_VISITOR',
             'COLLEGE',
             SYSDATE,
             'BU_APPS');

INSERT INTO BU_APPS.WF_OBJECT_ATTRIBUTES (OBJECT_CODE,
                                          ATTRIBUTE_CODE,
                                          ACTIVITY_DATE,
                                          USER_ID)
     VALUES ('WF_INTERNAL_VISITOR',
             'DEPARTMENT',
             SYSDATE,
             'BU_APPS');
 SET DEFINE OFF;
Insert into BU_APPS.WF_FLOW
   (OBJECT_CODE, FLOW_SEQ, FLOW_DISPLAY, FLOW_PROCEDURE, FLOW_TYPE, 
    HISTORY_IND, ACTIVITY_DATE, USER_ID, MATCH_TYPE, REVIEW_PROCEDURE, 
    ALLOW_BATCH_ACTION)
 Values
   ('WF_INTERNAL_VISITOR', 1, 'C', 'WF_INTERNAL_VISITOR.WFDP_INITIATOR', 'I', 
    'Y', TO_DATE('12/29/2020 12:43:10', 'MM/DD/YYYY HH24:MI:SS'), 'SAISUSR', 'F', 'WF_INTERNAL_VISITOR.WFRP_INITIATOR', 
    'N');
Insert into BU_APPS.WF_FLOW
   (OBJECT_CODE, FLOW_SEQ, FLOW_PROCEDURE, FLOW_TYPE, ROLE_CODE, 
    HISTORY_IND, ACTIVITY_DATE, USER_ID, MATCH_TYPE, REVIEW_PROCEDURE, 
    SEND_EMAIL_TYPE, ALLOW_BATCH_ACTION)
 Values
   ('WF_INTERNAL_VISITOR', 2, 'WF_INTERNAL_VISITOR.WFDP_APPROVER', 'R', 'RO_DEPT_MANAGER', 
    'Y', TO_DATE('12/29/2020 12:43:21', 'MM/DD/YYYY HH24:MI:SS'), 'SAISUSR', 'R', 'WF_INTERNAL_VISITOR.WFRP_APPROVER', 
    'I', 'N');
Insert into BU_APPS.WF_FLOW
   (OBJECT_CODE, FLOW_SEQ, FLOW_PROCEDURE, FLOW_TYPE, ROLE_CODE, 
    HISTORY_IND, ACTIVITY_DATE, USER_ID, MATCH_TYPE, REVIEW_PROCEDURE, 
    SEND_EMAIL_TYPE, ALLOW_BATCH_ACTION)
 Values
   ('WF_INTERNAL_VISITOR', 3, 'WF_INTERNAL_VISITOR.WFDP_APPROVER', 'R', 'RO_COLLEGE_DEAN', 
    'Y', TO_DATE('12/29/2020 12:43:27', 'MM/DD/YYYY HH24:MI:SS'), 'SAISUSR', 'R', 'WF_INTERNAL_VISITOR.WFRP_APPROVER', 
    'N', 'N');
Insert into BU_APPS.WF_FLOW
   (OBJECT_CODE, FLOW_SEQ, FLOW_PROCEDURE, FLOW_TYPE, ROLE_CODE, 
    HISTORY_IND, ACTIVITY_DATE, USER_ID, MATCH_TYPE, REVIEW_PROCEDURE, 
    MATCH_FUNCTION, SEND_EMAIL_TYPE, ALLOW_BATCH_ACTION)
 Values
   ('WF_INTERNAL_VISITOR', 4, 'WF_INTERNAL_VISITOR.WFDP_APPROVER', 'R', 'RO_DEPT_MANAGER', 
    'Y', TO_DATE('12/31/2020 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'SAISUSR', 'A', 'WF_INTERNAL_VISITOR.WFRP_APPROVER', 
    'WF_INTERNAL_VISITOR.WFMF_STEP_4', 'N', 'N');
Insert into BU_APPS.WF_FLOW
   (OBJECT_CODE, FLOW_SEQ, FLOW_PROCEDURE, FLOW_TYPE, ROLE_CODE, 
    HISTORY_IND, ACTIVITY_DATE, USER_ID, MATCH_TYPE, REVIEW_PROCEDURE, 
    MATCH_FUNCTION, SEND_EMAIL_TYPE, ALLOW_BATCH_ACTION)
 Values
   ('WF_INTERNAL_VISITOR', 5, 'WF_INTERNAL_VISITOR.WFDP_APPROVER', 'R', 'RO_COLLEGE_DEAN', 
    'Y', TO_DATE('12/31/2020 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'SAISUSR', 'A', 'WF_INTERNAL_VISITOR.WFRP_APPROVER', 
    'WF_INTERNAL_VISITOR.WFMF_STEP_5', 'N', 'N');
 

 SET DEFINE OFF;
Insert into BU_APPS.WF_FLOW_ACTIONS
   (OBJECT_CODE, FLOW_SEQ, ACTION_CODE, VALIDATION_PROCEDURE, ACTIVITY_DATE, 
    USER_ID, FORWARD_NEXT_STEP, PUBLIC_IND)
 Values
   ('WF_INTERNAL_VISITOR', 1, 'INIT', 'WF_INTERNAL_VISITOR.WFVP_INITIATOR', TO_DATE('12/29/2020 12:45:26', 'MM/DD/YYYY HH24:MI:SS'), 
    'SAISUSR', 'N', 'Y');
Insert into BU_APPS.WF_FLOW_ACTIONS
   (OBJECT_CODE, FLOW_SEQ, ACTION_CODE, ACTIVITY_DATE, USER_ID, 
    FORWARD_NEXT_STEP, PUBLIC_IND)
 Values
   ('WF_INTERNAL_VISITOR', 2, 'APPROVE', TO_DATE('12/29/2020 12:45:31', 'MM/DD/YYYY HH24:MI:SS'), 'SAISUSR', 
    'N', 'Y');
Insert into BU_APPS.WF_FLOW_ACTIONS
   (OBJECT_CODE, FLOW_SEQ, ACTION_CODE, ACTIVITY_DATE, USER_ID, 
    FORWARD_NEXT_STEP, PUBLIC_IND)
 Values
   ('WF_INTERNAL_VISITOR', 2, 'FINAL_REJECT', TO_DATE('12/29/2020 12:45:33', 'MM/DD/YYYY HH24:MI:SS'), 'SAISUSR', 
    'N', 'Y');
Insert into BU_APPS.WF_FLOW_ACTIONS
   (OBJECT_CODE, FLOW_SEQ, ACTION_CODE, ACTIVITY_DATE, USER_ID, 
    FORWARD_NEXT_STEP, PUBLIC_IND)
 Values
   ('WF_INTERNAL_VISITOR', 2, 'HOLD', TO_DATE('12/29/2020 12:45:56', 'MM/DD/YYYY HH24:MI:SS'), 'SAISUSR', 
    'N', 'Y');
Insert into BU_APPS.WF_FLOW_ACTIONS
   (OBJECT_CODE, FLOW_SEQ, ACTION_CODE, ACTIVITY_DATE, USER_ID, 
    FORWARD_NEXT_STEP, PUBLIC_IND)
 Values
   ('WF_INTERNAL_VISITOR', 3, 'APPROVE', TO_DATE('12/29/2020 12:45:39', 'MM/DD/YYYY HH24:MI:SS'), 'SAISUSR', 
    'N', 'Y');
Insert into BU_APPS.WF_FLOW_ACTIONS
   (OBJECT_CODE, FLOW_SEQ, ACTION_CODE, ACTIVITY_DATE, USER_ID, 
    FORWARD_NEXT_STEP, PUBLIC_IND)
 Values
   ('WF_INTERNAL_VISITOR', 3, 'FINAL_REJECT', TO_DATE('12/29/2020 12:55:03', 'MM/DD/YYYY HH24:MI:SS'), 'SAISUSR', 
    'N', 'Y');
Insert into BU_APPS.WF_FLOW_ACTIONS
   (OBJECT_CODE, FLOW_SEQ, ACTION_CODE, ACTIVITY_DATE, USER_ID, 
    FORWARD_NEXT_STEP, PUBLIC_IND)
 Values
   ('WF_INTERNAL_VISITOR', 3, 'HOLD', TO_DATE('12/29/2020 12:45:58', 'MM/DD/YYYY HH24:MI:SS'), 'SAISUSR', 
    'N', 'Y');
Insert into BU_APPS.WF_FLOW_ACTIONS
   (OBJECT_CODE, FLOW_SEQ, ACTION_CODE, ACTIVITY_DATE, USER_ID, 
    FORWARD_NEXT_STEP, PUBLIC_IND)
 Values
   ('WF_INTERNAL_VISITOR', 3, 'REJECT', TO_DATE('12/29/2020 12:45:43', 'MM/DD/YYYY HH24:MI:SS'), 'SAISUSR', 
    'N', 'Y');
Insert into BU_APPS.WF_FLOW_ACTIONS
   (OBJECT_CODE, FLOW_SEQ, ACTION_CODE, ACTIVITY_DATE, USER_ID, 
    FORWARD_NEXT_STEP, PUBLIC_IND)
 Values
   ('WF_INTERNAL_VISITOR', 4, 'APPROVE', TO_DATE('12/29/2020 12:57:12', 'MM/DD/YYYY HH24:MI:SS'), 'SAISUSR', 
    'N', 'Y');
Insert into BU_APPS.WF_FLOW_ACTIONS
   (OBJECT_CODE, FLOW_SEQ, ACTION_CODE, ACTIVITY_DATE, USER_ID, 
    FORWARD_NEXT_STEP, PUBLIC_IND)
 Values
   ('WF_INTERNAL_VISITOR', 4, 'FINAL_REJECT', TO_DATE('12/29/2020 12:45:53', 'MM/DD/YYYY HH24:MI:SS'), 'SAISUSR', 
    'N', 'Y');
Insert into BU_APPS.WF_FLOW_ACTIONS
   (OBJECT_CODE, FLOW_SEQ, ACTION_CODE, ACTIVITY_DATE, USER_ID, 
    FORWARD_NEXT_STEP, PUBLIC_IND)
 Values
   ('WF_INTERNAL_VISITOR', 4, 'HOLD', TO_DATE('12/29/2020 12:46:01', 'MM/DD/YYYY HH24:MI:SS'), 'SAISUSR', 
    'N', 'Y');
Insert into BU_APPS.WF_FLOW_ACTIONS
   (OBJECT_CODE, FLOW_SEQ, ACTION_CODE, ACTIVITY_DATE, USER_ID, 
    FORWARD_NEXT_STEP, PUBLIC_IND)
 Values
   ('WF_INTERNAL_VISITOR', 4, 'REJECT', TO_DATE('12/29/2020 12:56:15', 'MM/DD/YYYY HH24:MI:SS'), 'SAISUSR', 
    'N', 'Y');
Insert into BU_APPS.WF_FLOW_ACTIONS
   (OBJECT_CODE, FLOW_SEQ, ACTION_CODE, VALIDATION_PROCEDURE, EXECUTION_PROCEDURE, 
    ACTIVITY_DATE, USER_ID, FORWARD_NEXT_STEP, PUBLIC_IND)
 Values
   ('WF_INTERNAL_VISITOR', 5, 'FINAL_APPROVE', 'WF_INTERNAL_VISITOR.WFEP_APPROVER', 'WF_INTERNAL_VISITOR.WFEP_APPROVER', 
    TO_DATE('12/31/2020 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'SAISUSR', 'N', 'Y');
Insert into BU_APPS.WF_FLOW_ACTIONS
   (OBJECT_CODE, FLOW_SEQ, ACTION_CODE, ACTIVITY_DATE, USER_ID, 
    FORWARD_NEXT_STEP, PUBLIC_IND)
 Values
   ('WF_INTERNAL_VISITOR', 5, 'FINAL_REJECT', TO_DATE('12/29/2020 12:46:58', 'MM/DD/YYYY HH24:MI:SS'), 'SAISUSR', 
    'N', 'Y');
Insert into BU_APPS.WF_FLOW_ACTIONS
   (OBJECT_CODE, FLOW_SEQ, ACTION_CODE, ACTIVITY_DATE, USER_ID, 
    FORWARD_NEXT_STEP, PUBLIC_IND)
 Values
   ('WF_INTERNAL_VISITOR', 5, 'HOLD', TO_DATE('12/29/2020 12:46:39', 'MM/DD/YYYY HH24:MI:SS'), 'SAISUSR', 
    'N', 'Y');
 
